#!/usr/bin/env python3
"""Gate 1 step 3: write docs/briefs/phase6_budget.md from the export's own JSON. No Blender, no hand numbers.

    python3 export/budget_doc.py

Reads export/out/gate1/export_set.json (always), gltf_gate1.json and manifest.json (if the glTF/pack steps have
run) and export/out/gate1/bake/*.json (whatever the bake queue has finished), and rewrites the budget doc.
Re-run it after every later step; it is idempotent.
"""
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "export" / "out" / "gate1"
DOC = ROOT / "docs" / "briefs" / "phase6_budget.md"
# 8a: these used to be a second copy of the same numbers, and when the lead raised the ENV budget for the
# densified LOD2 shrubs (gate1_common.CLASS_BUDGET, 800 000 -> 902 000) this file went on printing 800 000
# and a headroom of -94 974 against a run that was in fact 7 026 UNDER budget. One source of truth: the
# constants the export set is actually cut against.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gate1_common as g1  # noqa: E402

BUDGET = dict(g1.CLASS_BUDGET)
TOTAL_BUDGET = g1.TOTAL_BUDGET
# Apple GPU ASTC 4x4 = 8 bpp = 1 byte/texel, x1.334 for the full mip chain.
BYTES_PER_TEXEL = 1.0
MIP = 4.0 / 3.0


def mb(b):
    return b / (1024.0 * 1024.0)


def tex_mb(px, n=1, maps=1):
    return mb(px * px * BYTES_PER_TEXEL * MIP) * n * maps


def load(name):
    p = OUT / name
    return json.loads(p.read_text()) if p.exists() else None


def main():
    s = load("export_set.json")
    if s is None:
        raise SystemExit("export/out/gate1/export_set.json missing - run export_set.py -- --gate1 first")
    gl = load("gltf_gate1.json") or {"classes": {}}
    jobs = (load("bake_jobs.json") or {}).get("jobs", [])
    bakes = {}
    for p in sorted((OUT / "bake").glob("*.json")) if (OUT / "bake").exists() else []:
        b = json.loads(p.read_text())
        bakes[b["id"]] = b
    meshes = s["meshes"]
    tot = s["totals"]
    job_by_lo = {j["lo"]: j for j in jobs}

    L = []
    a = L.append
    a("# Phase 6 Gate 1 — geometry and texture budget (export engineer, branch `phase6-export`)")
    a("")
    a(f"Generated by `export/budget_doc.py` from `export/out/gate1/export_set.json` "
      f"(source `{s['source']}`, built in {s['wall_s']} s). Every number below is measured on the export, "
      f"not estimated. Regenerate after any later step.")
    a("")
    a("## Class totals against the plan §2 freeze")
    a("")
    a("| class | placed tris | budget | headroom | unique tris | objects | unique meshes |")
    a("|---|---|---|---|---|---|---|")
    for c in ("ARCH", "ORN", "ENV"):
        pt = tot["placed_tris"][c]
        a(f"| {c} | {pt:,} | {BUDGET[c]:,} | {BUDGET[c] - pt:,} | {tot['unique_tris'][c]:,} | "
          f"{tot['objects'][c]:,} | "
          f"{sum(1 for m in meshes.values() if m['cls'] == c)} |")
    a(f"| **total** | **{tot['placed_total']:,}** | **{TOTAL_BUDGET:,}** | "
      f"**{TOTAL_BUDGET - tot['placed_total']:,}** | {tot['unique_total']:,} | "
      f"{sum(tot['objects'].values()):,} | {tot['unique_meshes']} |")
    a("")
    a(f"Draw-call batches (one per mesh × material slot, with EXT_mesh_gpu_instancing collapsing every "
      f"placement of a shared mesh into one call): **{tot['draw_call_batches']}** for the whole scene, "
      f"budget 400 at the hero station.")
    cam = gl.get("cam01_visible") or s.get("cam01_visible")
    if cam:
        a(f"Measured inside the cam01 frustum: **{cam['batches']} batches**, {cam['objects']:,} placements, "
          f"{cam['placed_tris']:,} placed triangles.")
    a("")
    a("## Per-asset table")
    a("")
    a("One row per unique mesh (that is one GPU batch). `src tris` is the evaluated source triangle count with "
      "modifiers applied; `tris` is what the glb carries. UV1 = the Gate 2 material atlas, UV2 = the Gate 3 "
      "lightmap.")
    for c in ("ARCH", "ORN", "ENV"):
        a("")
        a(f"### {c}")
        a("")
        a("| mesh | source | src tris | target | tris | placements | placed | UV | lightmap | Gate 2/3 texture |")
        a("|---|---|---|---|---|---|---|---|---|---|")
        rows = [(k, v) for k, v in meshes.items() if v["cls"] == c]
        rows.sort(key=lambda kv: -kv[1]["tris"] * kv[1]["placements"])
        for k, m in rows:
            kind = m.get("kind", "")
            if c == "ORN":
                job = job_by_lo.get(k)
                uv = "UV1+UV2"
                lm = f"256 px atlas slot ×{m['placements']}"
                tex = (f"normal+AO {job['size']}² (baked), albedo+rough {job['size']}² at Gate 2"
                       if job else "-")
            elif c == "ARCH":
                uv = "UV1+UV2"
                lm = (f"256 px atlas slot ×{m['placements']}" if m["instanced"] else "own 2K map")
                tex = "albedo/rough/normal 2K per (zone, material) atlas at Gate 2"
            elif kind == "ground":
                uv = "UV1+UV2"
                lm = "own 2K map"
                tex = "albedo/rough/normal 2K at Gate 2"
            elif kind in ("tree_near", "shrub"):
                uv = "source UV"
                lm = "vertex AO (Gate 3)"
                tex = "1K foliage cards as shipped (bake-free)"
            elif kind == "tree_board":
                uv = "UV1"
                lm = "-"
                tex = "octahedral impostor atlas at Gate 3"
            else:
                uv = "source UV"
                lm = "-"
                tex = "flat colour, no bake"
            src = m.get("src_mesh") or (f"{m.get('merged_from', 1)} objects merged")
            a(f"| `{k}` | {src} | {m['src_tris']:,} | {m['target'] or '-'} | {m['tris']:,} | "
              f"{m['placements']} | {m['tris'] * m['placements']:,} | {uv} | {lm} | {tex} |")

    # ---------------------------------------------------------------- textures
    a("")
    a("## Texture plan and resident memory")
    a("")
    a("ASTC 4×4 on the Apple GPU = 8 bpp = 1 byte per texel; ×4/3 for the full mip chain. "
      "(KTX2/UASTC on disk, transcoded to ASTC at load.)")
    a("")
    n2k = sum(1 for j in jobs if j["size"] == 2048)
    n1k = sum(1 for j in jobs if j["size"] == 1024)
    orn_now = tex_mb(2048, n2k, 2) + tex_mb(1024, n1k, 2)
    orn_g2 = tex_mb(2048, n2k, 2) + tex_mb(1024, n1k, 2)     # albedo + roughness at Gate 2
    uv1_groups = s.get("uv1_groups", 0)
    arch_atlases = len({m["material"] for m in meshes.values()
                        if m["cls"] == "ARCH" or (m["cls"] == "ENV" and m.get("kind") == "ground")})
    arch_g2 = tex_mb(2048, arch_atlases, 3)
    lm_assets = s.get("lightmap_assets", 0)
    slots = s.get("lightmap_slots", {})
    lm_atlases = sum(v["atlases"] for v in slots.values())
    lm_mb = tex_mb(2048, lm_assets, 1) + tex_mb(4096, lm_atlases, 1)
    foliage = 15 * tex_mb(1024, 1, 1)
    imp_protos = len({m["src_mesh"] for m in meshes.values() if m.get("kind") == "tree_board"})
    imp_mb = tex_mb(2048, imp_protos, 2)
    a("| set | count | size | maps | resident (MB) | gate |")
    a("|---|---|---|---|---|---|")
    a(f"| ORN normal + AO | {n2k} × 2K, {n1k} × 1K | 2048/1024 | 2 | {orn_now:.0f} | 1 (baked here) |")
    a(f"| ORN albedo + roughness | {n2k} × 2K, {n1k} × 1K | 2048/1024 | 2 | {orn_g2:.0f} | 2 |")
    a(f"| ARCH + ground PBR atlases | {arch_atlases} | 2048 | 3 | {arch_g2:.0f} | 2 |")
    a(f"| lightmaps, own map | {lm_assets} | 2048 | 1 | {tex_mb(2048, lm_assets, 1):.0f} | 3 |")
    pools = ", ".join("%s %d" % (k, v["count"]) for k, v in slots.items())
    a(f"| lightmap slot atlases ({pools}) | {lm_atlases} | 4096 | 1 | "
      f"{tex_mb(4096, lm_atlases, 1):.0f} | 3 |")
    a(f"| foliage cards (as shipped) | 15 | 1024 | 1 | {foliage:.0f} | - |")
    a(f"| tree impostor atlases | {imp_protos} prototypes | 2048 | 2 | {imp_mb:.0f} | 3 |")
    total_tex = orn_now + orn_g2 + arch_g2 + lm_mb + foliage + imp_mb
    a(f"| **total** | | | | **{total_tex:.0f}** | budget 1 200 |")
    a("")
    if total_tex > 1200:
        a(f"Over the 1.2 GB budget by {total_tex - 1200:.0f} MB: the levers, in order, are the "
          f"{imp_protos} impostor atlases (drop to 1K = −{imp_mb * 0.75:.0f} MB), the ORN albedo/roughness "
          f"pair at 1K for every prototype under 2 m, and ETC1S instead of UASTC on the backdrop.")
    else:
        a(f"Under the 1.2 GB budget with {1200 - total_tex:.0f} MB spare.")

    # ---------------------------------------------------------------- trees
    tr = s["tree_rule"]
    a("")
    a("## Trees — the near/far rule and the count")
    a("")
    a(f"**Rule.** {tr['rule']}")
    a("")
    a(f"- trees in the file (LOD1 objects): **{tr['trees_total']}**")
    a(f"- already-blob objects: **{tr['lod2_blob_objects']}** `_LOD1` objects carry a `_LOD2` mesh "
      f"(1 188-1 596 tris) inherited from Phase 5; {tr['lod2_blob_within_radius']} of them are inside the "
      f"25 m radius. They never spend the near budget — they go to the impostor list.")
    a(f"- real-LOD1 trees within 25 m of the walkable surface: "
      f"**{tr['within_radius']}**")
    a(f"- exported as thinned LOD1 geometry (leaf cards halved, branches untouched): "
      f"**{tr['near_exported']}**, {tr['near_tris_used']:,} placed triangles against a "
      f"{tr['near_tris_budget']:,} allowance (ENV budget minus ground, backdrop, shrubs and the billboards)")
    a(f"- exported as tagged billboard quads for the Gate 3 octahedral impostor bake: "
      f"**{tr['far_billboards']}** (2 triangles each, {imp_protos} prototypes)")
    a("")
    a(f"{tr['cut']}")
    a("")
    per_tree = tr["near_tris_used"] // max(1, tr["near_exported"])
    a(f"**The radius rule's own count is {tr['within_radius']}, not {tr['near_exported']}.** "
      f"{tr['within_radius']} real-LOD1 trees are within 25 m of the walkable surface; the ENV allowance pays "
      f"for {tr['near_exported']} of them and the other {tr['within_radius'] - tr['near_exported']} fall to "
      f"the impostor list, closest-to-the-walk first. That is the number to carry to the user alongside the "
      f"texture-memory line.")
    a("")
    a(f"Each further near tree costs {per_tree:,} placed triangles (measured: "
      f"{tr['near_tris_used']:,} / {tr['near_exported']}). The ARCH class is "
      f"{BUDGET['ARCH'] - tot['placed_tris']['ARCH']:,} triangles under its budget and the scene total is "
      f"{TOTAL_BUDGET - tot['placed_total']:,} under 3.0 M, i.e. room for "
      f"{(TOTAL_BUDGET - tot['placed_total']) // per_tree} more real-LOD1 near trees if the lead reallocates "
      f"the headroom; not taken here, the class budgets stand as frozen.")

    # ---------------------------------------------------------------- bakes and packing
    a("")
    a("## Bake queue (ORN normal + AO, Gate 1)")
    a("")
    if bakes:
        a("| prototype | size | lo tris | hi tris | cage (m) | normal s | AO s | normal B | AO B |")
        a("|---|---|---|---|---|---|---|---|---|")
        for jid in sorted(bakes):
            b = bakes[jid]
            a(f"| {jid} | {b['size']} | {b['tris']:,} | {b['src_tris']:,} | {b['cage_extrusion_m']} | "
              f"{b['normal']['bake_s']} | {b['ao']['bake_s']} | {b['normal']['bytes']:,} | "
              f"{b['ao']['bytes']:,} |")
        tn = sum(b["normal"]["bake_s"] for b in bakes.values())
        ta = sum(b["ao"]["bake_s"] for b in bakes.values())
        a("")
        a(f"{len(bakes)} of {len(jobs)} jobs finished; {tn:.0f} s of normal bakes and {ta:.0f} s of AO bakes.")
    else:
        a(f"{len(jobs)} jobs queued, none finished yet "
          f"({sum(1 for j in jobs if j['size'] == 2048)} at 2K, "
          f"{sum(1 for j in jobs if j['size'] == 1024)} at 1K). "
          f"Live state: `export/out/bake_queue/status.json`.")

    if gl["classes"]:
        a("")
        a("## Packed output")
        a("")
        a("| class | objects | placed tris | gltf bytes | glb bytes |")
        a("|---|---|---|---|---|")
        man = load("manifest.json") or {}
        per = (man.get("glb") or {}).get("per_class", {})
        for c, v in gl["classes"].items():
            gb = per.get(c, {}).get("bytes")
            a(f"| {c} | {v['objects']:,} | {v['placed_tris']:,} | {v['bytes']:,} | "
              f"{gb:,} |" if gb else
              f"| {c} | {v['objects']:,} | {v['placed_tris']:,} | {v['bytes']:,} | - |")
        a("")
    # ---------------------------------------------------------------- known items
    a("")
    a("## Known items and hand-offs")
    a("")
    man0 = load("manifest.json") or {}
    lod1_lo = man0.get("orn_lo_from_lod1") or s.get("orn_lo_from_lod1") or {}
    if lod1_lo:
        a(f"1. **The {len(lod1_lo)} ORN attic panels take their low-poly from the Phase 5 `_LOD1` mesh, not "
          f"from LOD0.** COLLAPSE stalls on the LOD0 relief (~40 000 separate islands) and the voxel shell "
          f"that replaced it read torn at cam02/cam05 (QA round 11 blocker 2). From `_LOD1` "
          f"({'/'.join(str(v['lo_source_tris']) for v in lod1_lo.values())} tris) the collapse is clean to "
          f"{'/'.join(str(v['out_tris']) for v in lod1_lo.values())}, and the lo->hi deviation dropped from "
          f"367/457/412 mm to "
          f"{'/'.join(str(round(bakes[i]['deviation_m']['max'] * 1000)) for i in sorted(bakes) if 'attic_panel' in i)} mm "
          f"with the normal map's blue mean back at "
          f"{'/'.join(format(bakes[i]['normal']['stats']['mean'][2], '.3f') for i in sorted(bakes) if 'attic_panel' in i)} "
          f"(0.79-0.86 before, 0.97 on a clean pair). The hi-poly bake source is still the LOD0 prototype.")
    remeshed = set(man0.get("voxel_remeshed") or s.get("voxel_remeshed") or [])
    proto_of = {k: v.get("src_mesh") for k, v in meshes.items()}
    deep = [b for b in bakes.values()
            if any(proto_of.get(mn) == b["prototype"] for mn in remeshed)] if remeshed else []
    if deep:
        a(f"1b. **{len(deep)} meshes are voxel-remeshed lo-polys.** COLLAPSE stalls on ~40 000 "
          f"relief islands, so the 8 k lo is a voxel shell: lo->hi deviation mean 44-54 mm, max "
          f"{max(b['deviation_m']['max'] for b in deep) * 1000:.0f} mm, cage "
          f"{min(b['cage_extrusion_m'] for b in deep)}-{max(b['cage_extrusion_m'] for b in deep)} m, and the "
          f"normal map's blue mean is 0.79-0.81 against 0.97 on a clean pair. The relief is all in the map. "
          f"A 10.5 x 5.3 m panel sits at z = 30.5 m and is small at every station; re-check it in the Gate 1 "
          f"tile review and retopologise by hand only if it reads flat.")
    orn_glb = ((load("manifest.json") or {}).get("glb") or {}).get("per_class", {}).get("orn", {})
    if orn_glb:
        a(f"2. **`orn.glb` is {mb(orn_glb['bytes']):.0f} MB**, almost all of it the 66 UASTC normal/AO maps "
          f"(2K UASTC q2 + zstd 18 is ~2.6 MB per map). Fine for 6a on this Mac; for the 6b 50 MB initial "
          f"payload the levers are ETC1S for the AO maps (smooth grey, compresses ~5x better), 1K for every "
          f"prototype under 2 m, and streaming `orn.glb` after `arch.glb` + `ground.glb` (3.7 MB together).")
    a("3. **UV2 (TEXCOORD_1) ships in arch/orn/ground but carries no texture yet** — the lightmaps arrive at "
      "Gate 3, where the per-instance slot offsets in `manifest.orn_slots` become the atlas lookup. `env.glb` "
      "has no UV2: foliage and the backdrop are vertex-AO / flat-colour by plan.")
    a("4. **Materials are neutral grey** (one per atlas group, plus an 8x8 grey base-colour probe so "
      "TEXCOORD_0 reaches every glb) except the foliage, which keeps its original bark/leaf materials so the "
      "silhouette check has the leaf alpha. PBR lands at Gate 2 on UV1.")
    # 8d (docs/reviews/phase8_env_r2_review.md): the group absorbed the hall-belt trees (+6 900 tris), so it
    # is no longer only the far shore - the belt stands on the hall's east face, ~150 m from the hero.
    a("5. `ENV_backdropgroup_backdrop_forest` is 106 540 triangles of backdrop canopy, 11.8 % of the whole "
      "ENV budget, and nothing in it is closer than ~150 m (the hall-belt trees 8d merged into it) — the "
      "cheapest remaining ENV saving if the lead wants more near trees.")
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text("\n".join(L) + "\n")
    print(f"[budget_doc] wrote {DOC} ({os.path.getsize(DOC)} B, {len(L)} lines)")


if __name__ == "__main__":
    main()
