"""Phase 6c item D: the foliage cards' albedo, translucency and normal maps, as the Phase 5 MATERIAL has
them rather than as the raw texture.

    scripts/blender_run.sh 600 -- --background master_delivery.blend --python export/read_foliage.py
    python3 export/foliage_tex.py            # -> export/out/gate3/foliage/tex/*.png + foliage_tex.json
    export/gltf_pack.sh --foliage            # -> export/out/gate3/foliage/tex_ktx2/*.ktx2

No Blender and no bake: every term this composes is a CONSTANT the node graph multiplies the image by, read
out of master_delivery.blend by export/read_foliage.py. The two terms it deliberately drops are the
per-instance ones (`hsv` from Object Info Random and the object-space `cluster` noise), which are
identity-centred variation a shared texture cannot carry; they are pinned to identity, which is what they
average to.

WHAT THIS FIXES. `env.glb` ships each card's raw 1 K PNG as `baseColorTexture`, and the Phase 5 material is
`image * TINT`. Measured (foliage_tex.json `stats`): the three shrub materials share one texture and are a
green, a paler green and a STRAW one in Blender - hue 95.0 / 94.2 / 36.1 deg, value 0.46 / 0.52 / 0.60 -
while the viewer draws three identical cards at hue 95.4 and value 0.34. MAT_reeds ships at 0.49 instead of
0.65. So the shipped foliage is not "45 deg too warm" in its albedo: its albedo is the untinted texture,
about 1.9x too dark on the shrubs and missing the dry shrub entirely. The warmth QA measured at cam02 is in
the SHADING, and the term the viewer is missing there is the Translucent branch - a green-biased multiplier
(0.85, 1.15, 0.60) at `maprange(trn, 0.05, 0.85, 0.35, 1.55) * translucency` - which is why this script also
ships the translucency factor map item C needs.

RESOLUTION - 1 K ONLY (lead decision 2, docs/decisions.md 2026-09-17 "6c export findings"). The brief asked
for 2048; **every foliage source in master_delivery is 1024x1024** (they are generated by
scripts/mat_leaf_textures.py at 1 K), so a 2 K map was an upsample: 4x the texture memory, no new detail, its
only real gain a smoother alpha edge at 3 m. Round 1 built and shipped both (13.0 MB at 1 K against 46.0 MB at
2 K); the lead dropped the 2 K set, so `PX_SET` is `(1024,)` and the manifest carries one size. A genuine 2 K
would mean re-running the generator, which changes a Phase 5 material source and needs the user's approval.
Stale outputs from an earlier `PX_SET` are deleted at the end of the run so `tex/` always matches `PX_SET`.
"""
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))

SCHEMA = "pfa-phase6c/foliage-tex/1"
ROOT = Path(__file__).resolve().parents[1]
MAIN_ROOT = Path(os.environ.get("PFA_MAIN_ROOT", "/Users/dk/Projects/3d render blender 3rd attempt building"))
OUT = ROOT / "export" / "out" / "gate3" / "foliage"
TEX = OUT / "tex"
PX_SET = (1024,)


def pick(rel):
    for base in (ROOT, MAIN_ROOT):
        p = base / rel
        if p.exists():
            return p
    raise FileNotFoundError(rel)


def s2l(c):
    return np.where(c <= 0.04045, c / 12.92, ((np.clip(c, 0, None) + 0.055) / 1.055) ** 2.4)


def l2s(c):
    c = np.clip(c, 0.0, 1.0)
    return np.where(c <= 0.0031308, c * 12.92, 1.055 * c ** (1.0 / 2.4) - 0.055)


def hsv_of(rgb_srgb):
    r, g, b = [float(v) for v in rgb_srgb]
    mx, mn = max(r, g, b), min(r, g, b)
    d = mx - mn
    if d < 1e-9:
        h = 0.0
    elif mx == r:
        h = (60.0 * ((g - b) / d)) % 360.0
    elif mx == g:
        h = 60.0 * ((b - r) / d) + 120.0
    else:
        h = 60.0 * ((r - g) / d) + 240.0
    return round(h, 1), round(0.0 if mx == 0 else d / mx, 3), round(mx, 3)


def resample_rgba(lin, alpha, px):
    """Alpha-weighted (premultiplied) resample of a linear RGBA image, so the transparent background cannot
    bleed a dark halo into the leaf edge."""
    pm = lin * alpha[..., None]
    out = np.stack([np.asarray(Image.fromarray(pm[..., k].astype(np.float32))
                               .resize((px, px), Image.LANCZOS), dtype=np.float64) for k in range(3)], -1)
    a = np.asarray(Image.fromarray(alpha.astype(np.float32)).resize((px, px), Image.LANCZOS),
                   dtype=np.float64)
    a = np.clip(a, 0.0, 1.0)
    return np.where(a[..., None] > 1e-4, out / np.maximum(a[..., None], 1e-4), 0.0), a


def resample_grey(g, px):
    return np.asarray(Image.fromarray(g.astype(np.float32)).resize((px, px), Image.LANCZOS),
                      dtype=np.float64)


def main():
    pp = pick("export/out/gate3/foliage/params.json")
    par = json.loads(pp.read_text())
    assert par.get("schema") == "pfa-phase6c/foliage-params/1", f"params schema {par.get('schema')!r}"
    TEX.mkdir(parents=True, exist_ok=True)
    rep = dict(schema=SCHEMA, generated=time.strftime("%Y-%m-%dT%H:%M:%S"),
               generator="export/foliage_tex.py", params=str(pp), sizes=list(PX_SET),
               note="albedo = clip(image_linear * tint); the hsv and cluster terms are per-instance "
                    "variation pinned to identity. translucency factor = clip(maprange(trn) * constant).",
               materials={}, normals={})
    src_cache = {}
    written = set()
    for mat, e in sorted(par["materials"].items()):
        ai = e["albedo_image"]
        ap = ai.get("path") or str(MAIN_ROOT / "assets" / "textures" / "foliage" / ai["file"])
        assert os.path.exists(ap), f"{mat}: albedo source {ap} is not on disk"
        if ap not in src_cache:
            src_cache[ap] = np.asarray(Image.open(ap).convert("RGBA"), dtype=np.float64) / 255.0
        im = src_cache[ap]
        lin, alpha = s2l(im[..., :3]), im[..., 3]
        tint = np.array(e["tint"], dtype=np.float64)
        tinted = lin * tint
        msk = alpha > e["alpha_cutoff"]
        clipped = float((tinted[msk] > 1.0).any(axis=-1).mean()) if msk.any() else 0.0
        stats = dict(
            source=os.path.basename(ap), source_px=list(ai["size"]), tint=e["tint"],
            src_hsv=hsv_of(l2s(lin[msk].mean(axis=0))) if msk.any() else None,
            tinted_hsv=hsv_of(l2s(np.clip(tinted[msk], 0, 1).mean(axis=0))) if msk.any() else None,
            clipped_texel_fraction=round(clipped, 4),
            coverage=round(float(msk.mean()), 4), alpha_cutoff=e["alpha_cutoff"])
        files = {}
        for px in PX_SET:
            rgb, a = resample_rgba(np.clip(tinted, 0.0, 1.0), alpha, px)
            rgba = np.concatenate([l2s(rgb), a[..., None]], axis=-1)
            p = TEX / f"foliage_{mat}_albedo_{px}.png"
            Image.fromarray(np.round(np.clip(rgba, 0, 1) * 255.0).astype(np.uint8)).save(p)
            files[f"albedo_{px}"] = p.name
            written.add(p.name)
        # ---- translucency factor: maprange(trn, from_min, from_max -> to_min, to_max) * constant
        tr = e.get("translucency") or {}
        fac = tr.get("factor") or {}
        mr, tmap, k = fac.get("map_range"), fac.get("map"), fac.get("constant")
        tstat = dict(colour_multiplier=tr.get("colour_multiplier"), constant=k)
        if tmap and mr and k is not None:
            tp = tmap.get("path") or str(MAIN_ROOT / "assets" / "textures" / "foliage" / tmap["file"])
            assert os.path.exists(tp), f"{mat}: translucency source {tp} is not on disk"
            t = np.asarray(Image.open(tp).convert("L"), dtype=np.float64) / 255.0   # Non-Color, already linear
            fm, fx = float(mr["From Min"]), float(mr["From Max"])
            tm, tx = float(mr["To Min"]), float(mr["To Max"])
            f = np.clip((t - fm) / max(fx - fm, 1e-9), 0.0, 1.0) * (tx - tm) + tm
            f = np.clip(f * float(k), 0.0, 1.0)
            tstat.update(source=os.path.basename(tp), map_range=[fm, fx, tm, tx],
                         factor_min=round(float(f.min()), 4), factor_max=round(float(f.max()), 4),
                         factor_mean_in_leaf=round(float(f[msk].mean()), 4) if msk.any() else None,
                         encoding="linear grey, the mix factor itself: 0 = the Principled branch, "
                                  "1 = the Translucent branch, whose colour is albedo * colour_multiplier")
            for px in PX_SET:
                g = np.clip(resample_grey(f, px), 0.0, 1.0)
                p = TEX / f"foliage_{mat}_translu_{px}.png"
                Image.fromarray(np.round(g * 255.0).astype(np.uint8)).save(p)
                files[f"translu_{px}"] = p.name
                written.add(p.name)
        else:
            tstat["constant_only"] = True
            tstat["note"] = "no translucency map in the graph: apply `constant` uniformly"
        # ---- the normal map, shared per source texture
        nm = e.get("normal") or {}
        ni = nm.get("image")
        if ni:
            np_path = ni.get("path") or str(MAIN_ROOT / "assets" / "textures" / "foliage" / ni["file"])
            key = os.path.splitext(os.path.basename(np_path))[0]
            if key not in rep["normals"]:
                assert os.path.exists(np_path), f"{mat}: normal source {np_path} is not on disk"
                n = np.asarray(Image.open(np_path).convert("RGB"), dtype=np.float64) / 255.0
                nf = {}
                for px in PX_SET:
                    o = np.stack([resample_grey(n[..., k], px) for k in range(3)], -1)
                    p = TEX / f"foliage_{key}_{px}.png"
                    Image.fromarray(np.round(np.clip(o, 0, 1) * 255.0).astype(np.uint8)).save(p)
                    nf[str(px)] = p.name
                    written.add(p.name)
                rep["normals"][key] = dict(source=os.path.basename(np_path), source_px=list(ni["size"]),
                                           files=nf, colorspace="linear (Non-Color)",
                                           convention="tangent space, +X +Y +Z (OpenGL)")
            files["normal"] = key
            tstat["normal_strength"] = nm.get("strength")
        rep["materials"][mat] = dict(files=files, stats=stats, translucency=tstat,
                                     roughness=e["roughness"], specular=e["specular"], sheen=e["sheen"],
                                     alpha_mode="MASK", alpha_cutoff=e["alpha_cutoff"],
                                     double_sided=not e["backface_culling"])
    # idempotent: a PNG from an earlier PX_SET (the dropped 2 K set) must not survive into gltf_pack.sh
    stale = sorted(q.name for q in TEX.glob("*.png") if q.name not in written)
    for name in stale:
        (TEX / name).unlink()
    rep["stale_removed"] = stale
    (OUT / "foliage_tex.json").write_text(json.dumps(rep, indent=1) + "\n")
    n = len(list(TEX.glob("*.png")))
    if stale:
        print(f"[foliage_tex] removed {len(stale)} stale PNG from an earlier PX_SET")
    print(f"[foliage_tex] {len(rep['materials'])} materials, {len(rep['normals'])} normal sets, "
          f"{n} PNG at {PX_SET} -> {TEX}")
    for m, v in rep["materials"].items():
        s = v["stats"]
        print(f"  {m:20s} hue {s['src_hsv'][0]:6.1f} -> {s['tinted_hsv'][0]:6.1f}   "
              f"val {s['src_hsv'][2]:.3f} -> {s['tinted_hsv'][2]:.3f}   "
              f"clip {s['clipped_texel_fraction']:.3f}   "
              f"translu x{v['translucency'].get('constant')} "
              f"{v['translucency'].get('factor_min')}..{v['translucency'].get('factor_max')}")


if __name__ == "__main__":
    main()
