#!/usr/bin/env python3
"""6b Gate 5 item D: the export hand-off report.

    python3 export/gate5_report.py            # -> docs/briefs/phase6b_export_report.md

Reads only what the other Gate 5 scripts wrote (`manifest.json`, `manifest_mobile.json`,
`visibility.json`, `lowres.json`, `verify_gate5_*.json`) plus the bytes on disk in MAIN, and prints
the tables the brief asks for.  Nothing is computed twice: a number here that disagrees with the
manifest is a bug in this file, not a second opinion.
"""
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gate5_common as G

MB = 1e6


def tier_table(man):
    t = man["tiers"]
    rows = []
    for k in sorted(t["bytes"]):
        rows.append((k, t["files"][k], t["bytes"][k]))
    return rows


def by_kind(man):
    b, n = defaultdict(int), defaultdict(int)
    for e in man["files"]:
        key = (e["tier"], e["kind"])
        b[key] += e["bytes"] or 0
        n[key] += 1
    return b, n


def present_in_main(man):
    """Every published file, resolved against MAIN's out/gate5 - what the viewer will actually fetch."""
    missing = []
    for e in man["files"]:
        if not (G.PUB_BASE / e["path"]).exists():
            missing.append(e["path"])
    return missing


def main():
    out = G.OUT
    man = json.loads((out / "manifest.json").read_text())
    mob = json.loads((out / "manifest_mobile.json").read_text())
    vis = json.loads((out / "visibility.json").read_text())
    lr = json.loads((out / "lowres.json").read_text())
    v5 = {v: json.loads((out / f"verify_gate5_{v}.json").read_text())
          for v in ("desktop", "mobile") if (out / f"verify_gate5_{v}.json").exists()}
    v4 = G.manifest()

    L = []
    a = L.append
    a("# Phase 6b Gate 5 — export hand-off (tiers, groups, mobile)\n")
    a("Generated by `export/gate5_report.py` from `export/out/gate5/*.json`; every number is the one "
      "in the manifests, read back, not a second computation. Branch `phase6b-export`.\n")

    a("## Tier bytes\n")
    a("| variant | tier | files | bytes | MB |")
    a("|---|---|---|---|---|")
    for name, m in (("desktop", man), ("mobile", mob)):
        for k, n, b in tier_table(m):
            a(f"| {name} | {k} | {n} | {b:,} | {b / MB:.1f} |")
        tot = sum(m["tiers"]["bytes"].values())
        a(f"| {name} | **all** | {sum(m['tiers']['files'].values())} | {tot:,} | **{tot / MB:.1f}** |")
    a("")
    a(f"Tier 0 budget 50 MB: desktop **{man['tiers']['bytes']['0'] / MB:.1f} MB** "
      f"({'within' if man['tiers']['tier0_within_budget'] else 'OVER'}), mobile "
      f"**{mob['tiers']['bytes']['0'] / MB:.1f} MB** "
      f"({'within' if mob['tiers']['tier0_within_budget'] else 'OVER'}).")
    a(f"The same look at Gate 3 was **{sum(p.bytes or 0 for p in G.resolve_files(v4).values()) / MB:.1f} "
      f"MB** over {len(G.resolve_files(v4))} files, with `orn.glb` (154.3 MB) and `env.glb` (38.1 MB) "
      "both over the 25 MiB per-file cap.\n")

    a("## What is in each tier\n")
    for name, m in (("desktop", man), ("mobile", mob)):
        b, n = by_kind(m)
        a(f"**{name}**\n")
        a("| tier | kind | files | MB |")
        a("|---|---|---|---|")
        for k in sorted(b, key=lambda k: (k[0], -b[k])):
            a(f"| {k[0]} | {k[1]} | {n[k]} | {b[k] / MB:.2f} |")
        a("")

    a("## Per-file cap (Cloudflare Pages, 25 MiB)\n")
    for name, m in (("desktop", man), ("mobile", mob)):
        ov = m["tiers"]["oversize"]
        a(f"- {name}: **{len(ov)}** files over the cap"
          + ("." if not ov else ": " + ", ".join(f"`{o['path']}` ({o['bytes']:,} B)" for o in ov)))
    big = sorted(((e["bytes"] or 0, e["path"]) for e in man["files"]), reverse=True)[:5]
    a("- desktop's five biggest published files: "
      + ", ".join(f"`{os.path.basename(p)}` {b / MB:.1f} MB" for b, p in big) + "\n")

    a("## ETC1S: wall time and size per texture class\n")
    a("| block | files | MB | wall s | encoder |")
    a("|---|---|---|---|---|")
    for k, v in lr.items():
        if not isinstance(v, dict) or "files" not in v:
            continue
        tot = sum(f["bytes"] for f in v["files"].values())
        a(f"| {k} | {len(v['files'])} | {tot / MB:.2f} | {v.get('wall_s')} | "
          f"`{v.get('encoder')} /{v.get('resize_div')}` |")
    a("")
    probe = lr.get("probe") or []
    if probe:
        a("The choice the brief left open, measured per map (bytes / RMS against the source png in "
          "linear light, the decoded image brought back to the source resolution):\n")
        a("| map | src px | ETC1S | ETC1S /2 | ETC1S /4 | UASTC /4 |")
        a("|---|---|---|---|---|---|")
        for r in probe:
            if "etc1s" not in r:
                continue
            a(f"| {r['tag']} `{r['key'][-34:]}` | {r['src_px']} | "
              + " | ".join(f"{r[k]['bytes'] / 1e3:.0f} kB / {r[k]['rms']:.4f}"
                           for k in ("etc1s", "etc1s_h2", "etc1s_q4", "uastc_q4")) + " |")
        a("\n**Half-resolution ETC1S wins the brief's test** — smaller AND lower RMS than quarter-res "
          "UASTC on 5 of the 6 sampled maps, and 8-15x smaller on the two normals for +0.0005 RMS — so "
          "that is what tier 0 and the whole mobile set use.\n")

    a("## Mobile resident estimate (ASTC 4x4, 1 byte/texel x 4/3 for mips)\n")
    a("| kind | MB |")
    a("|---|---|")
    for k, v in sorted(mob["tiers"]["resident_estimate_mb"]["by_kind"].items(), key=lambda x: -x[1]):
        a(f"| {k} | {v:.1f} |")
    a(f"| **total** | **{mob['tiers']['resident_estimate_mb']['total']:.0f}** |")
    a(f"\nTarget on the iPhone 16 Pro: **< 700 MB**. Desktop, by the same rule: "
      f"{man['tiers']['resident_estimate_mb']['total']:.0f} MB (manifest v4's own carried figure is "
      f"{v4['budget']['resident_mb']['total']:.0f} MB, so the rule reproduces).\n")

    a("## Hero-visible assets not in tier 0\n")
    t0_assets = set()
    for g in man["glb"]["groups"]:
        if g.get("tier") == 0:
            t0_assets |= set(g["assets"])
    for e in man["files"]:
        if e["tier"] == 0 and e["kind"] == "glb":
            cls = os.path.basename(e["path"]).replace(".glb", "")
            t0_assets |= {n for n, r in v4["assets"].items()
                          if ("ground" if r.get("kind") == "ground" else
                              "arch" if r["cls"] == "ARCH" else
                              "orn" if r["cls"] == "ORN" else "env") == cls}
    hero = {n for n, x in vis["assets"].items() if x["hero"] > 0}
    out_of_t0 = sorted(hero - t0_assets)
    boards = [n for n in out_of_t0 if "treeboard" in n]
    other = [n for n in out_of_t0 if "treeboard" not in n]
    a(f"- {len(hero)} assets are visible from the hero station at the 640x360 ray grid.")
    a(f"- **{len(other)}** of them are not in tier 0"
      + ("." if not other else f": {other[:10]} — these are a defect, not an exception."))
    a(f"- {len(boards)} `ENV_treeboard_*` stand-ins are deliberately not in tier 0: the viewer hides "
      "them by default (`?treeboards=0` since 6a, web/src/main.js) and draws those trees from the "
      "impostor atlases, which ARE in tier 0 at half resolution. Their pixels are covered.\n")

    a("## Verification (`export/verify_glb.py --gate5`)\n")
    a("| variant | assets | files | arch | orn | env | ground | result |")
    a("|---|---|---|---|---|---|---|---|")
    for v, r in v5.items():
        rat = {c: f"{d.get('ratio', '-')}" for c, d in r["per_class"].items()}
        a(f"| {v} | {r['assets_covered']}/{r['assets_expected']} | {r['files']} | "
          f"{rat.get('arch', '-')} | {rat.get('orn', '-')} | {rat.get('env', '-')} | "
          f"{rat.get('ground', '-')} | {'PASS' if not r['fail'] else 'FAIL: ' + '; '.join(r['fail'])} |")
    a("\nThe ratio is triangles DRAWN against `glb.per_class[cls].placed_tris` at Gate 3. Desktop's "
      "0.9981 / 0.9984 on arch and orn are the same degenerate-triangle loss Gate 3 itself reported "
      "(-0.185 % / -0.157 %); env and ground are exact. The mobile ratios are `gltfpack -si 0.5` on "
      "ARCH and ORN, which is the brief's \"decimated LOD0 at half the Gate 1 budget\" - the export set "
      "has no ARCH/ORN LOD1 to ship instead.\n")

    a("## Files in MAIN\n")
    for name, m in (("desktop", man), ("mobile", mob)):
        miss = present_in_main(m)
        a(f"- {name}: {len(m['files'])} published files, **{len(miss)} missing** from "
          f"`{G.PUB_BASE}`" + ("." if not miss else f": {miss[:5]}"))
    a("")

    p = G.MAIN / "docs/briefs/phase6b_export_report.md"
    local = Path(__file__).resolve().parents[1] / "docs/briefs/phase6b_export_report.md"
    local.parent.mkdir(parents=True, exist_ok=True)
    local.write_text("\n".join(L) + "\n")
    print(f"[gate5report] wrote {local} ({local.stat().st_size} B)")


if __name__ == "__main__":
    main()
