#!/usr/bin/env python3
"""6b Gate 5 item D: the export hand-off report.

    python3 export/gate5_report.py            # -> docs/briefs/phase6b_export_report.md

Reads only what the other Gate 5 scripts wrote (`manifest.json`, `manifest_mobile.json`,
`visibility.json`, `lowres.json`, `verify_gate5_*.json`) plus the bytes on disk in MAIN, and prints
the tables the brief asks for.  Nothing is computed twice: a number here that disagrees with the
manifest is a bug in this file, not a second opinion.
"""
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gate5_common as G

MB = 1e6


def tier_table(man):
    t = man["tiers"]
    rows = []
    for k in sorted(t["bytes"]):
        rows.append((k, t["files"][k], t["bytes"][k]))
    return rows


def by_kind(man):
    b, n = defaultdict(int), defaultdict(int)
    for e in man["files"]:
        key = (e["tier"], e["kind"])
        b[key] += e["bytes"] or 0
        n[key] += 1
    return b, n


def present_in_main(man):
    """Every published file, resolved against MAIN's out/gate5 - what the viewer will actually fetch."""
    missing = []
    for e in man["files"]:
        if not (G.PUB_BASE / e["path"]).exists():
            missing.append(e["path"])
    return missing


def main():
    out = G.OUT
    man = json.loads((out / "manifest.json").read_text())
    mob = json.loads((out / "manifest_mobile.json").read_text())
    vis = json.loads((out / "visibility.json").read_text())
    lr = json.loads((out / "lowres.json").read_text())
    v5 = {v: json.loads((out / f"verify_gate5_{v}.json").read_text())
          for v in ("desktop", "mobile") if (out / f"verify_gate5_{v}.json").exists()}
    v4 = G.manifest()

    L = []
    a = L.append
    a("# Phase 6b Gate 5 — export hand-off (tiers, groups, mobile)\n")
    a("Generated by `export/gate5_report.py` from `export/out/gate5/*.json`; every number is the one "
      "in the manifests, read back, not a second computation. Branch `phase6b-export`.\n")

    a("## Tier bytes\n")
    a("| variant | tier | files | bytes | MB |")
    a("|---|---|---|---|---|")
    for name, m in (("desktop", man), ("mobile", mob)):
        for k, n, b in tier_table(m):
            a(f"| {name} | {k} | {n} | {b:,} | {b / MB:.1f} |")
        tot = sum(m["tiers"]["bytes"].values())
        a(f"| {name} | **all** | {sum(m['tiers']['files'].values())} | {tot:,} | **{tot / MB:.1f}** |")
    a("")
    a("## The first frame, on the wire\n")
    a("The budget is **transfer bytes as the network log sees them**: `gzip -9` for the types "
      "Cloudflare Pages compresses (html, css, js, json, txt, svg), size on disk for KTX2, glb, wasm, "
      "`.hdr` and `.cube` (Pages serves those as `application/octet-stream` and does not compress "
      "them). gzip, not brotli, so the estimate errs high.\n")
    a("| variant | tier 0 transfer | boot overhead | first frame | budget | verdict |")
    a("|---|---|---|---|---|---|")
    for name, m in (("desktop", man), ("mobile", mob)):
        t = m["tiers"]
        a(f"| {name} | {t['transfer_bytes']['0']:,} | {t['boot_overhead_bytes']['total']:,} | "
          f"**{t['first_frame_transfer_bytes']:,}** | 50,000,000 | "
          f"{'WITHIN' if t['tier0_within_budget'] else 'OVER'} |")
    a("")
    a("`boot_overhead_bytes` is what the browser fetches before frame 1 that is not in `files`:\n")
    a("| item | path | bytes | transfer |")
    a("|---|---|---|---|")
    for k, v in man["tiers"]["boot_overhead_bytes"]["items"].items():
        a(f"| {k} | `{v['path']}` | {v['bytes']:,} | {v['transfer']:,} |")
    a("")
    tr = man["tiers"]["tier0_trim"]
    if tr["moved"]:
        a(f"To fit, **{len(tr['moved'])} Gate 2 placeholder maps ({tr['moved_bytes']:,} transfer "
          f"bytes) moved from tier 0 to tier 1**, least hero-visible first. Their materials' share of "
          f"the hero frame, from `visibility.json`:\n")
        a("| texture | hero fraction of the frame | transfer |")
        a("|---|---|---|")
        for x in tr["moved"][:40]:
            h = -x["hero_order"] if isinstance(x["hero_order"], (int, float)) and x["hero_order"] < 0 \
                else 0.0
            a(f"| `{x['key']}` | {h:.6f} ({h * 100:.4f} %) | {x['transfer']:,} |")
        nq = lr.get("tier0_normals_qlevel") or {}
        n_keys = set((nq.get("files") or {}))
        was = sum(v["bytes"] for k, v in ((lr.get("tier0") or {}).get("files") or {}).items()
                  if k in n_keys)
        now = sum(v["bytes"] for v in (nq.get("files") or {}).values())
        a(f"\nThe largest of them covers "
          f"{max((-x['hero_order'] for x in tr['moved'] if x['hero_order']), default=0) * 100:.4f} % "
          f"of the hero frame, and **all 28 are DROPPED from tier 0, not moved into tier 1** - their "
          f"full-resolution file is already there, so shipping the half-resolution copy as well would "
          f"be {tr['moved_bytes']:,} wasted bytes. Their materials carry no map at all until tier 1: "
          f"the glb's own base colour stands in.\n")
        a(f"Before any of them moved, the cheaper lever was spent: the **{len(n_keys)} tier-0 normal "
          f"maps re-encoded at ETC1S qlevel 32 instead of 128**, measured over the whole shipped set "
          f"in `lowres.json`: **{was:,} -> {now:,} B, -{100 * (1 - now / was):.1f} %** "
          f"({was - now:,} B). The only error measurement for that change is the five-file probe in "
          f"`lowres.json.probe` (qlevel 128 at the same resolution); no A/B was run over all "
          f"{len(n_keys)}, so no error claim is made for the shipped set.\n")
    a("**The probe is in tier 0** (lead's decision, review finding 2). Tier 0 ships no lightmap, so the "
      "six probe faces (6.29 MB) are the only indirect light in the first frame; without them it is "
      "sky-diffuse only, which is darker and flatter than the low-resolution look the user approved, "
      "not merely softer.\n")
    a(f"The same look at Gate 3 was **{sum(p.bytes or 0 for p in G.resolve_files(v4).values()) / MB:.1f} "
      f"MB** over {len(G.resolve_files(v4))} files, with `orn.glb` (154.3 MB) and `env.glb` (38.1 MB) "
      "both over the 25 MiB per-file cap.\n")

    a("## What is in each tier\n")
    for name, m in (("desktop", man), ("mobile", mob)):
        b, n = by_kind(m)
        a(f"**{name}**\n")
        a("| tier | kind | files | MB |")
        a("|---|---|---|---|")
        for k in sorted(b, key=lambda k: (k[0], -b[k])):
            a(f"| {k[0]} | {k[1]} | {n[k]} | {b[k] / MB:.2f} |")
        a("")

    a("## Per-file cap (Cloudflare Pages, 25 MiB)\n")
    for name, m in (("desktop", man), ("mobile", mob)):
        ov = m["tiers"]["oversize"]
        a(f"- {name}: **{len(ov)}** files over the cap"
          + ("." if not ov else ": " + ", ".join(f"`{o['path']}` ({o['bytes']:,} B)" for o in ov)))
    big = sorted(((e["bytes"] or 0, e["path"]) for e in man["files"]), reverse=True)[:5]
    a("- desktop's five biggest published files: "
      + ", ".join(f"`{os.path.basename(p)}` {b / MB:.1f} MB" for b, p in big) + "\n")

    a("## ETC1S: wall time and size per texture class\n")
    a("| block | files | MB | wall s | encoder |")
    a("|---|---|---|---|---|")
    for k, v in lr.items():
        if not isinstance(v, dict) or "files" not in v:
            continue
        tot = sum(f["bytes"] for f in v["files"].values())
        a(f"| {k} | {len(v['files'])} | {tot / MB:.2f} | {v.get('wall_s')} | "
          f"`{v.get('encoder')} /{v.get('resize_div')}` |")
    a("")
    probe = lr.get("probe") or []
    if probe:
        a("The choice the brief left open, measured per map (bytes / RMS against the source png in "
          "linear light, the decoded image brought back to the source resolution):\n")
        a("| map | src px | ETC1S | ETC1S /2 | ETC1S /4 | UASTC /4 |")
        a("|---|---|---|---|---|---|")
        for r in probe:
            if "etc1s" not in r:
                continue
            a(f"| {r['tag']} `{r['key'][-34:]}` | {r['src_px']} | "
              + " | ".join(f"{r[k]['bytes'] / 1e3:.0f} kB / {r[k]['rms']:.4f}"
                           for k in ("etc1s", "etc1s_h2", "etc1s_q4", "uastc_q4")) + " |")
        a("\n**Half-resolution ETC1S wins the brief's test** — smaller AND lower RMS than quarter-res "
          "UASTC on 5 of the 6 sampled maps, and 8-15x smaller on the two normals for +0.0005 RMS — so "
          "that is what tier 0 and the whole mobile set use.\n")

    a("## Mobile resident estimate (ASTC 4x4, 1 byte/texel x 4/3 for mips)\n")
    a("| kind | MB |")
    a("|---|---|")
    for k, v in sorted(mob["tiers"]["resident_estimate_mb"]["by_kind"].items(), key=lambda x: -x[1]):
        a(f"| {k} | {v:.1f} |")
    a(f"| **total** | **{mob['tiers']['resident_estimate_mb']['total']:.0f}** |")
    a(f"\nTarget on the iPhone 16 Pro: **< 700 MB**. Desktop, by the same rule: "
      f"{man['tiers']['resident_estimate_mb']['total']:.0f} MB (manifest v4's own carried figure is "
      f"{v4['budget']['resident_mb']['total']:.0f} MB, so the rule reproduces).\n")

    a("## Hero-visible assets not in tier 0\n")
    t0_assets = set()
    for g in man["glb"]["groups"]:
        if g.get("tier") == 0:
            t0_assets |= set(g["assets"])
    for e in man["files"]:
        if e["tier"] == 0 and e["kind"] == "glb":
            cls = os.path.basename(e["path"]).replace(".glb", "")
            t0_assets |= {n for n, r in v4["assets"].items()
                          if ("ground" if r.get("kind") == "ground" else
                              "arch" if r["cls"] == "ARCH" else
                              "orn" if r["cls"] == "ORN" else "env") == cls}
    hero = {n for n, x in vis["assets"].items() if x["hero"] > 0}
    out_of_t0 = sorted(hero - t0_assets)
    boards = [n for n in out_of_t0 if "treeboard" in n]
    other = [n for n in out_of_t0 if "treeboard" not in n]
    a(f"- {len(hero)} assets are visible from the hero station at the 640x360 ray grid.")
    a(f"- **{len(other)}** of them are not in tier 0"
      + ("." if not other else f": {other[:10]} — these are a defect, not an exception."))
    a(f"- {len(boards)} `ENV_treeboard_*` stand-ins are deliberately not in tier 0: the viewer hides "
      "them by default (`?treeboards=0` since 6a, web/src/main.js) and draws those trees from the "
      "impostor atlases, which ARE in tier 0 at half resolution. Their pixels are covered.\n")

    a("## Verification (`export/verify_glb.py --gate5`)\n")
    a("| variant | assets | files | arch | orn | env | ground | result |")
    a("|---|---|---|---|---|---|---|---|")
    for v, r in v5.items():
        rat = {c: f"{d.get('ratio', '-')}" for c, d in r["per_class"].items()}
        a(f"| {v} | {r['assets_covered']}/{r['assets_expected']} | {r['files']} | "
          f"{rat.get('arch', '-')} | {rat.get('orn', '-')} | {rat.get('env', '-')} | "
          f"{rat.get('ground', '-')} | {'PASS' if not r['fail'] else 'FAIL: ' + '; '.join(r['fail'])} |")
    a("\nThe ratio is triangles DRAWN against `glb.per_class[cls].placed_tris` at Gate 3. Desktop's "
      "0.9981 / 0.9984 on arch and orn are the same degenerate-triangle loss Gate 3 itself reported "
      "(-0.185 % / -0.157 %); env and ground are exact. The mobile ratios are `gltfpack -si 0.5` on "
      "ARCH and ORN, which is the brief's \"decimated LOD0 at half the Gate 1 budget\" - the export set "
      "has no ARCH/ORN LOD1 to ship instead.\n")

    a("## Carried, not fixed (for the next round)\n")
    a("- `../gate1/arch.glb` (15 images) and `../gate1/ground.glb` (4) still EMBED their Gate 1 "
      "stand-in maps in buffer views. They are not groups, so the no-embedded-image assertion skips "
      "them, and those maps can never be tier-upgraded - harmless today because `web/src/pbr.js` "
      "overwrites every one of them from the Gate 2 set, and both files are small (4.6 / 2.0 MB), but "
      "it is the same dead-end the groups were fixed for.")
    a("- `scene.ray_cast` treats alpha-cut leaf cards as opaque, so the tier ordering is conservative "
      "behind foliage: an asset hidden only by a leaf card reads as invisible and lands a tier late.")
    a("- `verify_glb --gate5` compares drawn triangles per class but does not compare instanced-ROW "
      "counts against a Gate 3 figure; the placements column is reported, not asserted.")
    a("- `tiers.py` still prints two hardcoded byte figures for `orn.glb` / `env.glb` in the `glb.note` "
      "text (154 253 424 / 38 119 568) that differ from `per_class_gate3` (154 065 360 / 35 797 240): "
      "the note quotes the files on disk, the block quotes what manifest v4 recorded at Gate 1.")
    a("- `gate5_tex.py --mobile` no longer writes a second texture set; it now says so and exits.")
    a("- `lowres.json` `wall_s` is this run's seconds; `wall_s_cumulative` is the running total.\n")

    a("## Viewer contract — what changed in v5 (breaking, on purpose)\n")
    a("- **`glb.per_class` is gone**, replaced by `glb.groups` (a list with `path`, `cls`, `tier`, "
      "`nodes`, `assets`, `hero_fraction`, `station_visibility`, `textures`, `placeholder`). The Gate 3 "
      "figures are kept as `glb.per_class_gate3` for reference only: `orn.glb` (154.3 MB) and `env.glb` "
      "(38.1 MB) are NOT published, because both are over the 25 MiB per-file cap. A viewer that still "
      "reads `per_class` will 404 rather than quietly download 192 MB of files that are not on the host.")
    a("- **`files`** is the load plan: an array already in (tier, hero coverage, path) order, each entry "
      "`{path, tier, kind, why, bytes, key, px}`. `tiers.bytes` is the loading-screen denominator.")
    a("- **`tiers.lowres.files[key]`** gives the tier-0 half-resolution variant of a texture key; the "
      "viewer uses it in tier 0 and re-loads the manifest's own full-resolution path when tier 1 lands.")
    a("- A group with **`placeholder: true`** is tier 0 and is replaced by the tier-1 group of the same "
      "class; its assets are asserted to be a subset of that group's.")
    a("- **`?tier=mobile`** selects `manifest_mobile.json`, which carries the same blocks. Its "
      "`lowres.files` entries have **no `full`**: the mobile set publishes only the half-resolution "
      "copy, so its redirect is permanent and there is nothing to upgrade to.")
    a(f"- **{len(man['tiers']['tier0_trim']['moved'])} keys listed in `tiers.tier0_trim` have NO "
      "tier-0 map** - no entry in `tiers.lowres.files` either - and their materials show the glb's own "
      "base colour until their full-resolution file arrives in tier 1. \"0 hero-visible assets outside "
      "tier 0\" is about GEOMETRY; these 28 maps are the texture exception, each under 0.003 % of the "
      "hero frame.")
    a("- **There are no placeholder groups any more.** Every instance of a prototype is in ONE group, "
      "so the hero draws the Gate 3 node set exactly; what tier 1 upgrades is the TEXTURE. For a key "
      "in `tiers.lowres.files`, `path` is the half-resolution file the group or the material already "
      "has and `full` is the full-resolution file to re-load into the same slot - including the ORN "
      "occlusion maps, which arrive inside the glb at half resolution and are named by each set's "
      "`occlusion.gate1_texture`.")
    a("- **`uv2_relay_status.json` is published beside the manifest** (tier 0) and named at "
      "`lightmaps.uv2_relay_status.path`; main.js already resolves it against the manifest URL.")
    a("- **`lightmaps.instance_irradiance.groups`** replaces the env.glb-keyed `nodes` (see above).")
    a("- **`files[*].transfer`** is the gzip-estimated wire size; `tiers.transfer_bytes` and "
      "`tiers.first_frame_transfer_bytes` are what the loading screen should count against.")
    a("- The four v4 paths that were relative to `out/gate3` are rebased to `../gate3/...`; what moved "
      "is listed in `tiers.path_rebase`.\n")
    a("## The deploy set — every directory the publish must carry\n")
    a("`files` spans four gates, not just gate5: the LUT and the sky are gate0, the glb-external maps "
      "and the lazy foliage glbs are gate1, the Gate 2 PBR and detail sets are gate2, the lightmaps, "
      "impostors, probe and foliage cards are gate3. **A deploy that publishes only `out/gate5` 404s on "
      "every `../gate0/...` path.**\n")
    a("| directory | files | bytes | transfer |")
    a("|---|---|---|---|")
    import collections as _c
    dirs_b, dirs_n, dirs_t = _c.Counter(), _c.Counter(), _c.Counter()
    for e in man["files"]:
        d = e["path"].split("/")[0]
        d = "gate5" if d not in ("..",) else e["path"].split("/")[1]
        dirs_b[d] += e["bytes"] or 0
        dirs_t[d] += e.get("transfer") or 0
        dirs_n[d] += 1
    for d in sorted(dirs_b, key=lambda d: -dirs_b[d]):
        a(f"| `export/out/{d}` | {dirs_n[d]} | {dirs_b[d]:,} | {dirs_t[d]:,} |")
    a(f"| **all** | {sum(dirs_n.values())} | **{sum(dirs_b.values()):,}** | "
      f"{sum(dirs_t.values()):,} |")
    a("\nThe mobile set is a subset of the same directories. `web/deploy.sh` should build the publish "
      "directory FROM `files` (copy each path, keeping it relative to `out/gate5`), not by copying "
      "`out/` wholesale: `out/` also holds ~2 GB of bake sources, the `rgbm8` lightmap twins and the "
      "unpublished `orn.glb` / `env.glb`, none of which are in the plan.\n")

    a("## Shrub and reed irradiance after the split\n")
    ii = man["lightmaps"]["instance_irradiance"]
    a(f"- `lightmaps.instance_irradiance.groups` re-keys the block to the per-tier ENV groups: "
      f"{ii.get('groups_placements')} of {ii.get('placements')} placements, "
      f"{'complete' if ii.get('groups_complete') else 'INCOMPLETE'}.")
    a("- **How the viewer joins it:** for each group id in `groups`, bind under "
      "`WEB_glb_<group id>` by `mesh.userData.pfaGltfNode`, exactly as `applyInstanceIrradiance` does "
      "today, passing that group's scene as `opts.root` and `groups[id].nodes` as `opts.block.nodes`. "
      "`segments` has the same `[mesh, count, offset]` meaning; `meshes[*].rgb` is unchanged.")
    ig = json.loads((out / "instance_order_groups.json").read_text())
    a(f"- The join is the bake's own key, the instance translation: rows decoded from the packed group "
      f"with `web/tools/instance_rows.mjs`, brought back to Blender space, matched to the nearest "
      f"placement within {ig['tolerance_m']} m with the runner-up at least {ig['margin']}x further; a "
      f"placement claimed twice is a hard failure.")
    if ig.get("unmatched"):
        a(f"- **{len(ig['unmatched'])} placements are unmatched** and fall back to the probe: "
          + ", ".join(f"`{u['object']}`" for u in ig["unmatched"])
          + ". These are the three `.001` near-duplicate cards the manifest's own `lod1` block already "
            "reports as `not_in_lod1: 3`.")
    a("")

    a("## Files in MAIN\n")
    for name, m in (("desktop", man), ("mobile", mob)):
        miss = present_in_main(m)
        a(f"- {name}: {len(m['files'])} published files, **{len(miss)} missing** from "
          f"`{G.PUB_BASE}`" + ("." if not miss else f": {miss[:5]}"))
    a("")

    p = G.MAIN / "docs/briefs/phase6b_export_report.md"
    local = Path(__file__).resolve().parents[1] / "docs/briefs/phase6b_export_report.md"
    local.parent.mkdir(parents=True, exist_ok=True)
    local.write_text("\n".join(L) + "\n")
    print(f"[gate5report] wrote {local} ({local.stat().st_size} B)")


if __name__ == "__main__":
    main()
