"""Architecture round 6 composite: the hero-facing stack before / after / ref 169, with the course table burnt in.

    python3 scripts/arch_r6_sheet.py

Inputs, all already in the 1920x1080 cam01 pixel grid:
  before : panel 0 of renders/qa_comparisons/round06_cam01_aligned_vs_ref169.png (QA's round-06 Cycles hero)
  ref    : panel 1 of the same sheet (ref 169 warped into the render frame by qa_silhouette align, REF169_XF)
  after  : renders/previews/architecture/arch_r6_cam01_stack.png (this round's Cycles 64 spp border render)
Outputs:
  renders/qa_comparisons/arch_r6_aligned_vs_ref169.png   3 panels (after | ref | blend) -- the file qa_stack_offset
                                                         re-runs on, so QA's own tool measures this round's rows.
                                                         INTERMEDIATE, regenerated by this script, not committed.
  renders/qa_comparisons/arch_r6_sheet.png               the composite for the report

The burnt-in table is READ FROM THE LOGS, not transcribed (r6 review finding 5): the model row of each course comes
from `renders/logs/arch_r6_courses.log` (`arch_entab_probe --courses`), and the rendered / photographed rows are the
edges `renders/logs/arch_r6b_stack_offset.log` found in the same x 880-1040 band (`qa_stack_offset.py`), so the sheet
can disagree with the report. Pairing rule, stated so it can be checked: for each course take the nearest RENDER edge
with |dL/dy| >= 2 within 6 rows of the model row, then the nearest REF edge with |dL/dy| >= 6 within 6 rows of that.
"""
import re
import sys
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
QA = ROOT / "renders" / "qa_comparisons"
BEFORE_SHEET = QA / "round06_cam01_aligned_vs_ref169.png"
AFTER = ROOT / "renders" / "previews" / "architecture" / "arch_r6_cam01_stack.png"
FONT = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
X0, X1, Y0, Y1 = 830, 1100, 140, 380          # the band the round-6 work moves (measurement band is x 880-1040)
SCALE = 1.55

# ---- the course table, parsed from the two committed logs (r6 review finding 5)
LOGS = ROOT / "renders" / "logs"
COURSES_LOG = LOGS / "arch_r6_courses.log"
OFFSET_LOG = LOGS / "arch_r6b_stack_offset.log"
# which courses of the log to show, and the short label for the 470 px table column. The first row is the CROWN at
# z 38.30 (model row 161.2); the old sheet called row 168 "attic crown", which this round's own argument rejects.
SHOW = [("attic top (cornice crown)", "attic crown (z 38.30)"),
        ("attic cornice corona soffit", "attic cornice corona soffit"),
        ("attic relief field top", "attic relief field top"),
        ("attic relief field bottom", "attic relief field bottom"),
        ("cornice corona bottom (soffit lip)", "entablature corona soffit"),
        ("frieze top", "frieze top"),
        ("architrave bottom", "architrave bottom"),
        ("capital top (pier, az 64.9)", "capital top (pier az 64.9)")]


def parse_courses(path):
    """label -> model row, from the `course  z  d  row  col` block of arch_entab_probe --courses."""
    out = {}
    for line in path.read_text().splitlines():
        m = re.match(r"^(\S.*?)\s\s+(-?\d+\.\d+)\s+(-?\d+\.\d+)\s+(\d+\.\d+)\s+(\d+\.\d+)", line)
        if m:
            out[m.group(1).strip()] = float(m.group(4))
    return out


def parse_edges(txt, which):
    """[(row, dL/dy)] from a `render edges (25): 157(+9.8), ...` line of qa_stack_offset."""
    m = re.search(rf"^{which}\s+edges \(\d+\): (.*)$", txt, re.M)
    return [(int(r), float(g)) for r, g in re.findall(r"(\d+)\(([-+][\d.]+)\)", m.group(1))] if m else []


def nearest(edges, row, min_g, tol):
    cand = [(abs(r - row), r) for r, g in edges if abs(g) >= min_g and abs(r - row) <= tol]
    return min(cand)[1] if cand else None


COURSES = parse_courses(COURSES_LOG)
_off = OFFSET_LOG.read_text()
R_EDGES, F_EDGES = parse_edges(_off, "render"), parse_edges(_off, "ref")
TABLE = []
for key, label in SHOW:
    z = COURSES[key]
    r = nearest(R_EDGES, z, 2.0, 6)
    f = nearest(F_EDGES, r, 6.0, 6) if r is not None else None
    d = f"{r - f:+d}" if (r is not None and f is not None) else "-"
    TABLE.append((label, f"{z:.1f}", "-" if r is None else str(r), "-" if f is None else str(f), d))

im = Image.open(BEFORE_SHEET).convert("RGB")
W, H = im.width // 3, im.height
before = im.crop((0, 0, W, H))
ref = im.crop((W, 0, 2 * W, H))
after = Image.open(AFTER).convert("RGB")
assert after.size == (W, H), f"{after.size} != {(W, H)}"

# ---- 3-panel aligned sheet in QA's own layout, so scripts/qa_stack_offset.py measures this round unchanged
blend = Image.fromarray((0.5 * np.asarray(after).astype(float) + 0.5 * np.asarray(ref).astype(float)).astype("uint8"))
sheet = Image.new("RGB", (3 * W, H))
for i, p in enumerate((after, ref, blend)):
    sheet.paste(p, (i * W, 0))
sheet.save(QA / "arch_r6_aligned_vs_ref169.png")

# ---- the composite for the report
f_lab = ImageFont.truetype(FONT, 17)
f_tab = ImageFont.truetype(FONT, 15)
panels = []
for img, name in ((before, "BEFORE  round 06"), (after, "AFTER  round 06 -> r6"), (ref, "REF 169  (aligned)")):
    c = img.crop((X0, Y0, X1, Y1)).resize((int((X1 - X0) * SCALE), int((Y1 - Y0) * SCALE)), Image.LANCZOS)
    d = ImageDraw.Draw(c)
    for y in range(Y0, Y1, 10):
        yy = (y - Y0) * SCALE
        d.line([(0, yy), (16 if y % 20 == 0 else 8, yy)], fill=(255, 40, 40))
        if y % 20 == 0:
            d.text((18, yy - 7), str(y), font=f_tab, fill=(255, 70, 70))
    d.rectangle([0, 0, c.width - 1, 24], fill=(0, 0, 0))
    d.text((6, 4), name, font=f_lab, fill=(255, 235, 90))
    panels.append(c)

gap, pad = 10, 12
tw = 470
out = Image.new("RGB", (sum(p.width for p in panels) + 2 * gap + tw + 3 * pad, panels[0].height + 2 * pad), (18, 18, 20))
d = ImageDraw.Draw(out)
x = pad
for p in panels:
    out.paste(p, (x, pad))
    x += p.width + gap
x += pad
d.text((x, pad + 2), "course row on cam01 (1920x1080), read from the logs", font=f_lab, fill=(255, 235, 90))
d.text((x, pad + 26), f"{'course':27s}{'model':>7s}{'render':>7s}{'ref169':>7s}{'d':>5s}", font=f_tab, fill=(180, 200, 255))
for i, (lab, z, r, f, dd) in enumerate(TABLE):
    d.text((x, pad + 46 + i * 19), f"{lab:27s}{z:>7s}{r:>7s}{f:>7s}{dd:>5s}", font=f_tab, fill=(235, 235, 235))
y = pad + 46 + len(TABLE) * 19 + 12
for line in ["model = arch_r6_courses.log; render / ref169 =",
             "qa_stack_offset edges, arch_r6b_stack_offset.log.",
             "13.42 px/m at the wall plane; 1 m of outward",
             "projection lifts a point 5.16 px.",
             "",
             "envelope HELD: --sil apex 87.5 corner_top 212.0",
             "W_a 544 px rise/W_a 0.2288 (round 4 alpha render",
             "88 / 212 / 544 / 0.228) -> 0.0-0.6 % on all four.",
             "",
             "tris LOD0 2,694,686 LOD1 1,109,390 (+0.01 %).",
             "UVProj re-baked by the build: 26,376 verts,",
             "0 clamped, round-trip 0.00 px, 3/3 named points."]:
    d.text((x, y), line, font=f_tab, fill=(200, 200, 200))
    y += 19
out.save(QA / "arch_r6_sheet.png")
print(f"[arch_r6_sheet] wrote {QA / 'arch_r6_aligned_vs_ref169.png'} and {QA / 'arch_r6_sheet.png'} {out.size}")
