"""ORN round 7/8, brief item 1 — re-lay the Corinthian proportions of the 3.0 m rotunda capital, and check it.

Pure Python (NO bpy): `orn_build.bell_radius`, `orn_build.leaf_spine` and `orn_build.apply_capital_style` are
PARSED OUT OF the builder and exec'd here (round 8; they used to be hand copies), so the vertical extent / radial
projection / width of an acanthus row can be solved for a TARGET tier height instead of being read off after a
20-minute mesh build, and so a formula edit in the builder moves these numbers instead of passing --verify.

    python3 scripts/orn_r7_capital_layout.py            # before / after / reference table
    python3 scripts/orn_r7_capital_layout.py --solve    # also print the solved preset numbers
    python3 scripts/orn_r7_capital_layout.py --verify   # gate: every preset x every CAPITAL_STYLE variant
                                                        # against the ref_002 window; exit 1 on any FAIL

Why: the r6 review (docs/reviews/orn_r6_review.md finding 2) showed the 3.0 m capital is the 2.6 m design
stretched in Z only. Everything keyed to H grew 15.4 %; everything keyed to R (leaf width, `proud`, thickness)
did not — so the acanthus tiers ended up 15 % longer at the same width and the same radial projection.

Reference (ref_002_rotunda_Corinthian_Order_Capital.jpg, the frontal pier capital; face-centre column x~490 of
940, capital base = astragal top y 785, abacus top y 385, so H = 400 px, 133 px/m at H = 3.0 m). The 940-px view
the pixel frame refers to is committed as reference/photos/ornament_crops/orn_r8_ref002_capital_940.jpg and is
regenerated by scripts/orn_r8_ref002_crop.py, so the reading below can be re-measured:

    abacus                     y 385-430    0.113 H   (canon 1/7 = 0.143 of the part above the leaves; ~0.10 H here)
    volute + caulicoli zone    y 440-620    top 0.35 H (volute eyes y ~500-505 = 0.71 H, spirals span 0.56-0.81 H)
    upper acanthus row         y 600-700    0.25 H projected; 0.30 H corrected for the up-view foreshortening
    lower acanthus row         y 700-790    0.21 H projected; 0.30 H corrected
    upper leaf width (front)   130 px       0.33 H, i.e. width ~1.08 x the row's own vertical extent

The up-view compresses the upper part of the capital more than the lower, so the two leaf rows are read as EQUAL
(0.30 H each) per the Vignola canon rather than the raw 0.25 / 0.21 px numbers; the abacus and the volute band,
which are measured across a short depth, are taken at face value.
"""
import math, pathlib, sys

TAU = math.tau
SRC = pathlib.Path(__file__).resolve().parent / "orn_build.py"

# ------------------------------------------------------------- everything below is READ OUT OF orn_build.py
# Round 8 (r7 review finding 1): there are no hand copies left in this file. `bell_radius`, `leaf_spine` and
# `apply_capital_style` are parsed out of the builder and exec'd, and so are ARCH_R6, BELL_PROFILE,
# CAPITAL_PRESETS and CAPITAL_STYLE — so a formula edit or an ARCH course change in the builder moves these
# numbers instead of passing --verify in silence against a stale copy.


def _bracket_slice(src, head):
    """The source text of a `NAME = <opener> ... <closer>` statement, brackets balanced."""
    i = src.index(head)
    depth, j = 0, i + len(head) - 1
    while True:
        if src[j] in "[{(":
            depth += 1
        elif src[j] in "]})":
            depth -= 1
            if depth == 0:
                break
        j += 1
    return src[i:j + 1]


def _def_slice(src, name):
    """The source text of a top-level `def name(...)`, up to the next line that starts in column 0."""
    i = src.index("\ndef %s(" % name) + 1
    lines = src[i:].split("\n")
    out = [lines[0]]
    for ln in lines[1:]:
        if ln and not ln[0].isspace():
            break
        out.append(ln)
    return "\n".join(out)


def source_ns():
    src = SRC.read_text()
    ns = {"math": math}
    for head in ("ARCH_R6 = dict(", "BELL_PROFILE = [", "CAPITAL_PRESETS = {", "CAPITAL_STYLE = {"):
        exec(_bracket_slice(src, head), ns)
    for fn in ("bell_radius", "leaf_spine", "apply_capital_style"):
        exec(_def_slice(src, fn), ns)
    return ns


_NS = source_ns()
ARCH_R6 = _NS["ARCH_R6"]
BELL_PROFILE = _NS["BELL_PROFILE"]
CAPITAL_PRESETS = _NS["CAPITAL_PRESETS"]
CAPITAL_STYLE = _NS["CAPITAL_STYLE"]
bell_radius = _NS["bell_radius"]
leaf_spine = _NS["leaf_spine"]
apply_capital_style = _NS["apply_capital_style"]


# --------------------------------------------------------------------------------------- row measurement
def row_metrics(P, row, base_zH, length_H, width_scale, count=8):
    """Vertical extent, tip height, radial projection and width of ONE acanthus row, in metres and in H.
    `tilt` is the outward lean applied by build_leaf_ring (place(..., tilt_x_deg=-leaf_tilt)); it rotates the
    leaf-local (y, z) frame about local X, so it trades height for projection."""
    R, H = P["R"], P["H"]
    base_z = base_zH * H
    r0 = bell_radius(P, base_z)
    length = length_H * H
    proud = P["proud"][row] * H                   # r7 onward `proud` is a fraction of H in every preset
    sp = leaf_spine(P, base_z, length, proud=proud, arc_deg=P["arc_deg"][row], arc_frac=P["arc_frac"][row])
    a = math.radians(-P["leaf_tilt"][row])        # tilt_x_deg, negative = lean outward
    # place(): rotation about local X by a, applied to (y, z) as y' = y cos a - z sin a, z' = y sin a + z cos a
    pts = [(y * math.cos(a) - z * math.sin(a), y * math.sin(a) + z * math.cos(a)) for (y, z) in sp]
    zs = [p[1] for p in pts]
    ys = [p[0] for p in pts]
    extent = max(zs)                              # highest point of the spine above the row base
    tip_z = zs[-1]                                # the curled-down tip
    proj = max(ys)                                # radial projection beyond the bell at the base
    r_tip = r0 * 0.965 + proj
    width = (TAU * r0) / count * width_scale
    return dict(proud=proud, base_zH=base_zH, base_z=base_z, r0=r0, length=length, extent=extent, extent_H=extent / H,
                top_zH=base_zH + extent / H, tip_zH=base_zH + tip_z / H, proj=proj, proj_H=proj / H,
                r_tip=r_tip, width=width, aspect=width / extent)


def solve_length_H(P, row, base_zH, target_extent_H, lo=0.10, hi=0.90):
    """Spine length (in H) whose tilted vertical extent equals target_extent_H."""
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        e = row_metrics(P, row, base_zH, mid, 1.0)["extent_H"]
        if e < target_extent_H:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def solve_width_scale(P, row, base_zH, extent_H, target_aspect, count=8):
    """width_scale (multiple of the leaf pitch) giving width = target_aspect x the row's vertical extent."""
    r0 = bell_radius(P, base_zH * P["H"])
    pitch = (TAU * r0) / count
    return target_aspect * extent_H * P["H"] / pitch


# ------------------------------------------------------- the pre-r7 preset, FROZEN as a historical record
# This is what CAPITAL_PRESETS["capital_rotunda"] held before the round-7 re-lay; it is deliberately NOT read
# from orn_build.py (it no longer exists there) and must not be updated when the live preset moves. `proud` was
# keyed to R then and to H now, so it is restated in H here at the two H values, which is the same millimetres.
_PROUD_R = (0.140, 0.130)                                     # pre-r7, in units of R (R = 1.05 m)


def _proud_H(H, R=1.05):
    return tuple(p * R / H for p in _PROUD_R)


BEFORE = dict(H=3.0, R=1.05, abacus_across=3.0, lower_len=0.44, upper_len=0.37, lower_w=1.26, upper_w=1.30,
              lower_z=0.060, upper_z=0.440, proud=_proud_H(3.0), arc_deg=(100.0, 90.0), arc_frac=(0.28, 0.26),
              leaf_tilt=(3.0, 4.0), volute_z=0.805, helix_z=0.775, volute_r=0.112, helix_r=0.055,
              abacus_z0=0.890)
BEFORE_26 = dict(BEFORE, H=2.6, proud=_proud_H(2.6))   # as laid out, for the "what did the stretch do" column

# ---- reference targets, from the ref_002 reading in the docstring (fractions of H)
REF = dict(lower_base=0.030, lower_extent=0.300, upper_base=0.300, upper_extent=0.300,
           volute_zone_bottom=0.650, abacus_h=0.100, upper_aspect=1.08, lower_aspect=1.02,
           # Body projection: in ref_002 the leaf stands clear of the kalathos down its WHOLE length (the slot
           # either side is in shadow from the tip to the base), not only at the curled tip. Read as ~0.20 of the
           # row's own vertical extent -> proud = 0.20 x 0.300 H = 0.060 H (lower). Round 8: the upper row is
           # held to 0.049 H (0.163 of its extent) because at 0.052 H its tips reached 1.408 R, just outside the
           # r_tip window below - the window is now checked, not asserted.
           lower_proud=0.060, upper_proud=0.049,
           # Tip radius: the tips clear the abacus concave side face (half-side = across/(2 sqrt2) = 1.01 R) and
           # stop short of the corner (across/2 = 1.43 R) -> r_tip 1.30-1.40 R.
           r_tip_R=(1.30, 1.40))

# Tolerances the check is held to (round 8). Variant 1 IS the solved lay-out, so it is held to the solver's own
# precision; variants 2 and 3 exist to differ in silhouette at hero distance (QA-01-18), so their tiers get a
# stated 0.015 H = 45 mm window instead of a pass because nobody looked.
TIER_TOL = 0.004            # H, variant 1
TIER_TOL_STYLE = 0.015      # H, variants 2-3
ABACUS_TOL = 0.002          # H
VOLUTE_MARGIN = 0.005       # H (15 mm) of clear stone wanted between the spiral top and the abacus seat


def verify():
    print("-- orn_build.py as committed, every CAPITAL_STYLE variant " + "-" * 49)
    print("   ARCH_R6 read from the builder: %s" % ARCH_R6)
    print("%-19s %-2s %-6s %7s %7s %7s %7s %7s %7s %6s %8s" % (
        "preset", "v", "row", "base/H", "len(m)", "ext(m)", "ext/H", "top/H", "proj(m)", "w/ext", "r_tip/R"))
    bad = 0
    for name, P0 in CAPITAL_PRESETS.items():
        rot = name == "capital_rotunda"
        for variant in sorted(CAPITAL_STYLE):
            P = apply_capital_style(P0, variant)
            tol = TIER_TOL if variant == 1 else TIER_TOL_STYLE
            up_top = None
            for row, key in ((0, "lower"), (1, "upper")):
                m = row_metrics(P, row, P[key + "_z"], P[key + "_len"], P[key + "_w"])
                if row == 1:
                    up_top = m["top_zH"]
                print("%-19s %-2d %-6s %7.3f %7.3f %7.3f %7.3f %7.3f %7.3f %6.2f %8.3f" % (
                    name, variant, key, m["base_zH"], m["length"], m["extent"], m["extent_H"], m["top_zH"],
                    m["proj"], m["aspect"], m["r_tip"] / P["R"]))
                if not rot:
                    continue
                tgt = REF[key + "_extent"]
                if abs(m["extent_H"] - tgt) > tol:
                    print("   FAIL %s v%d %s extent %.4f H, target %.3f +-%.3f H"
                          % (name, variant, key, m["extent_H"], tgt, tol))
                    bad += 1
                lo, hi = REF["r_tip_R"]
                if not lo - 1e-9 <= m["r_tip"] / P["R"] <= hi + 1e-9:
                    print("   FAIL %s v%d %s leaf tips reach %.3f R, ref window %.2f-%.2f R"
                          % (name, variant, key, m["r_tip"] / P["R"], lo, hi))
                    bad += 1
            z0 = P.get("abacus_z0", 0.890)
            vt, vb = P["volute_z"] + P["volute_r"], P["volute_z"] - P["volute_r"]
            print("%-19s %-2d abacus %.3f-1.000 H = %.3f H   volute spiral %.3f-%.3f H   helix %.3f-%.3f H" % (
                name, variant, z0, 1.0 - z0, vb, vt, P["helix_z"] - P["helix_r"], P["helix_z"] + P["helix_r"]))
            if not rot:
                # The 1.8 m capitals were never re-laid; their spiral has buried its top ~0.03 H in the abacus
                # since round 4 and 122 instances are not worth moving without a GPU to look at them.
                if vt > z0 + 1e-6:
                    print("   carried (not re-laid) %s v%d volute top %.3f H above the abacus seat %.3f H"
                          % (name, variant, vt, z0))
                continue
            if vt > z0 - VOLUTE_MARGIN:
                print("   FAIL %s v%d volute top %.3f H, abacus seat %.3f H, wanted %.3f H of clearance"
                      % (name, variant, vt, z0, VOLUTE_MARGIN))
                bad += 1
            if abs((1.0 - z0) - REF["abacus_h"]) > ABACUS_TOL:
                print("   FAIL %s v%d abacus %.3f H, target %.3f H" % (name, variant, 1.0 - z0, REF["abacus_h"]))
                bad += 1
            if vb < REF["volute_zone_bottom"] - 0.02:
                print("   FAIL %s v%d volute spiral starts at %.3f H, below the top-0.35 H band"
                      % (name, variant, vb))
                bad += 1
            if up_top > vb:
                print("   FAIL %s v%d upper leaf top %.3f H overlaps the volute spiral at %.3f H"
                      % (name, variant, up_top, vb))
                bad += 1
    print("VERIFY %s" % ("FAILED (%d)" % bad if bad else "OK"))
    return bad


def main():
    P = dict(BEFORE, proud=(REF["lower_proud"], REF["upper_proud"]))
    print("=" * 108)
    print("ORN r7 item 1 - capital_rotunda proportion re-lay   H = %.2f m, R = %.2f m" % (P["H"], P["R"]))
    print("=" * 108)
    rows = []
    for tag, preset in (("as laid out at H 2.6", BEFORE_26), ("r6 (Z-stretch to 3.0)", BEFORE)):
        for row, key in ((0, "lower"), (1, "upper")):
            m = row_metrics(preset, row, preset[key + "_z"], preset[key + "_len"], preset[key + "_w"])
            rows.append((tag, key, m, preset["H"]))
    hdr = "%-22s %-6s %7s %7s %7s %7s %7s %7s %7s %7s" % (
        "state", "row", "base/H", "len(m)", "ext(m)", "ext/H", "top/H", "proj(m)", "width", "w/ext")
    print(hdr)
    for tag, key, m, H in rows:
        print("%-22s %-6s %7.3f %7.3f %7.3f %7.3f %7.3f %7.3f %7.3f %7.2f" % (
            tag, key, m["base_zH"], m["length"], m["extent"], m["extent_H"], m["top_zH"], m["proj"],
            m["width"], m["aspect"]))

    # ------------------------------------------------------------------ solve the r7 lay-out
    print()
    print("-- solved r7 lay-out against the ref_002 reading " + "-" * 58)
    out = {}
    for row, key in ((0, "lower"), (1, "upper")):
        base = REF[key + "_base"]
        ext = REF[key + "_extent"]
        ln = solve_length_H(P, row, base, ext)
        m0 = row_metrics(P, row, base, ln, 1.0)
        ws = solve_width_scale(P, row, base, m0["extent_H"], REF[key + "_aspect"])
        m = row_metrics(P, row, base, ln, ws)
        out[key] = (base, ln, ws, m)
        print("%-22s %-6s %7.3f %7.3f %7.3f %7.3f %7.3f %7.3f %7.3f %7.2f  r_tip %.3f = %.3f R" % (
            "r7 re-lay", key, m["base_zH"], m["length"], m["extent"], m["extent_H"], m["top_zH"], m["proj"],
            m["width"], m["aspect"], m["r_tip"], m["r_tip"] / P["R"]))
    print()
    print("reference (ref_002)    lower  base 0.030  ext/H 0.300  top/H 0.330   width/ext 1.02   r_tip 1.30-1.40 R")
    print("                       upper  base 0.300  ext/H 0.300  top/H 0.600   width/ext 1.08   r_tip 1.30-1.40 R")
    print("                       volutes+caulicoli in the top 0.35 H (0.650-1.000); abacus 0.100 H (0.900-1.000)")

    if "--solve" in sys.argv:
        print()
        print("-- preset numbers to paste into orn_build.CAPITAL_PRESETS['capital_rotunda'] " + "-" * 30)
        for key in ("lower", "upper"):
            base, ln, ws, m = out[key]
            print("    %s_z=%.3f, %s_len=%.3f, %s_w=%.3f,   proud %.3f H = %.3f m  # ext %.3f m = %.3f H, top %.3f H, w/ext %.2f" % (
                key, base, key, ln, key, ws, REF[key + "_proud"], m["proud"], m["extent"], m["extent_H"],
                m["top_zH"], m["aspect"]))


if __name__ == "__main__":
    if "--verify" in sys.argv:
        sys.exit(1 if verify() else 0)
    main()
