// Normalises export/out/<gate>/manifest.json (written by the bake engineer) into what the viewer needs,
// so a schema change there is absorbed in one place.  Every field that had to be defaulted is reported
// in `notes` and logged, because a silently defaulted exposure or sun vector makes parity meaningless.
import stationsFallback from './stations_blender.json';

// Generated by web/tools/dump_stations.py from scripts/common.py + scripts/qa_cameras.py (review carry
// 10): nothing here is hand-copied.  The manifest still wins over all of it at run time.
export const WATER_Z = stationsFallback.water_z;

function pick( obj, ...keys ) {
	for ( const k of keys ) {
		const v = k.split( '.' ).reduce( ( o, p ) => ( o == null ? o : o[ p ] ), obj );
		if ( v !== undefined && v !== null ) return v;
	}
	return undefined;
}

export function resolveUrl( base, url ) {
	if ( ! url ) return null;
	if ( /^(https?:)?\//.test( url ) ) return url;
	return new URL( url, base ).href;
}

/**
 * @param {object|null} raw  parsed manifest.json (null -> pure defaults, test-scene mode)
 * @param {string} baseUrl   absolute URL of the manifest, for relative asset paths
 */
export function normaliseManifest( raw, baseUrl ) {
	const notes = [];
	const def = ( value, fallback, what ) => {
		if ( value === undefined || value === null ) { notes.push( `defaulted ${what} = ${JSON.stringify( fallback )}` ); return fallback; }
		return value;
	};
	raw = raw || {};

	// --- geometry ------------------------------------------------------------------------------
	// schema pfa-phase6/2 ships ONE GLB PER CLASS (arch / orn / env / ground) loaded in the manifest's
	// order; pfa-phase6-gate0/1 shipped a single `glb`.  Both normalise to `glbs`, an ordered list of
	// { url, name, cls, bytes }.  `glb` stays as the first entry for anything that still reads it.
	const glbRaw = pick( raw, 'glb', 'files.glb', 'model' );
	const glbUrlOf = ( v ) => resolveUrl( baseUrl, typeof v === 'string' ? v : ( v?.path || v?.url || v?.file ) );
	const isGlbUrl = ( u ) => !! u && /\.(glb|gltf)(\?.*)?$/i.test( u );
	const glbEntry = ( v, key, i ) => {
		const url = glbUrlOf( v );
		if ( ! isGlbUrl( url ) ) return null;          // 'texture_source: ktx2' and prose notes are not files
		const o = ( typeof v === 'object' && v ) || {};
		return {
			url,
			name: url.split( '/' ).pop(),
			cls: o.class ?? o.cls ?? o.kind ?? key ?? `part_${i}`,
			bytes: o.bytes ?? o.size ?? o.byte_length ?? null,
			order: o.order ?? i,
		};
	};
	const listOf = ( v ) => {
		if ( ! v ) return [];
		if ( Array.isArray( v ) ) return v.map( ( e, i ) => glbEntry( e, null, i ) );
		if ( typeof v === 'object' ) {
			// A single glb object ({path, bytes, instanced_variant, ...}) is ONE file, not a map of
			// files: its sibling keys are metadata (gate0's `texture_source`, `instanced_variant`).
			if ( v.path || v.url || v.file ) return [ glbEntry( v, v.class ?? v.cls ?? null, 0 ) ];
			return Object.entries( v ).map( ( [ k, e ], i ) => glbEntry( e, k, i ) );
		}
		return [ glbEntry( v, null, 0 ) ];
	};
	// 'glb.per_class' is what export/gltf_pack.sh --gate1 actually writes:
	// glb.per_class = { arch:{path,bytes,…}, orn, env, ground } in load order.
	let glbs = listOf( pick( raw, 'glbs', 'glb.per_class', 'glb.parts', 'glb.files', 'glb.classes', 'files.glbs' ) ).filter( Boolean );
	if ( ! glbs.length ) glbs = listOf( glbRaw ).filter( Boolean );
	glbs.sort( ( a, b ) => a.order - b.order );
	glbs.forEach( ( g, i ) => { g.order = i; } );
	const glb = glbs.length ? glbs[ 0 ].url : null;
	if ( glbs.length > 1 ) notes.push( `${glbs.length} glbs, loaded in manifest order: ${glbs.map( g => `${g.cls}:${g.name}` ).join( ', ' )}` );

	// --- stations ------------------------------------------------------------------------------
	// schema pfa-phase6-gate0/1 keys stations by camera name with lens_mm / rotation_euler_xyz;
	// older/array shapes are accepted too.  Look-at targets are not in the manifest, so they are
	// taken from scripts/qa_cameras.py (stations_blender.json) by name purely as a cross-check.
	let rawStations = pick( raw, 'stations', 'cameras' );
	let stationList;
	const byName = new Map( stationsFallback.stations.map( s => [ s.name, s ] ) );
	// Keys 1-6 are the six scripts/qa_cameras.py stations BY NAME.  manifest v2 also carries cameras
	// that are not QA stations (CAM_flythrough), so key order must never decide the index: a camera
	// the generated list does not know is appended after 6, never inserted in front of the hero.
	const indexFor = ( s, i ) => s.index ?? byName.get( s.name )?.index ?? null;
	if ( rawStations && ! Array.isArray( rawStations ) && Object.keys( rawStations ).length ) {
		stationList = Object.entries( rawStations ).map( ( [ name, s ] ) => ( { ...s, name } ) );
	} else if ( rawStations && rawStations.length ) {
		stationList = rawStations.slice();
	} else {
		stationList = stationsFallback.stations;
		notes.push( 'stations: manifest had none, using scripts/qa_cameras.py fallback' );
	}
	let nextExtra = stationsFallback.stations.length + 1;
	const extras = [];
	stationList = stationList.map( ( s, i ) => {
		const idx = indexFor( s, i );
		if ( idx === null ) extras.push( s.name );
		return { ...s, index: idx === null ? nextExtra ++ : idx };
	} ).sort( ( a, b ) => a.index - b.index );
	if ( extras.length ) notes.push( `stations not in scripts/qa_cameras.py, indexed after 6: ${extras.join( ', ' )}` );
	const stations = stationList.map( ( s, i ) => {
		const ref = byName.get( s.name );
		return {
			index: s.index ?? i + 1,
			name: s.name ?? `station_${i + 1}`,
			location: s.location ?? s.loc,
			target: s.target ?? ref?.target ?? null,
			rotation_euler: s.rotation_euler_xyz ?? s.rotation_euler ?? s.rotation ?? null,
			matrix_world: s.matrix_world ?? s.matrix ?? null,
			lens: s.lens_mm ?? s.lens ?? 35,
			sensor_width: s.sensor_width_mm ?? s.sensor_width ?? 36,
			sensor_fit: s.sensor_fit ?? 'HORIZONTAL',
			shift_x: s.shift_x ?? 0,
			shift_y: s.shift_y ?? 0,
			clip_start: s.clip_start ?? 0.1,
			clip_end: s.clip_end ?? 5000,
			reference_photo: s.reference_photo ?? ref?.ref ?? null,
		};
	} );

	// --- colour --------------------------------------------------------------------------------
	const lutRaw = pick( raw, 'lut', 'colour.lut', 'color.lut' );
	const sh = ( typeof lutRaw === 'object' && lutRaw && typeof lutRaw.shaper === 'object' ) ? lutRaw.shaper : null;
	const lut = lutRaw ? {
		url: resolveUrl( baseUrl, typeof lutRaw === 'string' ? lutRaw : ( lutRaw.url || lutRaw.path || lutRaw.file ) ),
		size: ( typeof lutRaw === 'object' && ( lutRaw.size ?? lutRaw.lut_size ) ) || null,
		// schema pfa-phase6-gate0/1: lut.shaper = { min_ev, max_ev, pivot } means an AgX log2 shaper
		shaper: sh ? 'log2' : ( ( typeof lutRaw === 'object' && typeof lutRaw.shaper === 'string' ) ? lutRaw.shaper : null ),
		shaperMin: sh ? sh.min_ev : ( ( typeof lutRaw === 'object' && ( lutRaw.shaper_min ?? lutRaw.shaperMin ) ) ?? undefined ),
		shaperMax: sh ? sh.max_ev : ( ( typeof lutRaw === 'object' && ( lutRaw.shaper_max ?? lutRaw.shaperMax ) ) ?? undefined ),
		shaperPivot: sh ? ( sh.pivot ?? 0.18 ) : undefined,
		exposureOwner: ( typeof lutRaw === 'object' && lutRaw.exposure_applied_by ) || null,
	} : null;
	if ( ! lut ) notes.push( 'no LUT in the manifest: the display pass falls back to gamma 2.2 (NOT the Phase 5 look)' );

	// Exposure.  export/bake_lut.py pushes the identity Hald through Blender's OWN view transform AT
	// the scene's exposure, so a LUT from that bake ALREADY contains -2.833 EV and the pass multiplier
	// must stay 1.0.  An explicit exposure_multiplier wins; `includes_exposure: false` switches to 2^EV.
	let exposure = pick( raw, 'exposure_multiplier', 'exposure_scale', 'colour.exposure_multiplier', 'view.exposure_multiplier' );
	const ev = pick( raw, 'exposure_ev', 'view.exposure_ev', 'exposure', 'view.exposure', 'colour.exposure' );
	const lutHasExposure = pick( raw, 'lut.includes_exposure', 'view.lut.includes_exposure', 'colour.lut.includes_exposure' );
	if ( exposure === undefined ) {
		if ( lut && /viewer/i.test( lut.exposureOwner || '' ) && ev !== undefined ) {
			exposure = Math.pow( 2, ev );
			notes.push( `exposure: the LUT says exposure_applied_by "${lut.exposureOwner}", multiplier 2^${ev.toFixed( 4 )} = ${Math.pow( 2, ev ).toFixed( 5 )}` );
		} else if ( lutHasExposure === false && ev !== undefined ) { exposure = Math.pow( 2, ev ); notes.push( `exposure: LUT declares includes_exposure false, multiplier 2^${ev} = ${Math.pow( 2, ev ).toFixed( 5 )}` ); }
		else if ( lut ) { exposure = 1.0; notes.push( `exposure: multiplier 1.0 (the LUT carries the ${ev !== undefined ? ev.toFixed( 3 ) : '-2.833'} EV exposure)` ); }
		else if ( ev !== undefined ) { exposure = Math.pow( 2, ev ); notes.push( `exposure: no LUT, gamma fallback gets 2^${ev.toFixed( 3 )} = ${Math.pow( 2, ev ).toFixed( 5 )}` ); }
		else { exposure = 1.0; notes.push( 'exposure: absent, multiplier = 1' ); }
	}

	// --- sky -----------------------------------------------------------------------------------
	const sky = pick( raw, 'sky', 'world', 'environment' ) || {};
	// schema pfa-phase6-gate0/1: sky.camera / sky.glossy are objects { exr, hdr }.  The .hdr (RGBE) is
	// used: 3.6 MB vs 32 MB and enough range for a background and a PMREM source.
	const skyFile = ( v ) => ( typeof v === 'string' ? v : ( v && ( v.hdr || v.exr ) ) );
	const skyCamera = resolveUrl( baseUrl, skyFile( pick( sky, 'camera', 'background', 'camera_hdr', 'camera_exr' ) ) );
	const skyGlossy = resolveUrl( baseUrl, skyFile( pick( sky, 'glossy', 'specular', 'glossy_hdr', 'glossy_exr' ) ) );
	// Blender/manifest mapping: u = 0.5 + atan2(bx, by)/360.  With three (X,Y,Z) = blender (x, z, -y)
	// that is three's atan2(Z,X) + 90 deg, so the manifest's u is three's u + 0.25 and the environment
	// needs a quarter turn about Y.  three's backgroundRotation applies the INVERSE sense, so the value
	// is +90, measured: a sweep of 0 / 90 / 180 / -90 against the Cycles reference frame gives
	// mean |delta| over five sky boxes of 33.1 / 1.5 / 19.0 / 21.4 of 255.
	const skyRotationDeg = def( pick( sky, 'rotation_deg', 'rotation' ), 90,
		'sky.rotation_deg (+90 about Y; measured against the Cycles frame, 1.5/255)' );

	// --- sun (specular only; the diffuse is in the lightmaps) ----------------------------------
	// The manifest's `direction_blender` / `direction_gltf` is the direction the light TRAVELS, so the
	// DirectionalLight is placed at -direction * d.  An azimuth/elevation pair instead points TOWARD
	// the sun, so the light is placed at +direction * d.
	const sunRaw = pick( raw, 'sun', 'light.sun' ) || {};
	let toSunBlender = null;
	const travel = pick( sunRaw, 'direction_blender', 'direction', 'vector', 'dir' );
	const az = pick( sunRaw, 'azimuth', 'azimuth_deg' ), el = pick( sunRaw, 'elevation', 'elevation_deg' );
	if ( travel ) { toSunBlender = travel.map( v => - v ); notes.push( `sun: travel direction [${travel.map( v => v.toFixed( 3 ) )}] -> light placed opposite` ); }
	else if ( az !== undefined && el !== undefined ) {
		// scripts/common.sun_direction: azimuth clockwise from north, -X = north, +Y = east
		const a = az * Math.PI / 180, e = el * Math.PI / 180;
		toSunBlender = [ - Math.cos( a ) * Math.cos( e ), Math.sin( a ) * Math.cos( e ), Math.sin( e ) ];
		notes.push( `sun: direction from azimuth ${az} / elevation ${el}` );
	} else {
		const a = 118.5 * Math.PI / 180, e = 7.36 * Math.PI / 180;
		toSunBlender = [ - Math.cos( a ) * Math.cos( e ), Math.sin( a ) * Math.cos( e ), Math.sin( e ) ];
		notes.push( 'sun: absent, using the Phase 5 world (az 118.5, el 7.36)' );
	}
	const sun = {
		toSunBlender,
		irradiance: def( pick( sunRaw, 'energy_w_m2', 'irradiance', 'strength', 'energy' ), 67.3, 'sun.irradiance (W/m2, Phase 5 LIGHT_sun)' ),
		color: pick( sunRaw, 'color', 'colour' ) || [ 1, 1, 1 ],
		angleDeg: pick( sunRaw, 'angle_deg' ) ?? ( pick( sunRaw, 'angle_rad' ) !== undefined ? pick( sunRaw, 'angle_rad' ) * 180 / Math.PI : 0.526 ),
	};

	// --- lightmaps -----------------------------------------------------------------------------
	// ONE RGBM range for every lightmap path (schema: textures.<key>.rgbm_range, 64 at Gate 0).
	// A missing value is reported, because silently using another number is a brightness error.
	const textures = pick( raw, 'textures' ) || {};
	let rgbmFound;
	for ( const [ k, v ] of Object.entries( textures ) ) {
		if ( k.includes( 'lightmap' ) && v && v.rgbm_range ) { rgbmFound = v.rgbm_range; break; }
	}
	// manifest v2 carries the scene-wide value in lightmap_encoding.rgbm_range (QA-11c-3): use it before any default.
	if ( rgbmFound === undefined && raw.lightmap_encoding && raw.lightmap_encoding.rgbm_range ) rgbmFound = raw.lightmap_encoding.rgbm_range;
	const rgbmRange = def( rgbmFound, 7.0, 'lightmap rgbm_range (no textures.*lightmap*.rgbm_range or lightmap_encoding.rgbm_range in the manifest)' );

	// lightmap_scale: the Cycles colour-off diffuse pass is irradiance/pi and three's lightMap path
	// divides by pi again in BRDF_Lambert, so the manifest carries the compensating factor (pi).
	const lightmapScale = def( pick( raw, 'lightmap_scale', 'lightmaps.scale', 'view.lightmap_scale', 'textures.lightmap_scale' ),
		1.0, 'lightmap_scale (absent: the decoded lightmap is used as-is)' );

	// Accepted shapes: {lightmaps:[{match|object|mesh|material, url, encoding, intensity}]}
	//                  {assets:[{name, lightmap:{url, encoding}}]}
	const lightmaps = [];
	for ( const lm of pick( raw, 'lightmaps' ) || [] ) {
		lightmaps.push( {
			match: lm.match ?? lm.object ?? lm.mesh ?? lm.material ?? lm.name,
			matchKind: lm.material ? 'material' : 'object',
			url: resolveUrl( baseUrl, lm.url || lm.path || lm.file ),
			encoding: lm.encoding || 'linear',
			intensity: lm.intensity ?? 1.0,
			rgbmMaxRange: lm.rgbm_max_range ?? lm.max_range ?? rgbmRange,
		} );
	}
	const assetsRaw = pick( raw, 'assets' ) || [];
	const assetList = Array.isArray( assetsRaw )
		? assetsRaw : Object.entries( assetsRaw ).map( ( [ name, a ] ) => ( { name, ...a } ) );
	const reservations = {};
	for ( const a of assetList ) {
		const lm = a.lightmap;
		if ( ! lm ) continue;
		// manifest v2 states a PLAN, not a texture: {mode:'slot', pool, atlas, slot, uv2_offset,
		// uv2_scale} reserves an atlas cell, {mode:'asset', size} an own map, {mode:'none'} nothing.
		// None of them exists before the Gate 3 bake, so they are counted per mode, not warned about.
		if ( typeof lm === 'object' && lm.mode && ! lm.path && ! lm.url && ! lm.file ) {
			reservations[ lm.mode ] = ( reservations[ lm.mode ] || 0 ) + 1;
			continue;
		}
		// schema pfa-phase6-gate0/1: assets[].lightmap is a KEY into `textures`, not a URL.  Resolving
		// it as a URL would 404 and, worse, skip the in-glb emissive path and leave the lightmap
		// rendering as full-bright emissive.  A texture entry carries path, encoding and rgbm_range.
		const tex = ( typeof lm === 'string' ) ? textures[ lm ] : lm;
		if ( typeof lm === 'string' && ! tex ) { notes.push( `asset ${a.name}: lightmap key "${lm}" is not in textures, ignored` ); continue; }
		const url = resolveUrl( baseUrl, tex.path || tex.url || tex.file );
		if ( ! url ) { notes.push( `asset ${a.name}: lightmap "${lm}" has no path, ignored` ); continue; }
		lightmaps.push( {
			match: a.name ?? a.object,
			matchKind: 'object',
			url,
			encoding: /rgbm/i.test( tex.encoding || '' ) ? 'rgbm' : ( tex.encoding === 'sRGB' ? 'srgb' : 'linear' ),
			intensity: tex.intensity ?? 1.0,
			rgbmMaxRange: tex.rgbm_range ?? tex.rgbm_max_range ?? rgbmRange,
		} );
	}

	if ( Object.keys( reservations ).length )
		notes.push( `lightmap reservations for the Gate 3 bake, no texture yet: `
			+ Object.entries( reservations ).map( ( [ m, n ] ) => `${n} mode "${m}"` ).join( ', ' ) );

	// --- materials: the Gate 2 PBR texture sets (manifest v3 `pfa-phase6/3`) --------------------
	// Shape, tolerant on purpose (the bake engineer documents the exact one in export/README.md):
	//   materials: { mode: "pbr", sets|per_material|materials: { <material name>: {
	//       albedo|base_color|diffuse: { path, colorspace, bytes }, roughness|rough: {...},
	//       normal: {...}, metalness|metallic: {...}, ao|occlusion: {...} } } }
	// A map value may also be a bare path string.  Anything that is not a texture entry is ignored.
	// Colour space: whatever the manifest states wins; the fallback is albedo sRGB, every other map
	// linear (data), and every fallback is reported so a silent colour-space error is impossible.
	const MAP_KEYS = {
		map: [ 'albedo', 'base_color', 'basecolor', 'base_colour', 'diffuse', 'colour', 'color', 'map' ],
		roughnessMap: [ 'roughness', 'rough', 'roughness_map' ],
		normalMap: [ 'normal', 'normal_map', 'nrm', 'tangent_normal' ],
		metalnessMap: [ 'metalness', 'metallic', 'metal' ],
		aoMap: [ 'ao', 'occlusion', 'ambient_occlusion' ],
	};
	const SRGB_DEFAULT = { map: true, roughnessMap: false, normalMap: false, metalnessMap: false, aoMap: false };
	const matRoot = pick( raw, 'materials', 'material_textures', 'pbr' ) || {};
	const materialsMode = ( typeof matRoot === 'object' && ( matRoot.mode || matRoot.materials_mode ) ) || null;
	const setsRaw = ( typeof matRoot === 'object'
		&& ( pick( matRoot, 'sets', 'per_material', 'materials', 'entries' )
			|| ( ! matRoot.mode && Object.keys( matRoot ).length ? matRoot : null ) ) )
		|| pick( raw, 'textures.per_material', 'textures.materials' ) || {};
	const texBase = ( pick( raw, 'textures.ktx2_dir', 'materials.dir', 'materials.ktx2_dir' ) || '' );
	const joinTex = ( p ) => {
		if ( ! p ) return null;
		// a bare file name is relative to the manifest's texture directory, a path with a slash is not
		return resolveUrl( baseUrl, ( texBase && ! p.includes( '/' ) ) ? `${texBase.replace( /\/$/, '' )}/${p}` : p );
	};
	const materialSets = {};
	const csFallbacks = [];
	let mapCount = 0, setBytes = 0;
	for ( const [ name, entry ] of Object.entries( typeof setsRaw === 'object' && setsRaw ? setsRaw : {} ) ) {
		if ( ! entry || typeof entry !== 'object' ) continue;
		const src = entry.maps && typeof entry.maps === 'object' ? entry.maps : entry;
		const set = { name, maps: {}, uv: entry.uv ?? src.uv ?? 'UV1', wrap: entry.wrap ?? src.wrap ?? null };
		for ( const [ slot, aliases ] of Object.entries( MAP_KEYS ) ) {
			let v;
			for ( const a of aliases ) { if ( src[ a ] !== undefined && src[ a ] !== null ) { v = src[ a ]; break; } }
			if ( v === undefined ) continue;
			const o = ( typeof v === 'object' ) ? v : { path: v };
			const url = joinTex( o.path || o.url || o.file || o.ktx2 );
			if ( ! url || ! /\.(ktx2|png|jpg|jpeg|webp|exr|hdr)(\?.*)?$/i.test( url ) ) continue;
			const cs = ( o.colorspace ?? o.color_space ?? o.colour_space ?? o.encoding ?? null );
			let srgb;
			if ( cs === null || cs === undefined ) { srgb = SRGB_DEFAULT[ slot ]; csFallbacks.push( `${name}.${slot}=${srgb ? 'sRGB' : 'linear'}` ); }
			else srgb = /srgb|s-rgb|colou?r$/i.test( String( cs ) ) && ! /non-?colou?r|linear|data|raw/i.test( String( cs ) );
			set.maps[ slot ] = { url, srgb, declared: cs, bytes: o.bytes ?? o.size ?? null, scale: o.scale ?? null };
			mapCount ++; setBytes += o.bytes ?? o.size ?? 0;
		}
		const aliasRaw = entry.materials ?? entry.applies_to ?? entry.material_names ?? entry.material ?? entry.group_materials;
		set.aliases = ( Array.isArray( aliasRaw ) ? aliasRaw : ( typeof aliasRaw === 'string' ? [ aliasRaw ] : [] ) ).filter( x => typeof x === 'string' );
		if ( Object.keys( set.maps ).length ) {
			if ( entry.roughness_factor !== undefined ) set.roughnessFactor = entry.roughness_factor;
			if ( entry.metalness_factor !== undefined ) set.metalnessFactor = entry.metalness_factor;
			if ( entry.normal_scale !== undefined ) set.normalScale = entry.normal_scale;
			materialSets[ name ] = set;
		}
	}
	const materials = {
		mode: materialsMode,
		sets: materialSets,
		count: Object.keys( materialSets ).length,
		maps: mapCount,
		declaredBytes: setBytes,
	};
	if ( materials.count ) {
		notes.push( `materials: ${materials.count} PBR texture set(s), ${mapCount} maps`
			+ ( setBytes ? `, ${( setBytes / 1e6 ).toFixed( 1 )} MB declared` : ', no declared bytes (HEAD)' )
			+ `, mode "${materialsMode || '(unstated)'}"` );
		if ( csFallbacks.length ) notes.push( `colour space defaulted on ${csFallbacks.length} map(s) (manifest states none): ${csFallbacks.slice( 0, 6 ).join( ', ' )}${csFallbacks.length > 6 ? ' …' : ''}` );
	} else if ( materialsMode ) {
		notes.push( `materials.mode "${materialsMode}" but no per-material texture set was recognised` );
	}

	// --- Gate 1 extras: far-tree billboard quads, ORN atlas slots ------------------------------
	// `trees.far` is the Gate 3 impostor list: each entry is a prototype id, a height and a trunk base.
	// Until that bake exists the viewer draws one flat, explicitly tagged quad per entry.
	const treesRaw = pick( raw, 'trees', 'tree_lists', 'vegetation' ) || {};
	const farRaw = pick( raw, 'tree_far' ) || pick( treesRaw, 'far', 'billboards', 'far_list' ) || [];
	const treesFar = ( Array.isArray( farRaw ) ? farRaw : [] ).map( ( t ) => ( {
		prototype: t.prototype ?? t.proto ?? t.id ?? t.name ?? 'tree',
		id: t.billboard ?? null,
		height: t.height_m ?? t.height ?? t.h ?? 12,
		width: t.width_m ?? t.width ?? t.w ?? null,
		base: t.trunk_base ?? t.base ?? t.location_blender ?? t.location ?? t.position ?? null,
	} ) ).filter( t => Array.isArray( t.base ) && t.base.length === 3 );
	if ( farRaw.length && treesFar.length !== farRaw.length )
		notes.push( `tree_far: ${farRaw.length - treesFar.length} of ${farRaw.length} entries have no trunk base, skipped` );
	const nearRaw = pick( raw, 'tree_near' ) || pick( treesRaw, 'near', 'near_list' ) || [];
	// v2: orn_slots = { <pool>: [ {object, atlas, slot}, ... ] }.  Gate 1 has no atlas texture yet;
	// the viewer only reports the reservation so a Gate 3 regression is visible in the sidecar.
	const ornSlotsRaw = pick( raw, 'orn_slots', 'orn.slots', 'ornament.slots' ) || null;
	const ornSlots = ornSlotsRaw && typeof ornSlotsRaw === 'object' && ! Array.isArray( ornSlotsRaw )
		? Object.fromEntries( Object.entries( ornSlotsRaw ).map( ( [ pool, v ] ) => [ pool, {
			entries: Array.isArray( v ) ? v.length : null,
			atlases: Array.isArray( v ) ? new Set( v.map( e => e.atlas ) ).size : null,
		} ] ) )
		: ornSlotsRaw;

	const out = {
		raw, baseUrl, glb, glbs, stations, lut, exposure, sun, lightmaps, notes, rgbmRange, lightmapScale, materials,
		treesFar, treesNearCount: Array.isArray( nearRaw ) ? nearRaw.length : 0, ornSlots,
		schema: pick( raw, 'schema' ) || null,
		waterZ: def( pick( raw, 'water.viewer_y', 'water.water_z', 'water_z', 'waterZ', 'scene.water_z' ), WATER_Z, 'water_z' ),
		sky: { camera: skyCamera, glossy: skyGlossy, rotationDeg: skyRotationDeg },
		frameSize: pick( raw, 'frame', 'render.frame' ) || { width: 1280, height: 720 },
	};
	if ( ! glbs.length ) notes.push( 'no glb in the manifest: test scene only' );
	return out;
}
