// Normalises export/out/<gate>/manifest.json (written by the bake engineer) into what the viewer needs,
// so a schema change there is absorbed in one place.  Every field that had to be defaulted is reported
// in `notes` and logged, because a silently defaulted exposure or sun vector makes parity meaningless.
import stationsFallback from './stations_blender.json' with { type: 'json' };

// Generated by web/tools/dump_stations.py from scripts/common.py + scripts/qa_cameras.py (review carry
// 10): nothing here is hand-copied.  The manifest still wins over all of it at run time.
export const WATER_Z = stationsFallback.water_z;

function pick( obj, ...keys ) {
	for ( const k of keys ) {
		const v = k.split( '.' ).reduce( ( o, p ) => ( o == null ? o : o[ p ] ), obj );
		if ( v !== undefined && v !== null ) return v;
	}
	return undefined;
}

/** Choose which of an own-map asset's two baked variants applies, from its CURRENT `uv2InGlb`.
 *  `uv2_in_glb` true -> the map baked on the layout the glb carries (Gate 3's re-laid one for the
 *  seven relaid assets); false -> the `_gate1_layout` twin baked on the frozen layout, where the bake
 *  shipped one; neither -> NO map, because there is no factor fallback for a lightmap. */
export function selectOwnMap( a ) {
	const tex = a.uv2InGlb ? a.gate3Tex : a.frozenTex;
	a.layout = a.uv2InGlb ? ( a.relaid ? 'gate3_relaid' : 'gate1' ) : 'gate1_frozen';
	a.blocked = tex ? null : ( a.uv2InGlb ? 'no usable texture' : 'uv2_in_glb false and no _gate1_layout twin' );
	for ( const k of [ 'url', 'textureKey', 'variant', 'encode', 'range', 'bytes', 'residentMb', 'w', 'h', 'tier' ] ) a[ k ] = tex ? tex[ k ] : undefined;
	if ( ! a.uv2InGlb && a.frozenTex ) a.cmPerTexelEffective = a.frozenCmPerTexel;
	else a.cmPerTexelEffective = a.cmPerTexel;
	return a;
}

/**
 * Fold `export/out/gate3/uv2_relay_status.json` (written by export/gate3_relay_check.py) into a
 * normalised manifest.  The export re-packs the glbs with the re-laid UV2 before the bake rewrites
 * `lightmaps.assets[*].uv2_in_glb`, so that file — not the manifest — is what the glb on disk
 * actually carries.  Returns a short report for the notes.
 */
export function applyUv2RelayStatus( manifest, status ) {
	const out = { applied: 0, flipped: [], meshes: 0, vertexIrradianceInGlb: null, note: null };
	if ( ! manifest.gate3 || ! status || ! status.uv2 ) return out;
	for ( const rec of Object.values( status.uv2 ) ) {
		const a = manifest.gate3.ownMaps[ rec.asset ];
		if ( ! a ) continue;
		out.applied ++;
		const want = rec.uv2_in_glb === true;
		if ( a.uv2InGlb === want ) continue;
		a.uv2InGlb = want;
		selectOwnMap( a );
		out.flipped.push( `${rec.asset} -> ${a.layout}${a.blocked ? ` (${a.blocked})` : ''}` );
	}
	out.meshes = status.uv2_all_meshes ? Object.keys( status.uv2_all_meshes ).length : 0;
	// The relay is the only place the per-mesh RANGE and the mesh -> asset mapping live together;
	// the manifest's own `meshes` block is keyed by the EXPM mesh name and carries no asset.
	const vi = status.vertex_irradiance;
	out.vertexIrradianceInGlb = vi && Object.keys( vi ).length ? true : false;
	if ( vi && manifest.gate3.vertexIrradiance ) {
		const byAsset = {};
		const globals = new Set();
		for ( const [ mesh, rec ] of Object.entries( vi ) ) {
			if ( ! rec || rec.in_glb !== true || ! rec.asset ) continue;
			const r = typeof rec.range_global === 'number' ? rec.range_global : rec.range;
			if ( typeof r !== 'number' || ! ( r > 0 ) ) continue;
			if ( typeof rec.range_global === 'number' ) globals.add( rec.range_global );
			byAsset[ rec.asset ] = { mesh, range: r, encoding: rec.encoding || 'gamma2', attribute: rec.attribute || 'COLOR_0' };
		}
		manifest.gate3.vertexIrradiance.byAsset = byAsset;
		manifest.gate3.vertexIrradiance.inGlb = Object.keys( byAsset ).length > 0;
		// ONE GLOBAL RANGE (the lead's call after gltfpack -mi was found to share a COLOR_0 buffer
		// across trees baked at different ranges).  The manifest's own
		// `lightmaps.vertex_irradiance.range` wins; the relay's `range_global` is the fallback while
		// that key is still landing.  If neither states it there is NO fallback to a guess - the
		// decode is simply refused, because a wrong range is a ~90x error in irradiance.
		if ( globals.size === 1 && manifest.gate3.vertexIrradiance.range == null ) {
			manifest.gate3.vertexIrradiance.range = [ ...globals ][ 0 ];
			manifest.gate3.vertexIrradiance.rangeFrom = 'uv2_relay_status.json range_global (FALLBACK: the manifest key was absent)';
		} else if ( globals.size > 1 ) {
			manifest.gate3.vertexIrradiance.rangeConflict = [ ...globals ];
		}
		out.vertexIrradianceAssets = Object.keys( byAsset ).length;
		out.vertexIrradianceRange = manifest.gate3.vertexIrradiance.range ?? null;
	}
	if ( status.vertex_irradiance_skipped ) out.note = String( status.vertex_irradiance_skipped );
	const g3 = manifest.gate3;
	g3.ownCount = Object.values( g3.ownMaps ).filter( m => m.url ).length;
	g3.blockedNoUv2 = Object.values( g3.ownMaps ).filter( m => m.blocked ).length;
	g3.frozenUsed = Object.values( g3.ownMaps ).filter( m => m.layout === 'gate1_frozen' && m.url ).length;
	g3.relayStatus = out;
	return out;
}

export function resolveUrl( base, url ) {
	if ( ! url ) return null;
	if ( /^(https?:)?\//.test( url ) ) return url;
	return new URL( url, base ).href;
}

/**
 * manifest v5 (`pfa-phase6/5`) LOAD TIERS.  The contract the viewer consumes is in web/README.md
 * "Phase 6b"; this reads it and nothing here invents one.  Three places may declare a file's tier and
 * the SMALLEST wins, because a tier number is "the latest moment this file may arrive" and a file
 * named twice must arrive by the earlier of the two:
 *   1. `files[<path>].tier`      the per-file table (authoritative, carries bytes and the `lo` variant)
 *   2. `tiers[n].files[]`        the per-tier file list
 *   3. the owning object's own `tier` (a glb group, a texture entry)
 * A file NO tier mentions is tier 0: it boots.  That way an export that forgets a file ships a slower
 * first payload, never a missing one, and `tiers.undeclared` in the viewer's report names it.
 *
 * Accepted shapes for `tiers`: an ARRAY of tier objects, `{ list: [...] }`, or an object keyed
 * "0"/"tier0"/"t0".  Each tier object: { tier|index|n, bytes|total_bytes, label, files[] }.
 */
export function readTiers( raw, baseUrl, resolve = resolveUrl ) {
	const notes = [];
	const out = { present: false, count: 0, list: [], oversize: [], byUrl: new Map(), files: new Map(),
		totals: {}, notes, declaredBytes: 0 };
	const rawTiers = pick( raw, 'tiers', 'load_tiers' );
	const rawFiles = pick( raw, 'files', 'tiers.files' );
	if ( ! rawTiers && ! ( rawFiles && typeof rawFiles === 'object' ) ) return out;

	/** Record `url` at tier `t` unless it is already recorded at an earlier one. */
	const claim = ( url, t ) => {
		if ( ! url || ! Number.isFinite( t ) ) return;
		const prev = out.byUrl.get( url );
		if ( prev === undefined || t < prev ) out.byUrl.set( url, t );
	};
	const entryOf = ( v ) => ( typeof v === 'string' ? { path: v } : ( v && typeof v === 'object' ? v : null ) );

	// --- the per-file table --------------------------------------------------------------------
	// { "<path>": { bytes, tier, kind, lo: { path, bytes, tier } } }.  `lo` is the LOW-RESOLUTION
	// stand-in an earlier tier ships for a texture whose full-resolution file arrives later; the
	// viewer loads `lo` first and hot-swaps the full file onto the same material when it lands.
	if ( rawFiles && typeof rawFiles === 'object' && ! Array.isArray( rawFiles ) ) {
		for ( const [ p, v ] of Object.entries( rawFiles ) ) {
			const e = entryOf( v ) || {};
			const url = resolve( baseUrl, e.path || p );
			if ( ! url ) continue;
			const tier = Number.isFinite( e.tier ) ? e.tier : undefined;
			const loRaw = entryOf( e.lo || e.low || e.variant_lo );
			let lo = null;
			if ( loRaw && loRaw.path ) {
				const loUrl = resolve( baseUrl, loRaw.path );
				// `lo` pointing at the same file is not a variant: there is nothing to swap.
				if ( loUrl && loUrl !== url ) {
					lo = { url: loUrl, bytes: loRaw.bytes ?? null,
						tier: Number.isFinite( loRaw.tier ) ? loRaw.tier : 0,
						standIn: loRaw.stand_in === true || loRaw.standIn === true };
					claim( loUrl, lo.tier );
				}
			}
			const row = { url, path: e.path || p, bytes: e.bytes ?? e.size ?? null, tier, kind: e.kind || null, lo };
			out.files.set( url, row );
			if ( tier !== undefined ) claim( url, tier );
			if ( row.bytes ) out.declaredBytes += row.bytes;
		}
	}

	// --- the tier list -------------------------------------------------------------------------
	let list = [];
	if ( Array.isArray( rawTiers ) ) list = rawTiers;
	else if ( rawTiers && typeof rawTiers === 'object' ) {
		if ( Array.isArray( rawTiers.list ) ) list = rawTiers.list;
		else if ( Array.isArray( rawTiers.tiers ) ) list = rawTiers.tiers;
		else list = Object.entries( rawTiers )
			.filter( ( [ k, v ] ) => /^(tier|t)?\d+$/i.test( k ) && v && typeof v === 'object' )
			.map( ( [ k, v ] ) => ( { tier: parseInt( String( k ).replace( /^(tier|t)/i, '' ), 10 ), ...v } ) );
	}
	for ( let i = 0; i < list.length; i ++ ) {
		const t = list[ i ] || {};
		const n = Number.isFinite( t.tier ) ? t.tier : ( Number.isFinite( t.index ) ? t.index : ( Number.isFinite( t.n ) ? t.n : i ) );
		const files = [];
		for ( const f of ( Array.isArray( t.files ) ? t.files : [] ) ) {
			const e = entryOf( f );
			if ( ! e || ! ( e.path || typeof f === 'string' ) ) continue;
			const url = resolve( baseUrl, e.path );
			if ( ! url ) continue;
			files.push( url );
			claim( url, n );
			if ( ! out.files.has( url ) ) out.files.set( url, { url, path: e.path, bytes: e.bytes ?? null, tier: n, kind: e.kind || null, lo: null } );
		}
		out.list.push( { tier: n, bytes: t.bytes ?? t.total_bytes ?? null, label: t.label || t.note || null,
			files, count: t.files_n ?? files.length } );
	}
	out.list.sort( ( a, b ) => a.tier - b.tier );
	// A declared per-tier byte total is what the loading screen's denominator uses; when the export
	// states none, sum the per-file bytes of that tier instead of guessing.
	for ( const t of out.list ) {
		if ( t.bytes === null || t.bytes === undefined ) {
			let sum = 0, known = 0;
			for ( const [ url, n ] of out.byUrl ) {
				if ( n !== t.tier ) continue;
				const row = out.files.get( url );
				if ( row && row.bytes ) { sum += row.bytes; known ++; }
			}
			t.bytes = known ? sum : null;
			t.bytesFrom = known ? 'summed from files[]' : 'unknown';
		} else t.bytesFrom = 'declared';
		out.totals[ t.tier ] = t.bytes;
	}
	const oversizeRaw = ( rawTiers && ! Array.isArray( rawTiers ) && ( rawTiers.oversize || rawTiers.over_size ) ) || [];
	for ( const v of ( Array.isArray( oversizeRaw ) ? oversizeRaw : [] ) ) {
		const e = entryOf( v );
		if ( ! e ) continue;
		out.oversize.push( { url: resolve( baseUrl, e.path ), path: e.path, bytes: e.bytes ?? null, reason: e.reason || null } );
	}
	out.present = out.list.length > 0 || out.files.size > 0;
	out.count = out.list.length ? ( Math.max( ...out.list.map( t => t.tier ) ) + 1 )
		: ( out.byUrl.size ? Math.max( ...out.byUrl.values() ) + 1 : 0 );
	if ( out.present ) notes.push( `manifest tiers: ${out.count} tier(s), `
		+ out.list.map( t => `tier ${t.tier} ${( ( t.bytes || 0 ) / 1e6 ).toFixed( 1 )} MB in ${t.count} file(s) (${t.bytesFrom})` ).join( ', ' )
		+ ( out.oversize.length ? `; ${out.oversize.length} file(s) over the host's per-file cap: ${out.oversize.map( o => o.path ).join( ', ' )}` : '' ) );
	return out;
}

/** The tier a url belongs to.  A url no tier declares is tier 0 — it boots (see readTiers). */
export function tierForUrl( tiers, url, fallback = 0 ) {
	if ( ! tiers || ! tiers.present || ! url ) return fallback;
	const t = tiers.byUrl.get( url );
	return t === undefined ? fallback : t;
}

/**
 * @param {object|null} raw  parsed manifest.json (null -> pure defaults, test-scene mode)
 * @param {string} baseUrl   absolute URL of the manifest, for relative asset paths
 */
export function normaliseManifest( raw, baseUrl ) {
	const notes = [];
	const def = ( value, fallback, what ) => {
		if ( value === undefined || value === null ) { notes.push( `defaulted ${what} = ${JSON.stringify( fallback )}` ); return fallback; }
		return value;
	};
	raw = raw || {};

	// --- load tiers (manifest v5) --------------------------------------------------------------
	// Read FIRST: every url built below asks it which tier it belongs to, and a manifest without a
	// `tiers` block yields `present: false`, which makes every consumer behave exactly as it did at
	// v4 (one tier, everything at boot).
	const tiers = readTiers( raw, baseUrl );
	tiers.notes.forEach( n => notes.push( n ) );

	// --- geometry ------------------------------------------------------------------------------
	// schema pfa-phase6/2 ships ONE GLB PER CLASS (arch / orn / env / ground) loaded in the manifest's
	// order; pfa-phase6-gate0/1 shipped a single `glb`.  Both normalise to `glbs`, an ordered list of
	// { url, name, cls, bytes }.  `glb` stays as the first entry for anything that still reads it.
	const glbRaw = pick( raw, 'glb', 'files.glb', 'model' );
	const glbUrlOf = ( v ) => resolveUrl( baseUrl, typeof v === 'string' ? v : ( v?.path || v?.url || v?.file ) );
	const isGlbUrl = ( u ) => !! u && /\.(glb|gltf)(\?.*)?$/i.test( u );
	const glbEntry = ( v, key, i ) => {
		const url = glbUrlOf( v );
		if ( ! isGlbUrl( url ) ) return null;          // 'texture_source: ktx2' and prose notes are not files
		const o = ( typeof v === 'object' && v ) || {};
		return {
			url,
			name: url.split( '/' ).pop(),
			cls: o.class ?? o.cls ?? o.kind ?? key ?? `part_${i}`,
			// v5 `glb.groups`: the group KEY is the identity (orn_t1_03), `class` stays the lighting /
			// naming class (orn) so WEB_glb_<class> and the instance-irradiance lookup keep working.
			group: key ?? null,
			bytes: o.bytes ?? o.size ?? o.byte_length ?? null,
			// The group's own `tier` is the weakest of the three declarations (readTiers), so it only
			// applies when neither `files` nor the tier list named this file.
			tier: tierForUrl( tiers, url, Number.isFinite( o.tier ) ? o.tier : 0 ),
			declaredTier: Number.isFinite( o.tier ) ? o.tier : null,
			stations: o.stations || o.station_visibility || null,
			order: o.order ?? i,
		};
	};
	const listOf = ( v ) => {
		if ( ! v ) return [];
		if ( Array.isArray( v ) ) return v.map( ( e, i ) => glbEntry( e, null, i ) );
		if ( typeof v === 'object' ) {
			// A single glb object ({path, bytes, instanced_variant, ...}) is ONE file, not a map of
			// files: its sibling keys are metadata (gate0's `texture_source`, `instanced_variant`).
			if ( v.path || v.url || v.file ) return [ glbEntry( v, v.class ?? v.cls ?? null, 0 ) ];
			return Object.entries( v ).map( ( [ k, e ], i ) => glbEntry( e, k, i ) );
		}
		return [ glbEntry( v, null, 0 ) ];
	};
	// 'glb.per_class' is what export/gltf_pack.sh --gate1 actually writes:
	// glb.per_class = { arch:{path,bytes,…}, orn, env, ground } in load order.
	// v5 `glb.groups` is read BEFORE `glb.per_class`: a manifest that carries both is a v5 one whose
	// per_class block is kept for the older tools, and loading both would draw every mesh twice.
	let glbs = listOf( pick( raw, 'glbs', 'glb.groups', 'glb.per_class', 'glb.parts', 'glb.files', 'glb.classes', 'files.glbs' ) ).filter( Boolean );
	if ( ! glbs.length ) glbs = listOf( glbRaw ).filter( Boolean );
	// Tier first, then the manifest's own order inside a tier: tier 0 is what boots, and a later tier
	// can never be pulled in front of it by an `order` field.
	glbs.sort( ( a, b ) => ( a.tier - b.tier ) || ( a.order - b.order ) );
	glbs.forEach( ( g, i ) => { g.order = i; } );
	const glb = glbs.length ? glbs[ 0 ].url : null;
	if ( glbs.length > 1 ) notes.push( `${glbs.length} glbs, loaded in manifest order: ${glbs.map( g => `${g.cls}:${g.name}` ).join( ', ' )}` );

	// --- stations ------------------------------------------------------------------------------
	// schema pfa-phase6-gate0/1 keys stations by camera name with lens_mm / rotation_euler_xyz;
	// older/array shapes are accepted too.  Look-at targets are not in the manifest, so they are
	// taken from scripts/qa_cameras.py (stations_blender.json) by name purely as a cross-check.
	let rawStations = pick( raw, 'stations', 'cameras' );
	let stationList;
	const byName = new Map( stationsFallback.stations.map( s => [ s.name, s ] ) );
	// Keys 1-6 are the six scripts/qa_cameras.py stations BY NAME.  manifest v2 also carries cameras
	// that are not QA stations (CAM_flythrough), so key order must never decide the index: a camera
	// the generated list does not know is appended after 6, never inserted in front of the hero.
	const indexFor = ( s, i ) => s.index ?? byName.get( s.name )?.index ?? null;
	if ( rawStations && ! Array.isArray( rawStations ) && Object.keys( rawStations ).length ) {
		stationList = Object.entries( rawStations ).map( ( [ name, s ] ) => ( { ...s, name } ) );
	} else if ( rawStations && rawStations.length ) {
		stationList = rawStations.slice();
	} else {
		stationList = stationsFallback.stations;
		notes.push( 'stations: manifest had none, using scripts/qa_cameras.py fallback' );
	}
	let nextExtra = stationsFallback.stations.length + 1;
	const extras = [];
	stationList = stationList.map( ( s, i ) => {
		const idx = indexFor( s, i );
		if ( idx === null ) extras.push( s.name );
		return { ...s, index: idx === null ? nextExtra ++ : idx };
	} ).sort( ( a, b ) => a.index - b.index );
	if ( extras.length ) notes.push( `stations not in scripts/qa_cameras.py, indexed after 6: ${extras.join( ', ' )}` );
	const stations = stationList.map( ( s, i ) => {
		const ref = byName.get( s.name );
		return {
			index: s.index ?? i + 1,
			name: s.name ?? `station_${i + 1}`,
			location: s.location ?? s.loc,
			target: s.target ?? ref?.target ?? null,
			rotation_euler: s.rotation_euler_xyz ?? s.rotation_euler ?? s.rotation ?? null,
			matrix_world: s.matrix_world ?? s.matrix ?? null,
			lens: s.lens_mm ?? s.lens ?? 35,
			sensor_width: s.sensor_width_mm ?? s.sensor_width ?? 36,
			sensor_fit: s.sensor_fit ?? 'HORIZONTAL',
			shift_x: s.shift_x ?? 0,
			shift_y: s.shift_y ?? 0,
			clip_start: s.clip_start ?? 0.1,
			clip_end: s.clip_end ?? 5000,
			reference_photo: s.reference_photo ?? ref?.ref ?? null,
		};
	} );

	// --- colour --------------------------------------------------------------------------------
	const lutRaw = pick( raw, 'lut', 'colour.lut', 'color.lut' );
	const sh = ( typeof lutRaw === 'object' && lutRaw && typeof lutRaw.shaper === 'object' ) ? lutRaw.shaper : null;
	const lut = lutRaw ? {
		url: resolveUrl( baseUrl, typeof lutRaw === 'string' ? lutRaw : ( lutRaw.url || lutRaw.path || lutRaw.file ) ),
		size: ( typeof lutRaw === 'object' && ( lutRaw.size ?? lutRaw.lut_size ) ) || null,
		// schema pfa-phase6-gate0/1: lut.shaper = { min_ev, max_ev, pivot } means an AgX log2 shaper
		shaper: sh ? 'log2' : ( ( typeof lutRaw === 'object' && typeof lutRaw.shaper === 'string' ) ? lutRaw.shaper : null ),
		shaperMin: sh ? sh.min_ev : ( ( typeof lutRaw === 'object' && ( lutRaw.shaper_min ?? lutRaw.shaperMin ) ) ?? undefined ),
		shaperMax: sh ? sh.max_ev : ( ( typeof lutRaw === 'object' && ( lutRaw.shaper_max ?? lutRaw.shaperMax ) ) ?? undefined ),
		shaperPivot: sh ? ( sh.pivot ?? 0.18 ) : undefined,
		exposureOwner: ( typeof lutRaw === 'object' && lutRaw.exposure_applied_by ) || null,
	} : null;
	if ( ! lut ) notes.push( 'no LUT in the manifest: the display pass falls back to gamma 2.2 (NOT the Phase 5 look)' );

	// Exposure.  export/bake_lut.py pushes the identity Hald through Blender's OWN view transform AT
	// the scene's exposure, so a LUT from that bake ALREADY contains -2.833 EV and the pass multiplier
	// must stay 1.0.  An explicit exposure_multiplier wins; `includes_exposure: false` switches to 2^EV.
	let exposure = pick( raw, 'exposure_multiplier', 'exposure_scale', 'colour.exposure_multiplier', 'view.exposure_multiplier' );
	const ev = pick( raw, 'exposure_ev', 'view.exposure_ev', 'exposure', 'view.exposure', 'colour.exposure' );
	const lutHasExposure = pick( raw, 'lut.includes_exposure', 'view.lut.includes_exposure', 'colour.lut.includes_exposure' );
	if ( exposure === undefined ) {
		if ( lut && /viewer/i.test( lut.exposureOwner || '' ) && ev !== undefined ) {
			exposure = Math.pow( 2, ev );
			notes.push( `exposure: the LUT says exposure_applied_by "${lut.exposureOwner}", multiplier 2^${ev.toFixed( 4 )} = ${Math.pow( 2, ev ).toFixed( 5 )}` );
		} else if ( lutHasExposure === false && ev !== undefined ) { exposure = Math.pow( 2, ev ); notes.push( `exposure: LUT declares includes_exposure false, multiplier 2^${ev} = ${Math.pow( 2, ev ).toFixed( 5 )}` ); }
		else if ( lut ) { exposure = 1.0; notes.push( `exposure: multiplier 1.0 (the LUT carries the ${ev !== undefined ? ev.toFixed( 3 ) : '-2.833'} EV exposure)` ); }
		else if ( ev !== undefined ) { exposure = Math.pow( 2, ev ); notes.push( `exposure: no LUT, gamma fallback gets 2^${ev.toFixed( 3 )} = ${Math.pow( 2, ev ).toFixed( 5 )}` ); }
		else { exposure = 1.0; notes.push( 'exposure: absent, multiplier = 1' ); }
	}

	// --- sky -----------------------------------------------------------------------------------
	const sky = pick( raw, 'sky', 'world', 'environment' ) || {};
	// schema pfa-phase6-gate0/1: sky.camera / sky.glossy are objects { exr, hdr }.  The .hdr (RGBE) is
	// used: 3.6 MB vs 32 MB and enough range for a background and a PMREM source.
	const skyFile = ( v ) => ( typeof v === 'string' ? v : ( v && ( v.hdr || v.exr ) ) );
	const skyCamera = resolveUrl( baseUrl, skyFile( pick( sky, 'camera', 'background', 'camera_hdr', 'camera_exr' ) ) );
	const skyGlossy = resolveUrl( baseUrl, skyFile( pick( sky, 'glossy', 'specular', 'glossy_hdr', 'glossy_exr' ) ) );
	// v4 `sky.diffuse` (QA-12b-1): the world's DIFFUSE branch as its own equirect.  The glossy branch
	// is a different colour, and using its PMREM as the diffuse environment made 16-22 % of the
	// cam02/cam06 building pixels read olive-green.  Diffuse irradiance comes from this one; specular
	// radiance stays on `sky.glossy`; the background sphere stays `sky.camera`.
	const skyDiffuse = resolveUrl( baseUrl, skyFile( pick( sky, 'diffuse', 'irradiance' ) ) );
	// Blender/manifest mapping: u = 0.5 + atan2(bx, by)/360.  With three (X,Y,Z) = blender (x, z, -y)
	// that is three's atan2(Z,X) + 90 deg, so the manifest's u is three's u + 0.25 and the environment
	// needs a quarter turn about Y.  three's backgroundRotation applies the INVERSE sense, so the value
	// is +90, measured: a sweep of 0 / 90 / 180 / -90 against the Cycles reference frame gives
	// mean |delta| over five sky boxes of 33.1 / 1.5 / 19.0 / 21.4 of 255.
	const skyRotationDeg = def( pick( sky, 'rotation_deg', 'rotation' ), 90,
		'sky.rotation_deg (+90 about Y; measured against the Cycles frame, 1.5/255)' );

	// --- sun (specular only; the diffuse is in the lightmaps) ----------------------------------
	// The manifest's `direction_blender` / `direction_gltf` is the direction the light TRAVELS, so the
	// DirectionalLight is placed at -direction * d.  An azimuth/elevation pair instead points TOWARD
	// the sun, so the light is placed at +direction * d.
	const sunRaw = pick( raw, 'sun', 'light.sun' ) || {};
	let toSunBlender = null;
	const travel = pick( sunRaw, 'direction_blender', 'direction', 'vector', 'dir' );
	const az = pick( sunRaw, 'azimuth', 'azimuth_deg' ), el = pick( sunRaw, 'elevation', 'elevation_deg' );
	if ( travel ) { toSunBlender = travel.map( v => - v ); notes.push( `sun: travel direction [${travel.map( v => v.toFixed( 3 ) )}] -> light placed opposite` ); }
	else if ( az !== undefined && el !== undefined ) {
		// scripts/common.sun_direction: azimuth clockwise from north, -X = north, +Y = east
		const a = az * Math.PI / 180, e = el * Math.PI / 180;
		toSunBlender = [ - Math.cos( a ) * Math.cos( e ), Math.sin( a ) * Math.cos( e ), Math.sin( e ) ];
		notes.push( `sun: direction from azimuth ${az} / elevation ${el}` );
	} else {
		const a = 118.5 * Math.PI / 180, e = 7.36 * Math.PI / 180;
		toSunBlender = [ - Math.cos( a ) * Math.cos( e ), Math.sin( a ) * Math.cos( e ), Math.sin( e ) ];
		notes.push( 'sun: absent, using the Phase 5 world (az 118.5, el 7.36)' );
	}
	const sun = {
		toSunBlender,
		irradiance: def( pick( sunRaw, 'energy_w_m2', 'irradiance', 'strength', 'energy' ), 67.3, 'sun.irradiance (W/m2, Phase 5 LIGHT_sun)' ),
		color: pick( sunRaw, 'color', 'colour' ) || [ 1, 1, 1 ],
		angleDeg: pick( sunRaw, 'angle_deg' ) ?? ( pick( sunRaw, 'angle_rad' ) !== undefined ? pick( sunRaw, 'angle_rad' ) * 180 / Math.PI : 0.526 ),
	};

	// --- lightmaps -----------------------------------------------------------------------------
	// ONE RGBM range for every lightmap path (schema: textures.<key>.rgbm_range, 64 at Gate 0).
	// A missing value is reported, because silently using another number is a brightness error.
	const textures = pick( raw, 'textures' ) || {};
	let rgbmFound;
	for ( const [ k, v ] of Object.entries( textures ) ) {
		if ( k.includes( 'lightmap' ) && v && v.rgbm_range ) { rgbmFound = v.rgbm_range; break; }
	}
	// manifest v2 carries the scene-wide value in lightmap_encoding.rgbm_range (QA-11c-3): use it before any default.
	if ( rgbmFound === undefined && raw.lightmap_encoding && raw.lightmap_encoding.rgbm_range ) rgbmFound = raw.lightmap_encoding.rgbm_range;
	const rgbmRange = def( rgbmFound, 7.0, 'lightmap rgbm_range (no textures.*lightmap*.rgbm_range or lightmap_encoding.rgbm_range in the manifest)' );

	// lightmap_scale: the Cycles colour-off diffuse pass is irradiance/pi and three's lightMap path
	// divides by pi again in BRDF_Lambert, so the manifest carries the compensating factor (pi).
	const lightmapScale = def( pick( raw, 'lightmap_scale', 'lightmaps.scale', 'view.lightmap_scale', 'textures.lightmap_scale' ),
		1.0, 'lightmap_scale (absent: the decoded lightmap is used as-is)' );

	// Accepted shapes: {lightmaps:[{match|object|mesh|material, url, encoding, intensity}]}
	//                  {assets:[{name, lightmap:{url, encoding}}]}
	const lightmaps = [];
	// v4 (`pfa-phase6/4`) makes `lightmaps` an OBJECT ({mode, scale, uv, assets, slots,
	// vertex_irradiance}); the older shapes are arrays.  Iterating the object with for..of throws, so
	// the v4 block is parsed further down (`gate3`) and this loop only ever sees an array.
	const lightmapsRaw = pick( raw, 'lightmaps' );
	for ( const lm of ( Array.isArray( lightmapsRaw ) ? lightmapsRaw : [] ) ) {
		lightmaps.push( {
			match: lm.match ?? lm.object ?? lm.mesh ?? lm.material ?? lm.name,
			matchKind: lm.material ? 'material' : 'object',
			url: resolveUrl( baseUrl, lm.url || lm.path || lm.file ),
			encoding: lm.encoding || 'linear',
			intensity: lm.intensity ?? 1.0,
			rgbmMaxRange: lm.rgbm_max_range ?? lm.max_range ?? rgbmRange,
		} );
	}
	const assetsRaw = pick( raw, 'assets' ) || [];
	const assetList = Array.isArray( assetsRaw )
		? assetsRaw : Object.entries( assetsRaw ).map( ( [ name, a ] ) => ( { name, ...a } ) );
	const reservations = {};
	for ( const a of assetList ) {
		const lm = a.lightmap;
		if ( ! lm ) continue;
		// manifest v2 states a PLAN, not a texture: {mode:'slot', pool, atlas, slot, uv2_offset,
		// uv2_scale} reserves an atlas cell, {mode:'asset', size} an own map, {mode:'none'} nothing.
		// None of them exists before the Gate 3 bake, so they are counted per mode, not warned about.
		if ( typeof lm === 'object' && lm.mode && ! lm.path && ! lm.url && ! lm.file ) {
			reservations[ lm.mode ] = ( reservations[ lm.mode ] || 0 ) + 1;
			continue;
		}
		// schema pfa-phase6-gate0/1: assets[].lightmap is a KEY into `textures`, not a URL.  Resolving
		// it as a URL would 404 and, worse, skip the in-glb emissive path and leave the lightmap
		// rendering as full-bright emissive.  A texture entry carries path, encoding and rgbm_range.
		const tex = ( typeof lm === 'string' ) ? textures[ lm ] : lm;
		if ( typeof lm === 'string' && ! tex ) { notes.push( `asset ${a.name}: lightmap key "${lm}" is not in textures, ignored` ); continue; }
		const url = resolveUrl( baseUrl, tex.path || tex.url || tex.file );
		if ( ! url ) { notes.push( `asset ${a.name}: lightmap "${lm}" has no path, ignored` ); continue; }
		lightmaps.push( {
			match: a.name ?? a.object,
			matchKind: 'object',
			url,
			encoding: /rgbm/i.test( tex.encoding || '' ) ? 'rgbm' : ( tex.encoding === 'sRGB' ? 'srgb' : 'linear' ),
			intensity: tex.intensity ?? 1.0,
			rgbmMaxRange: tex.rgbm_range ?? tex.rgbm_max_range ?? rgbmRange,
		} );
	}

	if ( Object.keys( reservations ).length )
		notes.push( `lightmap reservations for the Gate 3 bake, no texture yet: `
			+ Object.entries( reservations ).map( ( [ m, n ] ) => `${n} mode "${m}"` ).join( ', ' ) );

	// --- materials: the Gate 2 PBR texture sets (manifest v3 `pfa-phase6/3`) --------------------
	// The contract is export/README.md "manifest.json v3 — the contract with the viewer at Gate 2":
	//   materials.mode                "pbr" | "grey"            (the viewer switches on this string)
	//   materials.uv                  "TEXCOORD_0" — every PBR map rides UV1
	//   materials.colorspace          { albedo: "srgb", roughness|normal|occlusion: "linear" }
	//   materials.sets[<glb material name>] = {
	//       job, cls, src_material, size, uv1_in_glb,
	//       albedo:    { texture: <key into textures.gate2.files> | null, factor: [r,g,b] },
	//       roughness: { texture, factor }, normal: { texture, scale },
	//       metallic:  { texture: null, constant: true, factor }, occlusion: { texture } }
	// Rules honoured here: `texture` is a KEY, never a path (rule 1); `texture: null` with a factor
	// IS the map (rule 2); `factor` is the map's mean, used before the texture streams in and left at
	// 1.0/white afterwards, never multiplied into the texture (rule 3); albedo sRGB, the rest linear
	// (rule 4); `uv1_in_glb: false` (the ten backdrop groups) means factors only until env.glb is
	// re-exported with the UV1 the bake used.  Older/looser shapes (a bare path, {path}, per_material)
	// still parse, so the Gate 0/1 fixtures and the smoke manifest keep working.
	const MAP_KEYS = {
		map: [ 'albedo', 'base_color', 'basecolor', 'base_colour', 'diffuse', 'colour', 'color', 'map' ],
		roughnessMap: [ 'roughness', 'rough', 'roughness_map' ],
		normalMap: [ 'normal', 'normal_map', 'nrm', 'tangent_normal' ],
		metalnessMap: [ 'metallic', 'metalness', 'metal' ],
		aoMap: [ 'occlusion', 'ao', 'ambient_occlusion' ],
	};
	const SRGB_SLOT = { map: 'albedo', roughnessMap: 'roughness', normalMap: 'normal', metalnessMap: 'metallic', aoMap: 'occlusion' };
	const SRGB_DEFAULT = { map: true, roughnessMap: false, normalMap: false, metalnessMap: false, aoMap: false };
	const matRoot = pick( raw, 'materials', 'material_textures', 'pbr' ) || {};
	const materialsMode = ( typeof matRoot === 'object' && ( matRoot.mode || matRoot.materials_mode ) ) || null;
	const csDeclared = ( typeof matRoot === 'object' && matRoot.colorspace ) || {};
	const setsRaw = ( typeof matRoot === 'object'
		&& ( pick( matRoot, 'sets', 'per_material', 'materials', 'entries' )
			|| ( ! matRoot.mode && Object.keys( matRoot ).length ? matRoot : null ) ) )
		|| pick( raw, 'textures.per_material', 'textures.materials' ) || {};
	// Texture KEYS resolve through textures.gate2.files (Gate 2) and then through the Gate 1 list,
	// because an ORN occlusion map is carried unchanged from Gate 1 (`orn_<proto>_ao`).
	const texG2 = pick( raw, 'textures.gate2' ) || {};
	const filesG2 = ( texG2.files && typeof texG2.files === 'object' && ! Array.isArray( texG2.files ) ) ? texG2.files : {};
	const dirG2 = texG2.ktx2_dir || '';
	// v4 adds textures.gate3 (lightmaps, slot atlases, impostor atlases) with the same shape.
	const texG3 = pick( raw, 'textures.gate3' ) || {};
	const filesG3 = ( texG3.files && typeof texG3.files === 'object' && ! Array.isArray( texG3.files ) ) ? texG3.files : {};
	const dirG3 = texG3.ktx2_dir || '';
	const filesG1 = pick( raw, 'textures.files' );
	const dirG1 = pick( raw, 'textures.ktx2_dir' ) || '';
	const joinDir = ( dir, p ) => resolveUrl( baseUrl, ( dir && ! p.startsWith( '/' ) ) ? `${String( dir ).replace( /\/$/, '' )}/${p}` : p );
	const unresolvedKeys = [];
	/** A texture reference: a KEY into textures.gate3/gate2.files (v4/v3) or a path (older shapes). */
	const resolveTexture = ( ref ) => {
		if ( ! ref || typeof ref !== 'string' ) return null;
		const g3 = filesG3[ ref ];
		if ( g3 ) return { url: joinDir( dirG3, g3.path || `${ref}.ktx2` ), meta: g3 };
		const g2 = filesG2[ ref ];
		if ( g2 ) return { url: joinDir( dirG2, g2.path || `${ref}.ktx2` ), meta: g2 };
		if ( Array.isArray( filesG1 ) ) {
			const hit = filesG1.find( n => n === ref || n === `${ref}.ktx2` || ( typeof n === 'string' && n.startsWith( `${ref}.` ) ) );
			if ( hit ) return { url: joinDir( dirG1, hit ), meta: null };
		}
		if ( /\.(ktx2|png|jpg|jpeg|webp|exr|hdr)(\?.*)?$/i.test( ref ) ) return { url: joinDir( dirG2 || dirG1 || pick( raw, 'textures.ktx2_dir' ) || '', ref ), meta: filesG2[ ref.replace( /\.[^.]+$/, '' ) ] || null };
		unresolvedKeys.push( ref );
		return null;
	};
	const materialSets = {};
	const csFallbacks = [];
	let mapCount = 0, setBytes = 0, constantMaps = 0, noUv1 = 0, inGlbMaps = 0;
	for ( const [ name, entry ] of Object.entries( typeof setsRaw === 'object' && setsRaw ? setsRaw : {} ) ) {
		if ( ! entry || typeof entry !== 'object' ) continue;
		const src = entry.maps && typeof entry.maps === 'object' ? entry.maps : entry;
		const uv1 = entry.uv1_in_glb !== false;
		if ( ! uv1 ) noUv1 ++;
		const set = {
			name, maps: {}, factors: {}, uv1InGlb: uv1,
			job: entry.job ?? null, cls: entry.cls ?? null, srcMaterial: entry.src_material ?? null,
			size: entry.size ?? null, uv: matRoot.uv ?? entry.uv ?? src.uv ?? 'TEXCOORD_0',
			wrap: entry.wrap ?? src.wrap ?? null,
		};
		for ( const [ slot, aliases ] of Object.entries( MAP_KEYS ) ) {
			let v;
			for ( const a of aliases ) { if ( src[ a ] !== undefined && src[ a ] !== null ) { v = src[ a ]; break; } }
			if ( v === undefined ) continue;
			const o = ( typeof v === 'object' && v ) ? v : { path: v };
			// v3: `factor` is the baked mean — the value to use before (and instead of) the texture.
			if ( o.factor !== undefined && o.factor !== null ) set.factors[ slot ] = o.factor;
			if ( slot === 'normalMap' && o.scale !== undefined && o.scale !== null ) set.normalScale = o.scale;
			const hasTextureKey = Object.prototype.hasOwnProperty.call( o, 'texture' );
			const ref = hasTextureKey ? o.texture : ( o.path || o.url || o.file || o.ktx2 );
			// rule 2: a constant IS the map.  `in_glb: true` (the ORN occlusion) means the glb already
			// carries it and the viewer must load nothing.
			if ( ! ref ) { if ( o.in_glb === true ) inGlbMaps ++; else if ( hasTextureKey ) constantMaps ++; continue; }
			if ( ! uv1 ) continue;                                                   // rule: factors only, no UV1 in the glb
			const res = resolveTexture( ref );
			if ( ! res ) continue;
			const declared = ( o.colorspace ?? o.color_space ?? o.colour_space ?? o.encoding
				?? ( res.meta && res.meta.colorspace ) ?? csDeclared[ SRGB_SLOT[ slot ] ] ?? null );
			let srgb;
			if ( declared === null || declared === undefined ) { srgb = SRGB_DEFAULT[ slot ]; csFallbacks.push( `${name}.${slot}=${srgb ? 'sRGB' : 'linear'}` ); }
			else srgb = /srgb|s-rgb|colou?r$/i.test( String( declared ) ) && ! /non-?colou?r|linear|data|raw/i.test( String( declared ) );
			const bytes = o.bytes ?? o.size_bytes ?? ( res.meta && res.meta.bytes ) ?? null;
			// v5: which tier this map arrives in, and the low-resolution stand-in an earlier tier
			// ships for it (files[<path>].lo).  Both are null at v4, where every map is tier 0.
			const fileRow = tiers.files.get( res.url ) || null;
			set.maps[ slot ] = { url: res.url, srgb, declared, bytes,
				tier: tierForUrl( tiers, res.url, Number.isFinite( res.meta && res.meta.tier ) ? res.meta.tier : 0 ),
				lo: fileRow && fileRow.lo ? { ...fileRow.lo, srgb } : null,
				key: hasTextureKey ? ref : null, w: res.meta && res.meta.w, h: res.meta && res.meta.h,
				residentMb: res.meta && res.meta.resident_mb };
			mapCount ++; setBytes += bytes || 0;
		}
		const aliasRaw = entry.materials ?? entry.applies_to ?? entry.material_names ?? entry.material ?? entry.group_materials;
		set.aliases = ( Array.isArray( aliasRaw ) ? aliasRaw : ( typeof aliasRaw === 'string' ? [ aliasRaw ] : [] ) ).filter( x => typeof x === 'string' );
		if ( Object.keys( set.maps ).length || Object.keys( set.factors ).length ) materialSets[ name ] = set;
	}
	// --- materials.detail: the shared object-space tiling sets (QA-12-1) -----------------------
	// The Phase 5 concrete grain comes from a Bump with Distance 0.015 m, which no unique atlas can
	// carry (its texels are 3.8-11.8 cm), so the bake ships the five tiling sets Phase 5 itself uses
	// and the viewer re-creates the layer: albedo x (detail albedo / its own mean), roughness
	// likewise, the detail normal blended over the baked one.  `texture` here is a key too; the
	// files are PNGs under `detail/` next to the manifest (textures.gate2.detail_files has the
	// bytes but no path, detail.json has the paths).
	const detailRaw = ( typeof matRoot === 'object' && matRoot.detail ) || null;
	let detail = null;
	if ( detailRaw && detailRaw.sets ) {
		const dDir = detailRaw.dir || detailRaw.detail_dir || 'detail';
		// The set ships twice: a PNG under detail/ and a KTX2 next to the PBR atlases (1.33 MB
		// resident each, what textures.gate2.detail_files counts).  The PNG is used FIRST because
		// the layer divides by the map's own linear mean and only a decodable image can be measured
		// on the CPU; a compressed texture has no readable pixels.  The KTX2 (4x cheaper) becomes
		// the primary as soon as the manifest carries `mean_linear` per map — then nothing has to
		// be measured at run time.
		const detailFiles = ( texG2 && texG2.detail_files ) || {};
		const detailUrl = ( key, entry ) => {
			const given = entry && ( entry.path || entry.url );
			if ( given ) return { url: resolveUrl( baseUrl, given ), fallback: null };
			const png = resolveUrl( baseUrl, `${String( dDir ).replace( /\/$/, '' )}/${key}.png` );
			const ktx2 = ( detailFiles[ key ] && dirG2 ) ? joinDir( dirG2, `${key}.ktx2` ) : null;
			// KTX2 first (1 byte/texel against 4, and mips) whenever the manifest states the map's
			// mean: the layer divides the SAMPLED value by that mean, so the two must be in the same
			// space.  The Gate 2 KTX2 albedos carry DFD transfer 2 (sRGB) and the viewer sets
			// SRGBColorSpace on them, so the sample is decoded linear and `mean_linear` is the right
			// divisor.  Without a declared mean the PNG is used, because only a decodable image can
			// be measured on the CPU.
			const mean = entry && ( entry.mean_linear || entry.mean );
			if ( ktx2 && Array.isArray( mean ) ) return { url: ktx2, fallback: png };
			return { url: png, fallback: ktx2 };
		};
		const dSets = {};
		let dMaps = 0;
		for ( const [ name, set ] of Object.entries( detailRaw.sets ) ) {
			const maps = {};
			for ( const [ slot, key ] of [ [ 'map', 'albedo' ], [ 'roughnessMap', 'roughness' ], [ 'normalMap', 'normal' ] ] ) {
				const e = ( set.maps || set )[ key ];
				if ( ! e ) continue;
				const ref = typeof e === 'string' ? e : e.texture;
				if ( ! ref ) continue;
				const cs = ( typeof e === 'object' && e.colorspace ) || ( key === 'albedo' ? 'srgb' : 'linear' );
				const u = detailUrl( ref, typeof e === 'object' ? e : null );
				const declaredMean = ( typeof e === 'object' && ( e.mean_linear || e.mean ) ) || null;
				const declaredStd = ( typeof e === 'object' && ( e.std_linear || e.std ) ) || null;
				maps[ slot ] = { url: u.url, fallback: u.fallback, key: ref,
					meanLinear: Array.isArray( declaredMean ) ? declaredMean : null,
					stdLinear: Array.isArray( declaredStd ) ? declaredStd : null,
					srgb: /srgb/i.test( cs ), px: ( typeof e === 'object' && e.px ) || detailRaw.ship_px || 1024,
					bytes: detailFiles[ ref ] ? detailFiles[ ref ].bytes : null,
					residentMb: detailFiles[ ref ] ? detailFiles[ ref ].resident_mb : null };
				dMaps ++;
			}
			dSets[ name ] = { name, maps, tileM: set.tile_m ?? null };
		}
		// per_group is keyed by the GLB material name (authoritative); per_material by the Phase 5
		// source material name, matched through the same candidate keys as the PBR sets.
		const rule = ( r ) => ( ! r ? null : { set: r.set, scale: r.object_scale, tileM: r.tile_m,
			mmPerTexel: r.mm_per_texel, coordSpace: r.coord_space || 'object' } );
		const perGroup = {}, groupExtras = [];
		for ( const [ mat, entry ] of Object.entries( detailRaw.per_group || {} ) ) {
			const rules = Object.entries( entry ).map( ( [ src, r ] ) => ( { src, ...rule( r ) } ) ).filter( r => r.set && dSets[ r.set ] );
			if ( ! rules.length ) continue;
			// A merged group lists several source materials with different sets; one material can
			// carry one, so the FIRST is used and the others are reported.
			perGroup[ mat ] = rules[ 0 ];
			if ( rules.length > 1 ) groupExtras.push( `${mat}: ${rules.map( r => r.src ).join( ' + ' )} -> ${rules[ 0 ].set}` );
		}
		const perMaterial = {};
		for ( const [ src, r ] of Object.entries( detailRaw.per_material || {} ) ) {
			const v = rule( r );
			if ( v && dSets[ v.set ] ) perMaterial[ src ] = { src, ...v };
		}
		detail = { mode: detailRaw.mode || null, shipPx: detailRaw.ship_px || 1024,
			bumpDistanceM: detailRaw.bump_distance_m ?? null, apply: detailRaw.apply || null,
			sets: dSets, perGroup, perMaterial, maps: dMaps };
		notes.push( `materials.detail: ${Object.keys( dSets ).length} tiling set(s), ${dMaps} maps, `
			+ `${Object.keys( perGroup ).length} glb material rule(s) + ${Object.keys( perMaterial ).length} source-material rule(s), `
			+ `mode "${detail.mode}", bump distance ${detail.bumpDistanceM} m` );
		if ( groupExtras.length ) notes.push( `detail: ${groupExtras.length} merged group(s) list more than one source material, the first is used: ${groupExtras.join( '; ' )}` );
	}

	const materials = {
		mode: materialsMode,
		detail,
		sets: materialSets,
		count: Object.keys( materialSets ).length,
		maps: mapCount,
		constantMaps,
		inGlbMaps,
		withoutUv1: noUv1,
		declaredBytes: setBytes,
		budget: pick( raw, 'budget' ) || null,
		gate2Textures: { dir: dirG2, files: Object.keys( filesG2 ).length,
			bytes: texG2.bytes ?? null, residentMb: texG2.resident_mb ?? null },
	};
	if ( materials.count ) {
		notes.push( `materials: ${materials.count} set(s), ${mapCount} textures`
			+ ( constantMaps ? `, ${constantMaps} constant map(s) shipped as a factor` : '' )
			+ ( inGlbMaps ? `, ${inGlbMaps} map(s) already in the glb (in_glb, nothing loaded)` : '' )
			+ ( noUv1 ? `, ${noUv1} set(s) with uv1_in_glb false (factors only)` : '' )
			+ ( setBytes ? `, ${( setBytes / 1e6 ).toFixed( 1 )} MB declared` : ', no declared bytes (HEAD)' )
			+ `, mode "${materialsMode || '(unstated)'}"` );
		if ( csFallbacks.length ) notes.push( `colour space defaulted on ${csFallbacks.length} map(s) (manifest states none): ${csFallbacks.slice( 0, 6 ).join( ', ' )}${csFallbacks.length > 6 ? ' …' : ''}` );
		if ( unresolvedKeys.length ) notes.push( `${unresolvedKeys.length} texture key(s) not in textures.gate2.files or the Gate 1 list, skipped: ${[ ...new Set( unresolvedKeys ) ].slice( 0, 6 ).join( ', ' )}` );
	} else if ( materialsMode ) {
		notes.push( `materials.mode "${materialsMode}" but no per-material texture set was recognised` );
	}


	// --- Gate 3 (manifest v4 `pfa-phase6/4`): baked lightmaps, slot atlases, impostors, probe ----
	// export/README.md "manifest.json v4" is the contract.  The one rule that governs every map here:
	//     irradiance = decode(texel) * lightmaps.scale          (scale = pi, unchanged since Gate 0)
	// with `decode` chosen by the texture's own `encode`, NEVER guessed:
	//     rgbm8  -> rgb = t.rgb * t.a * range      (lossless KTX2 only)
	//     gamma2 -> rgb = t.rgb * t.rgb * range    (UASTC/ASTC, the shipped default)
	// `range` is per texture and is not 64 by default.  Two things the viewer must honour:
	//   * `uv2_in_glb: false` — the glb's UV2 is NOT the layout this map was baked on.  There is no
	//     factor fallback for a lightmap, so the asset either takes the `_gate1_layout` twin (baked on
	//     the frozen Gate 1 UV2, where the bake shipped one) or takes NO lightmap at all.
	//   * `vertex_irradiance.in_glb: false` — the near trees' COLOR_0 is not in env.glb yet; they stay
	//     on the environment path and their irradiance must come from `sky.diffuse`, not `sky.glossy`.
	const g3 = ( lightmapsRaw && typeof lightmapsRaw === 'object' && ! Array.isArray( lightmapsRaw )
		&& lightmapsRaw.assets ) ? lightmapsRaw : null;
	let gate3 = null;
	if ( g3 ) {
		const g3notes = [];
		const scale = g3.scale ?? lightmapScale;
		const encodeOf = ( variant, meta ) => {
			const e = ( meta && meta.encode ) || variant;
			return /rgbm/i.test( e ) ? 'rgbm8' : ( /gamma2/i.test( e ) ? 'gamma2' : String( e ) );
		};
		/** One lightmap entry -> { url, encode, range, variant } or null (with a reason). */
		const lmTexture = ( entry, what ) => {
			if ( ! entry || ! entry.textures ) return null;
			const want = entry.default || 'gamma2';
			const key = entry.textures[ want ] ?? entry.textures.gamma2 ?? entry.textures.rgbm8;
			const variant = entry.textures[ want ] ? want : ( entry.textures.gamma2 ? 'gamma2' : 'rgbm8' );
			if ( ! key ) { g3notes.push( `${what}: no texture key in the manifest` ); return null; }
			const res = resolveTexture( key );
			if ( ! res ) { g3notes.push( `${what}: texture key "${key}" is not in textures.gate3.files` ); return null; }
			const range = entry.range ?? ( res.meta && res.meta.range );
			if ( range === undefined || range === null ) { g3notes.push( `${what}: no range, skipped (a defaulted range is a brightness error)` ); return null; }
			return { url: res.url, textureKey: key, variant, encode: encodeOf( variant, res.meta ), range,
				tier: tierForUrl( tiers, res.url, 0 ),
				bytes: ( res.meta && res.meta.bytes ) ?? null, residentMb: ( res.meta && res.meta.resident_mb ) ?? null,
				w: res.meta && res.meta.w, h: res.meta && res.meta.h };
		};

		// own-map assets, keyed by the glb OBJECT name.  `_gate1_layout` is not an asset: it is the
		// frozen-layout twin of the assets whose UV2 was re-laid at Gate 3.
		const frozen = ( g3.assets && g3.assets._gate1_layout ) || {};
		const ownMaps = {};
		// BOTH candidates are resolved up front and the choice is made by `uv2_in_glb`, because that
		// flag moves: the export re-packs the glbs with the re-laid UV2 faster than the bake rewrites
		// the manifest, and `export/out/gate3/uv2_relay_status.json` is the live truth
		// (`selectOwnMap` below is re-run against it at load time).
		for ( const [ name, entry ] of Object.entries( g3.assets || {} ) ) {
			if ( name.startsWith( '_' ) ) continue;
			ownMaps[ name ] = {
				name, size: entry.size ?? null,
				uv2InGlb: entry.uv2_in_glb !== false,
				uv2Declared: entry.uv2_in_glb !== false,
				cmPerTexel: entry.cm_per_texel ?? null,
				relaid: entry.uv2_source === 'gate3_relaid',
				gate3Tex: lmTexture( entry, `lightmaps.assets.${name}` ),
				frozenTex: frozen[ name ] ? lmTexture( frozen[ name ], `lightmaps.assets._gate1_layout.${name}` ) : null,
				frozenCmPerTexel: frozen[ name ] ? ( frozen[ name ].cm_per_texel ?? null ) : null,
			};
			selectOwnMap( ownMaps[ name ] );
		}
		let blockedNoUv2 = Object.values( ownMaps ).filter( a => a.blocked ).length;
		let frozenUsed = Object.values( ownMaps ).filter( a => a.layout === 'gate1_frozen' && a.url ).length;
		// per-instance slot atlases (the user's option (c)).  `orn_slots` carries the per-object
		// offset/scale; `lightmaps.slots.atlases` names which texture each (pool, atlas) is.
		const atlasRaw = ( g3.slots && g3.slots.atlases ) || {};
		const atlases = {};
		for ( const [ key, a ] of Object.entries( atlasRaw ) ) {
			const tex = lmTexture( a, `lightmaps.slots.atlases.${key}` );
			atlases[ key ] = { key, pool: a.pool, atlas: a.atlas, atlasPx: a.atlas_px ?? null,
				slotPx: a.slot_px ?? null, gutterPx: a.gutter_px ?? null, usablePx: a.usable_px ?? null,
				uv2Scale: a.uv2_scale ?? null, slotsFilled: a.slots_filled ?? null, ...( tex || {} ) };
		}
		const byPoolAtlas = {};
		for ( const a of Object.values( atlases ) ) byPoolAtlas[ `${a.pool}/${a.atlas}` ] = a;
		const slotsRaw = pick( raw, 'orn_slots' ) || {};
		const slots = {};                       // glb object name -> { atlasKey, offset:[u,v], scale }
		let slotsNoAtlas = 0;
		for ( const [ pool, list ] of Object.entries( slotsRaw ) ) {
			if ( ! Array.isArray( list ) ) continue;
			for ( const s of list ) {
				const a = byPoolAtlas[ `${pool}/${s.atlas}` ];
				if ( ! a || ! a.url ) { slotsNoAtlas ++; continue; }
				slots[ s.object ] = { object: s.object, pool, atlasKey: a.key,
					offset: s.uv2_offset, scale: s.uv2_scale ?? a.uv2Scale };
			}
		}
		// the near trees' per-vertex irradiance: a hand-off, not a texture, and `in_glb` says whether
		// the exporter has written it as COLOR_0 yet.
		const vi = g3.vertex_irradiance || null;
		const ii = g3.instance_irradiance || null;

		// impostors (item 2) and the mirrored hero probe (item 3) are parsed here so one place knows
		// the v4 shape; the viewer modules consume them.
		const impRaw = pick( raw, 'impostors' ) || null;
		let impostors = null;
		if ( impRaw && impRaw.prototypes ) {
			const protos = {};
			let protosOk = true;
			for ( const [ name, p ] of Object.entries( impRaw.prototypes ) ) {
				const alb = resolveTexture( p.albedo ), nd = resolveTexture( p.normal_depth );
				if ( ! alb || ! nd ) { g3notes.push( `impostor ${name}: atlas key missing from textures.gate3.files` ); continue; }
				// The geometry fields are the Gate 3 restatement: heights are measured from the
				// prototype's OWN z = 0 (the plane `trunk_base` maps to), NOT from the bbox bottom.
				// `base_z_m` is 0 for 14 of the 16 but -2.6748 m / -0.7183 m on the two willows,
				// whose fronds hang below the trunk base; dividing by bbox[2] there made those
				// impostors 19 % / 6 % too small and lifted them off their trunks.
				// 6c C2: the 2K albedo variant, if the export shipped one for this prototype.  It is
				// resolved the same way and never constructed from the 1K name.
				const alb2k = p.albedo_2k ? resolveTexture( p.albedo_2k ) : null;
				protos[ name ] = { name, albedo: alb.url, normalDepth: nd.url,
					albedo2k: alb2k ? alb2k.url : null,
					bytes2k: ( alb2k && alb2k.meta && alb2k.meta.bytes ) || 0,
					range: p.range ?? null, bbox: p.bbox_m || null, radius: p.radius_m ?? null,
					baseZ: p.base_z_m ?? 0, centreZ: p.centre_z_m ?? null,
					heightAboveBase: p.height_above_base_m ?? null,
					centreAboveBase: p.centre_above_base_m ?? null, depthRange: p.depth_range_m ?? null,
					alphaCoverage: p.alpha_coverage ?? null,
					bytes: ( ( alb.meta && alb.meta.bytes ) || 0 ) + ( ( nd.meta && nd.meta.bytes ) || 0 ) };
				if ( ! ( protos[ name ].heightAboveBase > 0 ) || ! ( protos[ name ].radius > 0 ) || ! ( protos[ name ].range > 0 ) )
					g3notes.push( `impostor ${name}: height_above_base_m / radius_m / range missing or not positive - it cannot be placed` );
			}
			// Every geometric and encoding field is READ, never assumed: the Gate 3 review is
			// re-measuring `centre_above_base_m` / `bbox_m` from the trunk base and restating the
			// depth encode as `depth_from_centre_m = (a - 0.5) * depth_range_m`.  `encode` and
			// `frame_lookup` / `frame_uv` are carried verbatim so the impostor material can assert
			// the contract it was written against instead of silently drifting from it.
			// NO SILENT DEFAULTS.  grid/frame_px/inner_px/gutter_px/atlas_px all go straight into the
			// frame lookup; a missing one produced NaN UVs and a blank or garbage tree rather than an
			// error.  The block is refused instead, and the viewer says which field was missing.
			const geomFields = { grid: impRaw.grid, frame_px: impRaw.frame_px, inner_px: impRaw.inner_px,
				gutter_px: impRaw.gutter_px, atlas_px: impRaw.atlas_px };
			const missing = Object.entries( geomFields ).filter( ( [ , v ] ) => typeof v !== 'number' || ! ( v > 0 ) ).map( ( [ k ] ) => k );
			if ( missing.length ) {
				g3notes.push( `impostors REFUSED: manifest.impostors is missing ${missing.join( ', ' )}; `
					+ 'those fields go straight into the frame lookup and a default would make NaN UVs' );
				protosOk = false;
			}
			impostors = protosOk === false ? null : { encode: impRaw.encode || null, frameLookup: impRaw.frame_lookup || null,
				frameUv: impRaw.frame_uv || null, lighting: impRaw.lighting || null,
				mapping: impRaw.mapping || 'octahedral', grid: impRaw.grid,
				framePx: impRaw.frame_px, innerPx: impRaw.inner_px,
				gutterPx: impRaw.gutter_px, atlasPx: impRaw.atlas_px,
				unlit: impRaw.unlit !== false, prototypeMap: impRaw.prototype_map || {},
				// The 2K variant RE-STATES the atlas geometry (a 2048 px atlas of 170 px frames with
				// a 4 px gutter is not the 1K block x2), so it is read whole or not at all: a partial
				// block would be a frame lookup off by a texel row on every tree.
				variant2k: ( () => {
					const v = impRaw.variant_2k;
					if ( ! v ) return null;
					const g = { atlasPx: v.atlas_px, framePx: v.frame_px, gutterPx: v.gutter_px, innerPx: v.inner_px };
					const bad = Object.entries( g ).filter( ( [ , x ] ) => typeof x !== 'number' || ! ( x > 0 ) ).map( ( [ k ] ) => k );
					if ( bad.length ) { g3notes.push( `impostors variant_2k ignored: missing ${bad.join( ', ' )}` ); return null; }
					return g;
				} )(),
				prototypes: protos, count: Object.keys( protos ).length };
		}
		const probeRaw = pick( raw, 'probe' ) || null;
		let probe = null;
		if ( probeRaw && probeRaw.files ) {
			const dir = probeRaw.dir ? `${String( probeRaw.dir ).replace( /\/$/, '' )}/` : '';
			const faces = ( probeRaw.faces || [ 'px', 'nx', 'py', 'ny', 'pz', 'nz' ] ).map( ( f ) => {
				const e = probeRaw.files[ f ];
				const p = typeof e === 'string' ? e : ( e && ( e.hdr || e.path || e.exr ) );
				return p ? resolveUrl( baseUrl, `${dir}${p}` ) : null;
			} );
			if ( faces.every( Boolean ) ) probe = { faces, order: probeRaw.faces, sizePx: probeRaw.size_px ?? null,
				station: probeRaw.station || null, positionGltf: probeRaw.position_gltf || null };
			else g3notes.push( 'probe: not all six faces are in the manifest, ignored' );
		}

		gate3 = { mode: g3.mode || 'baked', scale, uv: g3.uv || 'TEXCOORD_1',
			ownMaps, ownCount: Object.values( ownMaps ).filter( m => m.url ).length,
			blockedNoUv2, frozenUsed, atlases, slots, slotCount: Object.keys( slots ).length, slotsNoAtlas,
			vertexIrradiance: vi ? { inGlb: vi.in_glb === true, encode: vi.encode || 'gamma2',
				range: typeof vi.range === 'number' ? vi.range : null,
				// Which KEY the viewer read is not the same question as where the export derived the
				// number; both are reported, so a relay fallback can never be mistaken for the manifest.
				rangeFrom: typeof vi.range === 'number' ? 'manifest lightmaps.vertex_irradiance.range' : null,
				rangeSource: vi.range_source || null,
				attribute: vi.attribute || 'COLOR_0', meshes: vi.meshes_n ?? null } : null,
			// Gate 4 item 1c: one scene-linear rgb per SHRUB/REED PLACEMENT, delivered in the manifest
			// (in_glb false) and bound per glb NODE through `segments`, never per mesh - gltfpack merged
			// three `.001` single-placement meshes into their base mesh's node with the odd row INSIDE
			// the run (export/README.md item 31).
			instanceIrradiance: ii ? { inGlb: ii.in_glb === true, attribute: ii.attribute || '_IRRADIANCE',
				placements: ii.placements ?? null, meshesN: ii.meshes_n ?? null,
				rangeGlobal: ii.range_global ?? null, nodes: Array.isArray( ii.nodes ) ? ii.nodes : [],
				meshes: ii.meshes || {}, darkN: ( ii.dark && ii.dark.n ) || 0,
				glb: ( ( ii.order_source && ii.order_source.glb ) || 'env.glb' ).replace( /\.glb$/, '' ) } : null,
			impostors, probe, notes: g3notes };
		notes.push( `manifest v4 lightmaps: ${gate3.ownCount} own map(s) ready of ${Object.keys( ownMaps ).length}`
			+ ( frozenUsed ? `, ${frozenUsed} on the frozen Gate 1 layout` : '' )
			+ ( blockedNoUv2 ? `, ${blockedNoUv2} blocked (uv2_in_glb false, no fallback)` : '' )
			+ `; ${gate3.slotCount} per-instance slot(s) over ${Object.keys( atlases ).length} atlas(es)`
			+ `; scale ${scale.toFixed( 5 )}` );
		if ( impostors ) notes.push( `manifest v4 impostors: ${impostors.count} prototype(s), ${impostors.grid}x${impostors.grid} octahedral frames at ${impostors.framePx} px on a ${impostors.atlasPx} px atlas` );
		if ( gate3.vertexIrradiance && ! gate3.vertexIrradiance.inGlb )
			notes.push( `vertex irradiance for ${gate3.vertexIrradiance.meshes} near-tree mesh(es) is NOT in the glb (COLOR_0 pending the re-export): they stay on the environment path` );
		g3notes.forEach( n => notes.push( `gate3: ${n}` ) );
	}

	// --- Gate 1 extras: far-tree billboard quads, ORN atlas slots ------------------------------
	// `trees.far` is the Gate 3 impostor list: each entry is a prototype id, a height and a trunk base.
	// Until that bake exists the viewer draws one flat, explicitly tagged quad per entry.
	const treesRaw = pick( raw, 'trees', 'tree_lists', 'vegetation' ) || {};
	const farRaw = pick( raw, 'tree_far' ) || pick( treesRaw, 'far', 'billboards', 'far_list' ) || [];
	const treesFar = ( Array.isArray( farRaw ) ? farRaw : [] ).map( ( t ) => ( {
		prototype: t.prototype ?? t.proto ?? t.id ?? t.name ?? 'tree',
		id: t.billboard ?? null,
		height: t.height_m ?? t.height ?? t.h ?? 12,
		width: t.width_m ?? t.width ?? t.w ?? null,
		base: t.trunk_base ?? t.base ?? t.location_blender ?? t.location ?? t.position ?? null,
	} ) ).filter( t => Array.isArray( t.base ) && t.base.length === 3 );
	if ( farRaw.length && treesFar.length !== farRaw.length )
		notes.push( `tree_far: ${farRaw.length - treesFar.length} of ${farRaw.length} entries have no trunk base, skipped` );
	const nearRaw = pick( raw, 'tree_near' ) || pick( treesRaw, 'near', 'near_list' ) || [];
	// v2: orn_slots = { <pool>: [ {object, atlas, slot}, ... ] }.  Gate 1 has no atlas texture yet;
	// the viewer only reports the reservation so a Gate 3 regression is visible in the sidecar.
	const ornSlotsRaw = pick( raw, 'orn_slots', 'orn.slots', 'ornament.slots' ) || null;
	const ornSlots = ornSlotsRaw && typeof ornSlotsRaw === 'object' && ! Array.isArray( ornSlotsRaw )
		? Object.fromEntries( Object.entries( ornSlotsRaw ).map( ( [ pool, v ] ) => [ pool, {
			entries: Array.isArray( v ) ? v.length : null,
			atlases: Array.isArray( v ) ? new Set( v.map( e => e.atlas ) ).size : null,
		} ] ) )
		: ornSlotsRaw;

	const out = {
		tiers,
		raw, baseUrl, glb, glbs, stations, lut, exposure, sun, lightmaps, notes, rgbmRange, lightmapScale, materials,
		treesFar, treesNearCount: Array.isArray( nearRaw ) ? nearRaw.length : 0, ornSlots, gate3,
		// `assets` is the identity the glb lost: gltfpack -mi drops every node and mesh name, so the
		// only way back from a drawn mesh to a manifest asset is its world bounding-box CENTRE
		// (`location_blender`, Blender Z-up).  Kept as a plain map for the lightmap matcher.
		assets: ( pick( raw, 'assets' ) && ! Array.isArray( raw.assets ) ) ? raw.assets : null,
		instancing: pick( raw, 'instancing' ) || null,
		schema: pick( raw, 'schema' ) || null,
		waterZ: def( pick( raw, 'water.viewer_y', 'water.water_z', 'water_z', 'waterZ', 'scene.water_z' ), WATER_Z, 'water_z' ),
		sky: { camera: skyCamera, glossy: skyGlossy, diffuse: skyDiffuse, rotationDeg: skyRotationDeg },
		frameSize: pick( raw, 'frame', 'render.frame' ) || { width: 1280, height: 720 },
	};
	if ( ! glbs.length ) notes.push( 'no glb in the manifest: test scene only' );
	return out;
}
