// Normalises export/out/<gate>/manifest.json (written by the bake engineer) into what the viewer needs,
// so a schema change there is absorbed in one place.  Every field that had to be defaulted is reported
// in `notes` and logged, because a silently defaulted exposure or sun vector makes parity meaningless.
import stationsFallback from './stations_blender.json';

// Generated by web/tools/dump_stations.py from scripts/common.py + scripts/qa_cameras.py (review carry
// 10): nothing here is hand-copied.  The manifest still wins over all of it at run time.
export const WATER_Z = stationsFallback.water_z;

function pick( obj, ...keys ) {
	for ( const k of keys ) {
		const v = k.split( '.' ).reduce( ( o, p ) => ( o == null ? o : o[ p ] ), obj );
		if ( v !== undefined && v !== null ) return v;
	}
	return undefined;
}

export function resolveUrl( base, url ) {
	if ( ! url ) return null;
	if ( /^(https?:)?\//.test( url ) ) return url;
	return new URL( url, base ).href;
}

/**
 * @param {object|null} raw  parsed manifest.json (null -> pure defaults, test-scene mode)
 * @param {string} baseUrl   absolute URL of the manifest, for relative asset paths
 */
export function normaliseManifest( raw, baseUrl ) {
	const notes = [];
	const def = ( value, fallback, what ) => {
		if ( value === undefined || value === null ) { notes.push( `defaulted ${what} = ${JSON.stringify( fallback )}` ); return fallback; }
		return value;
	};
	raw = raw || {};

	// --- geometry ------------------------------------------------------------------------------
	// schema pfa-phase6/2 ships ONE GLB PER CLASS (arch / orn / env / ground) loaded in the manifest's
	// order; pfa-phase6-gate0/1 shipped a single `glb`.  Both normalise to `glbs`, an ordered list of
	// { url, name, cls, bytes }.  `glb` stays as the first entry for anything that still reads it.
	const glbRaw = pick( raw, 'glb', 'files.glb', 'model' );
	const glbUrlOf = ( v ) => resolveUrl( baseUrl, typeof v === 'string' ? v : ( v?.path || v?.url || v?.file ) );
	const isGlbUrl = ( u ) => !! u && /\.(glb|gltf)(\?.*)?$/i.test( u );
	const glbEntry = ( v, key, i ) => {
		const url = glbUrlOf( v );
		if ( ! isGlbUrl( url ) ) return null;          // 'texture_source: ktx2' and prose notes are not files
		const o = ( typeof v === 'object' && v ) || {};
		return {
			url,
			name: url.split( '/' ).pop(),
			cls: o.class ?? o.cls ?? o.kind ?? key ?? `part_${i}`,
			bytes: o.bytes ?? o.size ?? o.byte_length ?? null,
			order: o.order ?? i,
		};
	};
	const listOf = ( v ) => {
		if ( ! v ) return [];
		if ( Array.isArray( v ) ) return v.map( ( e, i ) => glbEntry( e, null, i ) );
		if ( typeof v === 'object' ) {
			// A single glb object ({path, bytes, instanced_variant, ...}) is ONE file, not a map of
			// files: its sibling keys are metadata (gate0's `texture_source`, `instanced_variant`).
			if ( v.path || v.url || v.file ) return [ glbEntry( v, v.class ?? v.cls ?? null, 0 ) ];
			return Object.entries( v ).map( ( [ k, e ], i ) => glbEntry( e, k, i ) );
		}
		return [ glbEntry( v, null, 0 ) ];
	};
	// 'glb.per_class' is what export/gltf_pack.sh --gate1 actually writes:
	// glb.per_class = { arch:{path,bytes,…}, orn, env, ground } in load order.
	let glbs = listOf( pick( raw, 'glbs', 'glb.per_class', 'glb.parts', 'glb.files', 'glb.classes', 'files.glbs' ) ).filter( Boolean );
	if ( ! glbs.length ) glbs = listOf( glbRaw ).filter( Boolean );
	glbs.sort( ( a, b ) => a.order - b.order );
	glbs.forEach( ( g, i ) => { g.order = i; } );
	const glb = glbs.length ? glbs[ 0 ].url : null;
	if ( glbs.length > 1 ) notes.push( `${glbs.length} glbs, loaded in manifest order: ${glbs.map( g => `${g.cls}:${g.name}` ).join( ', ' )}` );

	// --- stations ------------------------------------------------------------------------------
	// schema pfa-phase6-gate0/1 keys stations by camera name with lens_mm / rotation_euler_xyz;
	// older/array shapes are accepted too.  Look-at targets are not in the manifest, so they are
	// taken from scripts/qa_cameras.py (stations_blender.json) by name purely as a cross-check.
	let rawStations = pick( raw, 'stations', 'cameras' );
	let stationList;
	const byName = new Map( stationsFallback.stations.map( s => [ s.name, s ] ) );
	// Keys 1-6 are the six scripts/qa_cameras.py stations BY NAME.  manifest v2 also carries cameras
	// that are not QA stations (CAM_flythrough), so key order must never decide the index: a camera
	// the generated list does not know is appended after 6, never inserted in front of the hero.
	const indexFor = ( s, i ) => s.index ?? byName.get( s.name )?.index ?? null;
	if ( rawStations && ! Array.isArray( rawStations ) && Object.keys( rawStations ).length ) {
		stationList = Object.entries( rawStations ).map( ( [ name, s ] ) => ( { ...s, name } ) );
	} else if ( rawStations && rawStations.length ) {
		stationList = rawStations.slice();
	} else {
		stationList = stationsFallback.stations;
		notes.push( 'stations: manifest had none, using scripts/qa_cameras.py fallback' );
	}
	let nextExtra = stationsFallback.stations.length + 1;
	const extras = [];
	stationList = stationList.map( ( s, i ) => {
		const idx = indexFor( s, i );
		if ( idx === null ) extras.push( s.name );
		return { ...s, index: idx === null ? nextExtra ++ : idx };
	} ).sort( ( a, b ) => a.index - b.index );
	if ( extras.length ) notes.push( `stations not in scripts/qa_cameras.py, indexed after 6: ${extras.join( ', ' )}` );
	const stations = stationList.map( ( s, i ) => {
		const ref = byName.get( s.name );
		return {
			index: s.index ?? i + 1,
			name: s.name ?? `station_${i + 1}`,
			location: s.location ?? s.loc,
			target: s.target ?? ref?.target ?? null,
			rotation_euler: s.rotation_euler_xyz ?? s.rotation_euler ?? s.rotation ?? null,
			matrix_world: s.matrix_world ?? s.matrix ?? null,
			lens: s.lens_mm ?? s.lens ?? 35,
			sensor_width: s.sensor_width_mm ?? s.sensor_width ?? 36,
			sensor_fit: s.sensor_fit ?? 'HORIZONTAL',
			shift_x: s.shift_x ?? 0,
			shift_y: s.shift_y ?? 0,
			clip_start: s.clip_start ?? 0.1,
			clip_end: s.clip_end ?? 5000,
			reference_photo: s.reference_photo ?? ref?.ref ?? null,
		};
	} );

	// --- colour --------------------------------------------------------------------------------
	const lutRaw = pick( raw, 'lut', 'colour.lut', 'color.lut' );
	const sh = ( typeof lutRaw === 'object' && lutRaw && typeof lutRaw.shaper === 'object' ) ? lutRaw.shaper : null;
	const lut = lutRaw ? {
		url: resolveUrl( baseUrl, typeof lutRaw === 'string' ? lutRaw : ( lutRaw.url || lutRaw.path || lutRaw.file ) ),
		size: ( typeof lutRaw === 'object' && ( lutRaw.size ?? lutRaw.lut_size ) ) || null,
		// schema pfa-phase6-gate0/1: lut.shaper = { min_ev, max_ev, pivot } means an AgX log2 shaper
		shaper: sh ? 'log2' : ( ( typeof lutRaw === 'object' && typeof lutRaw.shaper === 'string' ) ? lutRaw.shaper : null ),
		shaperMin: sh ? sh.min_ev : ( ( typeof lutRaw === 'object' && ( lutRaw.shaper_min ?? lutRaw.shaperMin ) ) ?? undefined ),
		shaperMax: sh ? sh.max_ev : ( ( typeof lutRaw === 'object' && ( lutRaw.shaper_max ?? lutRaw.shaperMax ) ) ?? undefined ),
		shaperPivot: sh ? ( sh.pivot ?? 0.18 ) : undefined,
		exposureOwner: ( typeof lutRaw === 'object' && lutRaw.exposure_applied_by ) || null,
	} : null;
	if ( ! lut ) notes.push( 'no LUT in the manifest: the display pass falls back to gamma 2.2 (NOT the Phase 5 look)' );

	// Exposure.  export/bake_lut.py pushes the identity Hald through Blender's OWN view transform AT
	// the scene's exposure, so a LUT from that bake ALREADY contains -2.833 EV and the pass multiplier
	// must stay 1.0.  An explicit exposure_multiplier wins; `includes_exposure: false` switches to 2^EV.
	let exposure = pick( raw, 'exposure_multiplier', 'exposure_scale', 'colour.exposure_multiplier', 'view.exposure_multiplier' );
	const ev = pick( raw, 'exposure_ev', 'view.exposure_ev', 'exposure', 'view.exposure', 'colour.exposure' );
	const lutHasExposure = pick( raw, 'lut.includes_exposure', 'view.lut.includes_exposure', 'colour.lut.includes_exposure' );
	if ( exposure === undefined ) {
		if ( lut && /viewer/i.test( lut.exposureOwner || '' ) && ev !== undefined ) {
			exposure = Math.pow( 2, ev );
			notes.push( `exposure: the LUT says exposure_applied_by "${lut.exposureOwner}", multiplier 2^${ev.toFixed( 4 )} = ${Math.pow( 2, ev ).toFixed( 5 )}` );
		} else if ( lutHasExposure === false && ev !== undefined ) { exposure = Math.pow( 2, ev ); notes.push( `exposure: LUT declares includes_exposure false, multiplier 2^${ev} = ${Math.pow( 2, ev ).toFixed( 5 )}` ); }
		else if ( lut ) { exposure = 1.0; notes.push( `exposure: multiplier 1.0 (the LUT carries the ${ev !== undefined ? ev.toFixed( 3 ) : '-2.833'} EV exposure)` ); }
		else if ( ev !== undefined ) { exposure = Math.pow( 2, ev ); notes.push( `exposure: no LUT, gamma fallback gets 2^${ev.toFixed( 3 )} = ${Math.pow( 2, ev ).toFixed( 5 )}` ); }
		else { exposure = 1.0; notes.push( 'exposure: absent, multiplier = 1' ); }
	}

	// --- sky -----------------------------------------------------------------------------------
	const sky = pick( raw, 'sky', 'world', 'environment' ) || {};
	// schema pfa-phase6-gate0/1: sky.camera / sky.glossy are objects { exr, hdr }.  The .hdr (RGBE) is
	// used: 3.6 MB vs 32 MB and enough range for a background and a PMREM source.
	const skyFile = ( v ) => ( typeof v === 'string' ? v : ( v && ( v.hdr || v.exr ) ) );
	const skyCamera = resolveUrl( baseUrl, skyFile( pick( sky, 'camera', 'background', 'camera_hdr', 'camera_exr' ) ) );
	const skyGlossy = resolveUrl( baseUrl, skyFile( pick( sky, 'glossy', 'specular', 'glossy_hdr', 'glossy_exr' ) ) );
	// Blender/manifest mapping: u = 0.5 + atan2(bx, by)/360.  With three (X,Y,Z) = blender (x, z, -y)
	// that is three's atan2(Z,X) + 90 deg, so the manifest's u is three's u + 0.25 and the environment
	// needs a quarter turn about Y.  three's backgroundRotation applies the INVERSE sense, so the value
	// is +90, measured: a sweep of 0 / 90 / 180 / -90 against the Cycles reference frame gives
	// mean |delta| over five sky boxes of 33.1 / 1.5 / 19.0 / 21.4 of 255.
	const skyRotationDeg = def( pick( sky, 'rotation_deg', 'rotation' ), 90,
		'sky.rotation_deg (+90 about Y; measured against the Cycles frame, 1.5/255)' );

	// --- sun (specular only; the diffuse is in the lightmaps) ----------------------------------
	// The manifest's `direction_blender` / `direction_gltf` is the direction the light TRAVELS, so the
	// DirectionalLight is placed at -direction * d.  An azimuth/elevation pair instead points TOWARD
	// the sun, so the light is placed at +direction * d.
	const sunRaw = pick( raw, 'sun', 'light.sun' ) || {};
	let toSunBlender = null;
	const travel = pick( sunRaw, 'direction_blender', 'direction', 'vector', 'dir' );
	const az = pick( sunRaw, 'azimuth', 'azimuth_deg' ), el = pick( sunRaw, 'elevation', 'elevation_deg' );
	if ( travel ) { toSunBlender = travel.map( v => - v ); notes.push( `sun: travel direction [${travel.map( v => v.toFixed( 3 ) )}] -> light placed opposite` ); }
	else if ( az !== undefined && el !== undefined ) {
		// scripts/common.sun_direction: azimuth clockwise from north, -X = north, +Y = east
		const a = az * Math.PI / 180, e = el * Math.PI / 180;
		toSunBlender = [ - Math.cos( a ) * Math.cos( e ), Math.sin( a ) * Math.cos( e ), Math.sin( e ) ];
		notes.push( `sun: direction from azimuth ${az} / elevation ${el}` );
	} else {
		const a = 118.5 * Math.PI / 180, e = 7.36 * Math.PI / 180;
		toSunBlender = [ - Math.cos( a ) * Math.cos( e ), Math.sin( a ) * Math.cos( e ), Math.sin( e ) ];
		notes.push( 'sun: absent, using the Phase 5 world (az 118.5, el 7.36)' );
	}
	const sun = {
		toSunBlender,
		irradiance: def( pick( sunRaw, 'energy_w_m2', 'irradiance', 'strength', 'energy' ), 67.3, 'sun.irradiance (W/m2, Phase 5 LIGHT_sun)' ),
		color: pick( sunRaw, 'color', 'colour' ) || [ 1, 1, 1 ],
		angleDeg: pick( sunRaw, 'angle_deg' ) ?? ( pick( sunRaw, 'angle_rad' ) !== undefined ? pick( sunRaw, 'angle_rad' ) * 180 / Math.PI : 0.526 ),
	};

	// --- lightmaps -----------------------------------------------------------------------------
	// ONE RGBM range for every lightmap path (schema: textures.<key>.rgbm_range, 64 at Gate 0).
	// A missing value is reported, because silently using another number is a brightness error.
	const textures = pick( raw, 'textures' ) || {};
	let rgbmFound;
	for ( const [ k, v ] of Object.entries( textures ) ) {
		if ( k.includes( 'lightmap' ) && v && v.rgbm_range ) { rgbmFound = v.rgbm_range; break; }
	}
	// manifest v2 carries the scene-wide value in lightmap_encoding.rgbm_range (QA-11c-3): use it before any default.
	if ( rgbmFound === undefined && raw.lightmap_encoding && raw.lightmap_encoding.rgbm_range ) rgbmFound = raw.lightmap_encoding.rgbm_range;
	const rgbmRange = def( rgbmFound, 7.0, 'lightmap rgbm_range (no textures.*lightmap*.rgbm_range or lightmap_encoding.rgbm_range in the manifest)' );

	// lightmap_scale: the Cycles colour-off diffuse pass is irradiance/pi and three's lightMap path
	// divides by pi again in BRDF_Lambert, so the manifest carries the compensating factor (pi).
	const lightmapScale = def( pick( raw, 'lightmap_scale', 'lightmaps.scale', 'view.lightmap_scale', 'textures.lightmap_scale' ),
		1.0, 'lightmap_scale (absent: the decoded lightmap is used as-is)' );

	// Accepted shapes: {lightmaps:[{match|object|mesh|material, url, encoding, intensity}]}
	//                  {assets:[{name, lightmap:{url, encoding}}]}
	const lightmaps = [];
	for ( const lm of pick( raw, 'lightmaps' ) || [] ) {
		lightmaps.push( {
			match: lm.match ?? lm.object ?? lm.mesh ?? lm.material ?? lm.name,
			matchKind: lm.material ? 'material' : 'object',
			url: resolveUrl( baseUrl, lm.url || lm.path || lm.file ),
			encoding: lm.encoding || 'linear',
			intensity: lm.intensity ?? 1.0,
			rgbmMaxRange: lm.rgbm_max_range ?? lm.max_range ?? rgbmRange,
		} );
	}
	const assetsRaw = pick( raw, 'assets' ) || [];
	const assetList = Array.isArray( assetsRaw )
		? assetsRaw : Object.entries( assetsRaw ).map( ( [ name, a ] ) => ( { name, ...a } ) );
	const reservations = {};
	for ( const a of assetList ) {
		const lm = a.lightmap;
		if ( ! lm ) continue;
		// manifest v2 states a PLAN, not a texture: {mode:'slot', pool, atlas, slot, uv2_offset,
		// uv2_scale} reserves an atlas cell, {mode:'asset', size} an own map, {mode:'none'} nothing.
		// None of them exists before the Gate 3 bake, so they are counted per mode, not warned about.
		if ( typeof lm === 'object' && lm.mode && ! lm.path && ! lm.url && ! lm.file ) {
			reservations[ lm.mode ] = ( reservations[ lm.mode ] || 0 ) + 1;
			continue;
		}
		// schema pfa-phase6-gate0/1: assets[].lightmap is a KEY into `textures`, not a URL.  Resolving
		// it as a URL would 404 and, worse, skip the in-glb emissive path and leave the lightmap
		// rendering as full-bright emissive.  A texture entry carries path, encoding and rgbm_range.
		const tex = ( typeof lm === 'string' ) ? textures[ lm ] : lm;
		if ( typeof lm === 'string' && ! tex ) { notes.push( `asset ${a.name}: lightmap key "${lm}" is not in textures, ignored` ); continue; }
		const url = resolveUrl( baseUrl, tex.path || tex.url || tex.file );
		if ( ! url ) { notes.push( `asset ${a.name}: lightmap "${lm}" has no path, ignored` ); continue; }
		lightmaps.push( {
			match: a.name ?? a.object,
			matchKind: 'object',
			url,
			encoding: /rgbm/i.test( tex.encoding || '' ) ? 'rgbm' : ( tex.encoding === 'sRGB' ? 'srgb' : 'linear' ),
			intensity: tex.intensity ?? 1.0,
			rgbmMaxRange: tex.rgbm_range ?? tex.rgbm_max_range ?? rgbmRange,
		} );
	}

	if ( Object.keys( reservations ).length )
		notes.push( `lightmap reservations for the Gate 3 bake, no texture yet: `
			+ Object.entries( reservations ).map( ( [ m, n ] ) => `${n} mode "${m}"` ).join( ', ' ) );

	// --- materials: the Gate 2 PBR texture sets (manifest v3 `pfa-phase6/3`) --------------------
	// The contract is export/README.md "manifest.json v3 — the contract with the viewer at Gate 2":
	//   materials.mode                "pbr" | "grey"            (the viewer switches on this string)
	//   materials.uv                  "TEXCOORD_0" — every PBR map rides UV1
	//   materials.colorspace          { albedo: "srgb", roughness|normal|occlusion: "linear" }
	//   materials.sets[<glb material name>] = {
	//       job, cls, src_material, size, uv1_in_glb,
	//       albedo:    { texture: <key into textures.gate2.files> | null, factor: [r,g,b] },
	//       roughness: { texture, factor }, normal: { texture, scale },
	//       metallic:  { texture: null, constant: true, factor }, occlusion: { texture } }
	// Rules honoured here: `texture` is a KEY, never a path (rule 1); `texture: null` with a factor
	// IS the map (rule 2); `factor` is the map's mean, used before the texture streams in and left at
	// 1.0/white afterwards, never multiplied into the texture (rule 3); albedo sRGB, the rest linear
	// (rule 4); `uv1_in_glb: false` (the ten backdrop groups) means factors only until env.glb is
	// re-exported with the UV1 the bake used.  Older/looser shapes (a bare path, {path}, per_material)
	// still parse, so the Gate 0/1 fixtures and the smoke manifest keep working.
	const MAP_KEYS = {
		map: [ 'albedo', 'base_color', 'basecolor', 'base_colour', 'diffuse', 'colour', 'color', 'map' ],
		roughnessMap: [ 'roughness', 'rough', 'roughness_map' ],
		normalMap: [ 'normal', 'normal_map', 'nrm', 'tangent_normal' ],
		metalnessMap: [ 'metallic', 'metalness', 'metal' ],
		aoMap: [ 'occlusion', 'ao', 'ambient_occlusion' ],
	};
	const SRGB_SLOT = { map: 'albedo', roughnessMap: 'roughness', normalMap: 'normal', metalnessMap: 'metallic', aoMap: 'occlusion' };
	const SRGB_DEFAULT = { map: true, roughnessMap: false, normalMap: false, metalnessMap: false, aoMap: false };
	const matRoot = pick( raw, 'materials', 'material_textures', 'pbr' ) || {};
	const materialsMode = ( typeof matRoot === 'object' && ( matRoot.mode || matRoot.materials_mode ) ) || null;
	const csDeclared = ( typeof matRoot === 'object' && matRoot.colorspace ) || {};
	const setsRaw = ( typeof matRoot === 'object'
		&& ( pick( matRoot, 'sets', 'per_material', 'materials', 'entries' )
			|| ( ! matRoot.mode && Object.keys( matRoot ).length ? matRoot : null ) ) )
		|| pick( raw, 'textures.per_material', 'textures.materials' ) || {};
	// Texture KEYS resolve through textures.gate2.files (Gate 2) and then through the Gate 1 list,
	// because an ORN occlusion map is carried unchanged from Gate 1 (`orn_<proto>_ao`).
	const texG2 = pick( raw, 'textures.gate2' ) || {};
	const filesG2 = ( texG2.files && typeof texG2.files === 'object' && ! Array.isArray( texG2.files ) ) ? texG2.files : {};
	const dirG2 = texG2.ktx2_dir || '';
	const filesG1 = pick( raw, 'textures.files' );
	const dirG1 = pick( raw, 'textures.ktx2_dir' ) || '';
	const joinDir = ( dir, p ) => resolveUrl( baseUrl, ( dir && ! p.startsWith( '/' ) ) ? `${String( dir ).replace( /\/$/, '' )}/${p}` : p );
	const unresolvedKeys = [];
	/** A texture reference: a KEY into textures.gate2.files (v3) or a path (older shapes). */
	const resolveTexture = ( ref ) => {
		if ( ! ref || typeof ref !== 'string' ) return null;
		const g2 = filesG2[ ref ];
		if ( g2 ) return { url: joinDir( dirG2, g2.path || `${ref}.ktx2` ), meta: g2 };
		if ( Array.isArray( filesG1 ) ) {
			const hit = filesG1.find( n => n === ref || n === `${ref}.ktx2` || ( typeof n === 'string' && n.startsWith( `${ref}.` ) ) );
			if ( hit ) return { url: joinDir( dirG1, hit ), meta: null };
		}
		if ( /\.(ktx2|png|jpg|jpeg|webp|exr|hdr)(\?.*)?$/i.test( ref ) ) return { url: joinDir( dirG2 || dirG1 || pick( raw, 'textures.ktx2_dir' ) || '', ref ), meta: filesG2[ ref.replace( /\.[^.]+$/, '' ) ] || null };
		unresolvedKeys.push( ref );
		return null;
	};
	const materialSets = {};
	const csFallbacks = [];
	let mapCount = 0, setBytes = 0, constantMaps = 0, noUv1 = 0, inGlbMaps = 0;
	for ( const [ name, entry ] of Object.entries( typeof setsRaw === 'object' && setsRaw ? setsRaw : {} ) ) {
		if ( ! entry || typeof entry !== 'object' ) continue;
		const src = entry.maps && typeof entry.maps === 'object' ? entry.maps : entry;
		const uv1 = entry.uv1_in_glb !== false;
		if ( ! uv1 ) noUv1 ++;
		const set = {
			name, maps: {}, factors: {}, uv1InGlb: uv1,
			job: entry.job ?? null, cls: entry.cls ?? null, srcMaterial: entry.src_material ?? null,
			size: entry.size ?? null, uv: matRoot.uv ?? entry.uv ?? src.uv ?? 'TEXCOORD_0',
			wrap: entry.wrap ?? src.wrap ?? null,
		};
		for ( const [ slot, aliases ] of Object.entries( MAP_KEYS ) ) {
			let v;
			for ( const a of aliases ) { if ( src[ a ] !== undefined && src[ a ] !== null ) { v = src[ a ]; break; } }
			if ( v === undefined ) continue;
			const o = ( typeof v === 'object' && v ) ? v : { path: v };
			// v3: `factor` is the baked mean — the value to use before (and instead of) the texture.
			if ( o.factor !== undefined && o.factor !== null ) set.factors[ slot ] = o.factor;
			if ( slot === 'normalMap' && o.scale !== undefined && o.scale !== null ) set.normalScale = o.scale;
			const hasTextureKey = Object.prototype.hasOwnProperty.call( o, 'texture' );
			const ref = hasTextureKey ? o.texture : ( o.path || o.url || o.file || o.ktx2 );
			// rule 2: a constant IS the map.  `in_glb: true` (the ORN occlusion) means the glb already
			// carries it and the viewer must load nothing.
			if ( ! ref ) { if ( o.in_glb === true ) inGlbMaps ++; else if ( hasTextureKey ) constantMaps ++; continue; }
			if ( ! uv1 ) continue;                                                   // rule: factors only, no UV1 in the glb
			const res = resolveTexture( ref );
			if ( ! res ) continue;
			const declared = ( o.colorspace ?? o.color_space ?? o.colour_space ?? o.encoding
				?? ( res.meta && res.meta.colorspace ) ?? csDeclared[ SRGB_SLOT[ slot ] ] ?? null );
			let srgb;
			if ( declared === null || declared === undefined ) { srgb = SRGB_DEFAULT[ slot ]; csFallbacks.push( `${name}.${slot}=${srgb ? 'sRGB' : 'linear'}` ); }
			else srgb = /srgb|s-rgb|colou?r$/i.test( String( declared ) ) && ! /non-?colou?r|linear|data|raw/i.test( String( declared ) );
			const bytes = o.bytes ?? o.size_bytes ?? ( res.meta && res.meta.bytes ) ?? null;
			set.maps[ slot ] = { url: res.url, srgb, declared, bytes,
				key: hasTextureKey ? ref : null, w: res.meta && res.meta.w, h: res.meta && res.meta.h,
				residentMb: res.meta && res.meta.resident_mb };
			mapCount ++; setBytes += bytes || 0;
		}
		const aliasRaw = entry.materials ?? entry.applies_to ?? entry.material_names ?? entry.material ?? entry.group_materials;
		set.aliases = ( Array.isArray( aliasRaw ) ? aliasRaw : ( typeof aliasRaw === 'string' ? [ aliasRaw ] : [] ) ).filter( x => typeof x === 'string' );
		if ( Object.keys( set.maps ).length || Object.keys( set.factors ).length ) materialSets[ name ] = set;
	}
	// --- materials.detail: the shared object-space tiling sets (QA-12-1) -----------------------
	// The Phase 5 concrete grain comes from a Bump with Distance 0.015 m, which no unique atlas can
	// carry (its texels are 3.8-11.8 cm), so the bake ships the five tiling sets Phase 5 itself uses
	// and the viewer re-creates the layer: albedo x (detail albedo / its own mean), roughness
	// likewise, the detail normal blended over the baked one.  `texture` here is a key too; the
	// files are PNGs under `detail/` next to the manifest (textures.gate2.detail_files has the
	// bytes but no path, detail.json has the paths).
	const detailRaw = ( typeof matRoot === 'object' && matRoot.detail ) || null;
	let detail = null;
	if ( detailRaw && detailRaw.sets ) {
		const dDir = detailRaw.dir || detailRaw.detail_dir || 'detail';
		// The set ships twice: a PNG under detail/ and a KTX2 next to the PBR atlases (1.33 MB
		// resident each, what textures.gate2.detail_files counts).  The PNG is used FIRST because
		// the layer divides by the map's own linear mean and only a decodable image can be measured
		// on the CPU; a compressed texture has no readable pixels.  The KTX2 (4x cheaper) becomes
		// the primary as soon as the manifest carries `mean_linear` per map — then nothing has to
		// be measured at run time.
		const detailFiles = ( texG2 && texG2.detail_files ) || {};
		const detailUrl = ( key, entry ) => {
			const given = entry && ( entry.path || entry.url );
			if ( given ) return { url: resolveUrl( baseUrl, given ), fallback: null };
			const png = resolveUrl( baseUrl, `${String( dDir ).replace( /\/$/, '' )}/${key}.png` );
			const ktx2 = ( detailFiles[ key ] && dirG2 ) ? joinDir( dirG2, `${key}.ktx2` ) : null;
			// The PNG is used whenever it exists, because the layer divides the SAMPLED value by the
			// map's mean and only the PNG guarantees the two are in the same space: the KTX2 albedo
			// is written with `--assign_oetf linear`, so the GPU returns the stored sRGB-encoded
			// bytes undecoded while `mean_linear` is the decoded mean — dividing one by the other
			// brightened the stone by 45 %.  The KTX2 set (4x cheaper) becomes the primary when the
			// bake tags the albedo srgb, or declares the mean in the sampled space.
			return { url: png, fallback: ktx2 };
		};
		const dSets = {};
		let dMaps = 0;
		for ( const [ name, set ] of Object.entries( detailRaw.sets ) ) {
			const maps = {};
			for ( const [ slot, key ] of [ [ 'map', 'albedo' ], [ 'roughnessMap', 'roughness' ], [ 'normalMap', 'normal' ] ] ) {
				const e = ( set.maps || set )[ key ];
				if ( ! e ) continue;
				const ref = typeof e === 'string' ? e : e.texture;
				if ( ! ref ) continue;
				const cs = ( typeof e === 'object' && e.colorspace ) || ( key === 'albedo' ? 'srgb' : 'linear' );
				const u = detailUrl( ref, typeof e === 'object' ? e : null );
				const declaredMean = ( typeof e === 'object' && ( e.mean_linear || e.mean ) ) || null;
				const declaredStd = ( typeof e === 'object' && ( e.std_linear || e.std ) ) || null;
				maps[ slot ] = { url: u.url, fallback: u.fallback, key: ref,
					meanLinear: Array.isArray( declaredMean ) ? declaredMean : null,
					stdLinear: Array.isArray( declaredStd ) ? declaredStd : null,
					srgb: /srgb/i.test( cs ), px: ( typeof e === 'object' && e.px ) || detailRaw.ship_px || 1024,
					bytes: detailFiles[ ref ] ? detailFiles[ ref ].bytes : null,
					residentMb: detailFiles[ ref ] ? detailFiles[ ref ].resident_mb : null };
				dMaps ++;
			}
			dSets[ name ] = { name, maps, tileM: set.tile_m ?? null };
		}
		// per_group is keyed by the GLB material name (authoritative); per_material by the Phase 5
		// source material name, matched through the same candidate keys as the PBR sets.
		const rule = ( r ) => ( ! r ? null : { set: r.set, scale: r.object_scale, tileM: r.tile_m,
			mmPerTexel: r.mm_per_texel, coordSpace: r.coord_space || 'object' } );
		const perGroup = {}, groupExtras = [];
		for ( const [ mat, entry ] of Object.entries( detailRaw.per_group || {} ) ) {
			const rules = Object.entries( entry ).map( ( [ src, r ] ) => ( { src, ...rule( r ) } ) ).filter( r => r.set && dSets[ r.set ] );
			if ( ! rules.length ) continue;
			// A merged group lists several source materials with different sets; one material can
			// carry one, so the FIRST is used and the others are reported.
			perGroup[ mat ] = rules[ 0 ];
			if ( rules.length > 1 ) groupExtras.push( `${mat}: ${rules.map( r => r.src ).join( ' + ' )} -> ${rules[ 0 ].set}` );
		}
		const perMaterial = {};
		for ( const [ src, r ] of Object.entries( detailRaw.per_material || {} ) ) {
			const v = rule( r );
			if ( v && dSets[ v.set ] ) perMaterial[ src ] = { src, ...v };
		}
		detail = { mode: detailRaw.mode || null, shipPx: detailRaw.ship_px || 1024,
			bumpDistanceM: detailRaw.bump_distance_m ?? null, apply: detailRaw.apply || null,
			sets: dSets, perGroup, perMaterial, maps: dMaps };
		notes.push( `materials.detail: ${Object.keys( dSets ).length} tiling set(s), ${dMaps} maps, `
			+ `${Object.keys( perGroup ).length} glb material rule(s) + ${Object.keys( perMaterial ).length} source-material rule(s), `
			+ `mode "${detail.mode}", bump distance ${detail.bumpDistanceM} m` );
		if ( groupExtras.length ) notes.push( `detail: ${groupExtras.length} merged group(s) list more than one source material, the first is used: ${groupExtras.join( '; ' )}` );
	}

	const materials = {
		mode: materialsMode,
		detail,
		sets: materialSets,
		count: Object.keys( materialSets ).length,
		maps: mapCount,
		constantMaps,
		inGlbMaps,
		withoutUv1: noUv1,
		declaredBytes: setBytes,
		budget: pick( raw, 'budget' ) || null,
		gate2Textures: { dir: dirG2, files: Object.keys( filesG2 ).length,
			bytes: texG2.bytes ?? null, residentMb: texG2.resident_mb ?? null },
	};
	if ( materials.count ) {
		notes.push( `materials: ${materials.count} set(s), ${mapCount} textures`
			+ ( constantMaps ? `, ${constantMaps} constant map(s) shipped as a factor` : '' )
			+ ( inGlbMaps ? `, ${inGlbMaps} map(s) already in the glb (in_glb, nothing loaded)` : '' )
			+ ( noUv1 ? `, ${noUv1} set(s) with uv1_in_glb false (factors only)` : '' )
			+ ( setBytes ? `, ${( setBytes / 1e6 ).toFixed( 1 )} MB declared` : ', no declared bytes (HEAD)' )
			+ `, mode "${materialsMode || '(unstated)'}"` );
		if ( csFallbacks.length ) notes.push( `colour space defaulted on ${csFallbacks.length} map(s) (manifest states none): ${csFallbacks.slice( 0, 6 ).join( ', ' )}${csFallbacks.length > 6 ? ' …' : ''}` );
		if ( unresolvedKeys.length ) notes.push( `${unresolvedKeys.length} texture key(s) not in textures.gate2.files or the Gate 1 list, skipped: ${[ ...new Set( unresolvedKeys ) ].slice( 0, 6 ).join( ', ' )}` );
	} else if ( materialsMode ) {
		notes.push( `materials.mode "${materialsMode}" but no per-material texture set was recognised` );
	}


	// --- Gate 1 extras: far-tree billboard quads, ORN atlas slots ------------------------------
	// `trees.far` is the Gate 3 impostor list: each entry is a prototype id, a height and a trunk base.
	// Until that bake exists the viewer draws one flat, explicitly tagged quad per entry.
	const treesRaw = pick( raw, 'trees', 'tree_lists', 'vegetation' ) || {};
	const farRaw = pick( raw, 'tree_far' ) || pick( treesRaw, 'far', 'billboards', 'far_list' ) || [];
	const treesFar = ( Array.isArray( farRaw ) ? farRaw : [] ).map( ( t ) => ( {
		prototype: t.prototype ?? t.proto ?? t.id ?? t.name ?? 'tree',
		id: t.billboard ?? null,
		height: t.height_m ?? t.height ?? t.h ?? 12,
		width: t.width_m ?? t.width ?? t.w ?? null,
		base: t.trunk_base ?? t.base ?? t.location_blender ?? t.location ?? t.position ?? null,
	} ) ).filter( t => Array.isArray( t.base ) && t.base.length === 3 );
	if ( farRaw.length && treesFar.length !== farRaw.length )
		notes.push( `tree_far: ${farRaw.length - treesFar.length} of ${farRaw.length} entries have no trunk base, skipped` );
	const nearRaw = pick( raw, 'tree_near' ) || pick( treesRaw, 'near', 'near_list' ) || [];
	// v2: orn_slots = { <pool>: [ {object, atlas, slot}, ... ] }.  Gate 1 has no atlas texture yet;
	// the viewer only reports the reservation so a Gate 3 regression is visible in the sidecar.
	const ornSlotsRaw = pick( raw, 'orn_slots', 'orn.slots', 'ornament.slots' ) || null;
	const ornSlots = ornSlotsRaw && typeof ornSlotsRaw === 'object' && ! Array.isArray( ornSlotsRaw )
		? Object.fromEntries( Object.entries( ornSlotsRaw ).map( ( [ pool, v ] ) => [ pool, {
			entries: Array.isArray( v ) ? v.length : null,
			atlases: Array.isArray( v ) ? new Set( v.map( e => e.atlas ) ).size : null,
		} ] ) )
		: ornSlotsRaw;

	const out = {
		raw, baseUrl, glb, glbs, stations, lut, exposure, sun, lightmaps, notes, rgbmRange, lightmapScale, materials,
		treesFar, treesNearCount: Array.isArray( nearRaw ) ? nearRaw.length : 0, ornSlots,
		schema: pick( raw, 'schema' ) || null,
		waterZ: def( pick( raw, 'water.viewer_y', 'water.water_z', 'water_z', 'waterZ', 'scene.water_z' ), WATER_Z, 'water_z' ),
		sky: { camera: skyCamera, glossy: skyGlossy, rotationDeg: skyRotationDeg },
		frameSize: pick( raw, 'frame', 'render.frame' ) || { width: 1280, height: 720 },
	};
	if ( ! glbs.length ) notes.push( 'no glb in the manifest: test scene only' );
	return out;
}
